import { useCallback, useState } from 'react';
import { useFocusEffect } from 'expo-router';
import { Text } from 'react-native';
import { Card, CardTitle, CardValue } from '@/components/Card';
import { Screen, Section } from '@/components/Screen';
import { latestSelfBelief } from '@/storage/repositories/selfBeliefRepository';
import { latestHypothesis } from '@/storage/repositories/hypothesisRepository';
import { latestEvaluation, listEvaluations } from '@/storage/repositories/evaluationRepository';
import { colors } from '@/theme';
function status(result?: string) { return ({ supports: 'Supported', challenges: 'Challenged', inconclusive: 'Inconclusive', insufficient_data: 'Inconclusive' } as Record<string, string>)[result ?? ''] ?? '未評価'; }
function interpretation(result?: string) { if (result === 'supports') return '現在の観測は、登録した仮説と同じ方向を示しています。ただし、確定的なプロフィールではありません。'; if (result === 'challenges') return '現在の観測は、登録した自己認識とは異なる方向を示しています。ただし、原因や性格を断定するものではありません。'; if (result === 'inconclusive' || result === 'insufficient_data') return '現在は観測数または差が十分でないため、まだ判断できません。'; return '観測を重ねると、ここに暫定的な解釈が表示されます。'; }
export default function SelfModel() { const [belief, setBelief] = useState<any>(null); const [hypothesis, setHypothesis] = useState<any>(null); const [evaluation, setEvaluation] = useState<any>(null); const [history, setHistory] = useState<any[]>([]); useFocusEffect(useCallback(() => { Promise.all([latestSelfBelief(), latestHypothesis(), latestEvaluation(), listEvaluations()]).then(([b, h, e, items]) => { setBelief(b); setHypothesis(h); setEvaluation(e); setHistory(items); }); }, [])); return <Screen eyebrow="SELF MODEL" title="暫定的な自己理解"><Section><Card><CardTitle>Self Belief</CardTitle><CardValue>{belief?.statement ?? '未登録'}</CardValue></Card><Card tone="teal"><CardTitle>Tracking Hypothesis</CardTitle><CardValue>{hypothesis?.statement ?? '未登録'}</CardValue></Card><Card><CardTitle>Current Status</CardTitle><CardValue>{status(evaluation?.result)}</CardValue><Text style={{ color: colors.ink }}>Current Observation</Text><Text style={{ color: colors.muted }}>{interpretation(evaluation?.result)}</Text></Card><Card><CardTitle>Provisional Self Model</CardTitle><Text style={{ color: colors.ink, lineHeight: 23 }}>{interpretation(evaluation?.result)}</Text></Card><Card><CardTitle>Evaluation History</CardTitle>{history.map((item) => <Text key={item.id} style={{ color: colors.muted }}>{new Date(item.evaluated_at).toLocaleString()} / {status(item.result)} / effect {item.observed_effect === null ? '-' : Number(item.observed_effect).toFixed(2)}</Text>)}</Card></Section></Screen>; }
