import { useCallback, useState } from 'react';
import { useFocusEffect } from 'expo-router';
import { Text } from 'react-native';
import { Card, CardTitle, CardValue } from '@/components/Card';
import { Screen, Section } from '@/components/Screen';
import { latestSelfBelief } from '@/storage/repositories/selfBeliefRepository';
import { latestHypothesis } from '@/storage/repositories/hypothesisRepository';
import { latestEvaluation, listEvaluations } from '@/storage/repositories/evaluationRepository';
import { colors } from '@/theme';
import { templateByKey } from '@/features/hypothesisTemplates';
function status(result?: string) { return ({ supports: 'Supported', challenges: 'Challenged', inconclusive: 'Inconclusive', insufficient_data: 'Inconclusive' } as Record<string, string>)[result ?? ''] ?? '未評価'; }
function interpretation(result: string | undefined, template: ReturnType<typeof templateByKey>) { if (result === 'supports') return template.supportedMessage; if (result === 'challenges') return template.challengedMessage; if (result === 'inconclusive' || result === 'insufficient_data') return template.inconclusiveMessage; return 'No evaluation yet.'; }
export default function SelfModel() { const [belief, setBelief] = useState<any>(null); const [hypothesis, setHypothesis] = useState<any>(null); const [evaluation, setEvaluation] = useState<any>(null); const [history, setHistory] = useState<any[]>([]); useFocusEffect(useCallback(() => { Promise.all([latestSelfBelief(), latestHypothesis(), latestEvaluation(), listEvaluations()]).then(([b, h, e, items]) => { setBelief(b); setHypothesis(h); setEvaluation(e); setHistory(items); }); }, [])); const template = templateByKey(hypothesis?.template_key ?? 'night_completion'); const message = interpretation(evaluation?.result, template); return <Screen eyebrow="SELF MODEL" title="暫定的な自己理解"><Section><Card><CardTitle>Self Belief</CardTitle><CardValue>{belief?.statement ?? 'Not registered'}</CardValue></Card><Card tone="teal"><CardTitle>Tracking Hypothesis</CardTitle><CardValue>{hypothesis?.statement ?? 'Not registered'}</CardValue><Text style={{ color: colors.muted }}>Lifecycle: {hypothesis?.state ?? 'unknown'}</Text></Card><Card><CardTitle>Latest Evaluation</CardTitle><CardValue>{status(evaluation?.result)}</CardValue><Text style={{ color: colors.ink }}>{message}</Text></Card><Card><CardTitle>Provisional Self Model</CardTitle><Text style={{ color: colors.ink, lineHeight: 23 }}>{message}</Text></Card><Card><CardTitle>Evaluation History</CardTitle>{history.map((item) => <Text key={item.id} style={{ color: colors.muted }}>{new Date(item.evaluated_at).toLocaleString()} / {status(item.result)} / effect {item.observed_effect === null ? '-' : Number(item.observed_effect).toFixed(2)}</Text>)}</Card></Section></Screen>; }
