import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput } from 'react-native';
import { Screen, Section, Label } from '@/components/Screen';
import { Card } from '@/components/Card';
import { colors } from '@/theme';
import { cancelMeTheoryNotifications, scheduleNextCheckin } from '@/notifications/scheduler';
import { defaultNotificationSettings, getNotificationSettings, setSetting, type NotificationSettings } from '@/storage/repositories/settingsRepository';

export default function Settings() { const [settings, setSettings] = useState<NotificationSettings>(defaultNotificationSettings); useEffect(() => { getNotificationSettings().then(setSettings); }, []); async function update(next: NotificationSettings) { setSettings(next); await setSetting('notification_settings', next); if (next.notification_enabled) await scheduleNextCheckin(); else await cancelMeTheoryNotifications(); } return <Screen eyebrow="SETTINGS" title="自分のペース"><Section><Card><Label>ローカル保存</Label><Text style={styles.text}>Self Belief、Hypothesis、観測、評価履歴はこの端末のSQLiteに保存されます。</Text></Card><Pressable onPress={() => update({ ...settings, notification_enabled: !settings.notification_enabled })} style={styles.toggle}><Text style={styles.text}>チェックイン通知</Text><Text style={styles.state}>{settings.notification_enabled ? 'ON' : 'OFF'}</Text></Pressable><Label>通知開始</Label><TextInput value={settings.window_start} onChangeText={(value) => update({ ...settings, window_start: value })} style={styles.input} /><Label>通知終了</Label><TextInput value={settings.window_end} onChangeText={(value) => update({ ...settings, window_end: value })} style={styles.input} /><Label>一日の上限: {settings.daily_limit}</Label><Pressable onPress={() => update({ ...settings, daily_limit: settings.daily_limit >= 3 ? 1 : settings.daily_limit + 1 })} style={styles.stepper}><Text style={styles.text}>上限を変更</Text></Pressable><Label>最小通知間隔: {settings.minimum_interval_minutes}分</Label><Pressable onPress={() => update({ ...settings, minimum_interval_minutes: settings.minimum_interval_minutes >= 360 ? 60 : settings.minimum_interval_minutes + 60 })} style={styles.stepper}><Text style={styles.text}>間隔を変更</Text></Pressable></Section></Screen>; }
const styles = StyleSheet.create({ text: { color: colors.ink, fontSize: 15, lineHeight: 23 }, toggle: { minHeight: 56, paddingHorizontal: 16, borderRadius: 8, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, state: { color: colors.teal, fontWeight: '800' }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, borderRadius: 8, paddingHorizontal: 14, color: colors.ink }, stepper: { minHeight: 48, justifyContent: 'center', paddingHorizontal: 16, borderRadius: 8, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line } });
