import test from 'node:test';
import assert from 'node:assert/strict';
import { AiResponseCache, DeterministicFallbackProvider, MockAiProvider, assessReplication, assessReplicationLifecycle, evaluateQuestionBudget, generateSyntheticDataset, validateAiGenerationOutput } from '../packages/domain/src/index.ts';

test('synthetic data reproduces a known direction', () => { const dataset = generateSyntheticDataset({ count: 100, seed: 7 }); assert.equal(dataset.observations.length, 200); assert.equal(dataset.expectedDirection, 'a_greater_than_b'); });
test('question budget blocks daily, hourly and cooldown limits', () => { assert.equal(evaluateQuestionBudget({ now: '2026-07-25T12:00:00.000Z', todayCount: 6, hourCount: 0, hypothesisTodayCount: 0, consecutiveSkips: 0 }).reason, 'daily_budget_exceeded'); assert.equal(evaluateQuestionBudget({ now: '2026-07-25T12:00:00.000Z', todayCount: 0, hourCount: 2, hypothesisTodayCount: 0, consecutiveSkips: 0 }).reason, 'hourly_budget_exceeded'); });
test('question budget applies overnight quiet hours, pause duration, and response rate', () => { assert.equal(evaluateQuestionBudget({ now: '2026-07-25T14:00:00.000Z', todayCount: 0, hourCount: 0, hypothesisTodayCount: 0, consecutiveSkips: 0, quietHoursStart: '22:00', quietHoursEnd: '07:00' }).reason, 'quiet_hours'); const paused = evaluateQuestionBudget({ now: '2026-07-25T12:00:00.000Z', todayCount: 0, hourCount: 0, hypothesisTodayCount: 0, consecutiveSkips: 3 }); assert.equal(paused.reason, 'pause_active'); assert.ok(paused.pauseUntil); assert.equal(evaluateQuestionBudget({ now: '2026-07-25T12:00:00.000Z', todayCount: 0, hourCount: 0, hypothesisTodayCount: 0, consecutiveSkips: 0, recentResponseRate: 0.1 }).reason, 'low_recent_response_rate'); });
test('replication separates stable support from contradiction', () => { const result = assessReplication([{ period: 'before', effectValue: 0.4, normalizedEffect: 0.4, direction: 'supports' }, { period: 'after', effectValue: 0.3, normalizedEffect: 0.3, direction: 'supports' }]); assert.equal(result.status, 'supports'); assert.equal(result.stability, 1); });
test('replication lifecycle excludes discovery from replication status', () => { const result = assessReplicationLifecycle([{ period: 'discovery', effectValue: 0.5, normalizedEffect: 0.5, direction: 'supports' }, { period: 'validation', effectValue: 0.4, normalizedEffect: 0.4, direction: 'supports' }, { period: 'replication', effectValue: 0.3, normalizedEffect: 0.3, direction: 'supports' }]); assert.equal(result.status, 'replicated'); });
test('AI provider validates structured fields and caches deterministic responses', async () => { const fallback = await new DeterministicFallbackProvider().generate({ generationType: 'question', structuredInput: { parameterName: 'energy', parameterId: 'energy_level', answerType: 'ordinal', optionKeys: [] }, promptVersion: 'v1', locale: 'ja-JP' }); assert.equal(fallback.fallbackUsed, true); assert.equal(validateAiGenerationOutput(fallback.output, { generationType: 'question', parameterId: 'energy_level', answerType: 'ordinal', optionKeys: [] }).valid, true); assert.equal(validateAiGenerationOutput({ text: 'This proves the hypothesis.' }).valid, false); assert.equal(validateAiGenerationOutput({ text: 'ok', parameterId: 'other', answerType: 'ordinal', optionKeys: [] }, { generationType: 'question', parameterId: 'energy_level', answerType: 'ordinal', optionKeys: [] }).valid, false); const cache = new AiResponseCache(1000); cache.set('same', fallback); assert.equal(cache.get('same')?.cacheHit, true); const mock = await new MockAiProvider({ text: 'mock' }).generate({ generationType: 'question', structuredInput: {}, promptVersion: 'v1', locale: 'ja-JP' }); assert.equal(mock.provider, 'mock'); });
