import test from 'node:test';
import assert from 'node:assert/strict';
import { buildCohorts, calculateOutcomeMetric, generateHypothesisCandidates } from '../packages/domain/src/hypothesis/candidates.ts';

const parameter = (id: string, valueType: string, condition: boolean, outcome: boolean, min = 1, max = 5) => ({ id, nameJa: id, valueType, minimumValue: min, maximumValue: max, usableAsCondition: condition, usableAsOutcome: outcome });
test('cohorts split boolean and numeric parameters', () => { assert.deepEqual(buildCohorts(parameter('x', 'boolean', true, false)).map((item) => item.key), ['true', 'false']); assert.deepEqual(buildCohorts(parameter('x', 'number', true, false)).map((item) => item.key), ['low', 'high']); });
test('integer midpoint assigns every value to exactly one cohort', () => { const cohorts = buildCohorts(parameter('x', 'integer', true, false, 1, 5)); const matches = [1, 2, 3, 4, 5].map((value) => cohorts.filter((cohort) => cohort.condition.type === 'range' && (cohort.condition.minimum === undefined || value >= cohort.condition.minimum) && (cohort.condition.maximum === undefined || value <= cohort.condition.maximum)).length); assert.deepEqual(matches, [1, 1, 1, 1, 1]); });
test('outcome metrics exclude missing values and calculate means', () => { assert.equal(calculateOutcomeMetric([1, 3, null], parameter('x', 'number', false, true)).value, 2); assert.equal(calculateOutcomeMetric([true, false, null], parameter('x', 'boolean', false, true)).value, 0.5); });
test('choice outcome uses its declared positive values', () => { assert.equal(calculateOutcomeMetric(['started', 'completed', 'skipped'], { ...parameter('x', 'single_choice', false, true), positiveValues: ['completed'] }).value, 1 / 3); });
test('candidate generation enforces sample and effect thresholds', () => { const observations = Array.from({ length: 12 }, (_, index) => ({ episodeId: `e${index}`, parameterId: index < 6 ? 'condition' : 'condition', value: index < 6, observedAt: '2026-07-24T00:00:00.000Z' })).flatMap((row, index) => [row, { episodeId: `e${index}`, parameterId: 'outcome', value: index < 6 ? 5 : 1, observedAt: row.observedAt }]); const candidates = generateHypothesisCandidates({ parameters: [parameter('condition', 'boolean', true, false), parameter('outcome', 'number', false, true)], observations, now: '2026-07-24T12:00:00.000Z' }); assert.equal(candidates.length, 1); assert.equal(candidates[0].relation, 'a_greater_than_b'); assert.equal(candidates[0].sampleBalance, 1); });
test('missing outcomes do not satisfy the valid cohort minimum', () => { const observations = Array.from({ length: 12 }, (_, index) => [{ episodeId: `missing-${index}`, parameterId: 'condition', value: index < 6, observedAt: '2026-07-24T00:00:00.000Z' }, { episodeId: `missing-${index}`, parameterId: 'outcome', value: index % 3 === 0 ? null : index < 6 ? 5 : 1, isMissing: index % 3 === 0, observedAt: '2026-07-24T00:00:00.000Z' }]).flat(); const candidates = generateHypothesisCandidates({ parameters: [parameter('condition', 'boolean', true, false), parameter('outcome', 'number', false, true)], observations, now: '2026-07-24T12:00:00.000Z' }); assert.equal(candidates.length, 0); });
