import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { spawn } from "node:child_process";
import { DatabaseSync } from "node:sqlite";
import { test } from "node:test";

async function waitForHealth(url: string) { for (let i=0;i<40;i++) { try { const r=await fetch(url); if(r.ok) return; } catch {} await new Promise(r=>setTimeout(r,100)); } throw new Error("api_start_timeout"); }
test("PCS schema migration is idempotent", () => { const dir=mkdtempSync(join(tmpdir(),"pcs-migration-")); const db=new DatabaseSync(join(dir,"db.sqlite")); const schema=readFileSync("db/ts_mvp_schema.sql","utf8"); db.exec(schema); db.exec(schema); for(const name of ["pcs_profile_bindings","pcs_analysis_runs","pcs_candidate_reviews","pcs_experiment_drafts","pcs_experiments"]) assert.ok(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(name)); db.close(); rmSync(dir,{recursive:true,force:true}); });
test("PCS HTTP flow reaches deterministic evaluation", async () => { const dir=mkdtempSync(join(tmpdir(),"pcs-e2e-")); const dbPath=join(dir,"db.sqlite"); const port=18991; const child=spawn(process.execPath,["--experimental-strip-types","apps/api/src/server.ts"],{env:{...process.env,PORT:String(port),METHEORY_DB:dbPath},stdio:"ignore"}); try { await waitForHealth(`http://127.0.0.1:${port}/healthz`); const post=async(path:string,payload:unknown)=>{const r=await fetch(`http://127.0.0.1:${port}${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}); assert.ok(r.status<500,`${path}: ${r.status}`); return await r.json() as Record<string,unknown>}; const user={userId:"demo-user"}; await post("/v1/users",{...user,authSubject:"demo-user"}); const bound=await post("/v1/pcs/profile-binding",{...user,profileId:"demo-profile"}); assert.ok(bound.binding); const snapshot={schemaVersion:"pcs-analysis-snapshot-v2",snapshotId:"e2e-snapshot",profileId:"demo-profile",period:{from:"2026-07-01T00:00:00.000Z",to:"2026-07-31T00:00:00.000Z",timezone:"UTC"},records:[{recordId:"r1",recordedAt:"2026-07-10T00:00:00.000Z",templateId:"t",templateVersionId:"v",fieldKey:"clarity",valueType:"number",value:4,analysisRole:"task_clarity",analysisRoleConfirmed:true,analysisUsage:"condition",analysisMergeAllowed:false}]}; const run=await post("/v1/pcs/analyze",{...user,snapshot}); const draft=await post("/v1/pcs/experiment-draft",{...user,runId:run.runId,candidateId:"candidate_1",title:"E2E",plan:{}}); await post(`/v1/pcs/experiment-draft/${draft.id}/accept`,user); const experiment=await post(`/v1/pcs/experiments/${draft.id}/start`,user); await post(`/v1/pcs/experiments/${experiment.id}/observation`,{...user,observation:{group:"A",value:4}}); await post(`/v1/pcs/experiments/${experiment.id}/observation`,{...user,observation:{group:"B",value:2}}); await post(`/v1/pcs/experiments/${experiment.id}/transition`,{...user,status:"completed"}); const evaluation=await post(`/v1/pcs/experiments/${experiment.id}/evaluate`,user); assert.equal(evaluation.status,"evaluated"); } finally { child.kill(); await new Promise(r=>setTimeout(r,150)); try { rmSync(dir,{recursive:true,force:true}); } catch {} } });
