import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
async function start(port:number,database:string){const child=spawn(process.execPath,["--experimental-strip-types","apps/api/src/server.ts"],{env:{...process.env,PORT:String(port),METHEORY_DB:database},stdio:"ignore"});for(let i=0;i<40;i++){try{if((await fetch(`http://127.0.0.1:${port}/healthz`)).ok)return child}catch{}await new Promise(r=>setTimeout(r,100))}child.kill();throw new Error("server_not_ready")}
const post=async(base:string,path:string,value:unknown)=>{const response=await fetch(base+path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(value)});return{response,body:await response.json() as any}};
test("hypothesis ratings and self-model approval are covered",async()=>{const port=18500+Math.floor(Math.random()*100),directory=mkdtempSync(join(tmpdir(),"metheory-review-api-")),database=join(directory,"review.sqlite3"),child=await start(port,database),base=`http://127.0.0.1:${port}`;try{const db=new DatabaseSync(database),userId="review-user",now="2026-08-01T00:00:00.000Z";db.prepare("INSERT INTO users(id,auth_subject,locale,timezone,created_at) VALUES(?,?,?,?,?)").run(userId,"review-auth","ja-JP","Asia/Tokyo",now);const snapshot=(candidateId:string,statement:string)=>JSON.stringify({candidateId,period:{startAt:"2026-07-01T00:00:00.000Z",endAt:"2026-07-31T00:00:00.000Z"},construct:"task_initiation",tendencyScope:"single_period_state",selfModelCandidate:statement,interpretationInput:{condition:{fieldKey:"task_clarity"},outcome:{fieldKey:"start_delay"}}});for(const [candidateId,statement] of [["fits-candidate","明確な作業条件では開始が早い"],["does-not-fit-candidate","反証される仮説"],["hold-candidate","まだ判断保留"]] as const)db.prepare("INSERT INTO self_understanding_analysis_history(id,user_id,candidate_id,construct_key,condition_role,outcome_role,relation,period_start_at,period_end_at,complete_pair_count,condition_field_key,outcome_field_key,source_entry_ids_json,source_entry_fingerprint,evidence_provenance_json,candidate_snapshot_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`history-${candidateId}`,userId,candidateId,"task_initiation","task_clarity","start_delay","a_less_than_b","2026-07-01T00:00:00.000Z","2026-07-31T00:00:00.000Z",8,"task_clarity","start_delay","[]","","{}",snapshot(candidateId,statement),now);db.close();for(const [candidateId,rating] of [["fits-candidate","fits"],["does-not-fit-candidate","does_not_fit"],["hold-candidate","on_hold"]] as const){const result=await post(base,"/v1/self-understanding/reviews",{userId,candidateId,rating});assert.equal(result.response.status,201);assert.equal(result.body.rating,rating);assert.equal(result.body.selfModelUpdate,rating==="fits"?"proposed":"none")}const candidates=await fetch(`${base}/v1/self-understanding/self-model-candidates?userId=${userId}`),proposed=(await candidates.json() as any).items.find((item:any)=>item.candidate_id==="fits-candidate");assert.ok(proposed);const approved=await post(base,"/v1/self-understanding/self-model-candidates/review",{userId,candidateId:proposed.id,status:"accepted"});assert.equal(approved.response.status,200);const db2=new DatabaseSync(database);assert.equal((db2.prepare("SELECT status FROM self_model_candidates WHERE id=?").get(proposed.id) as any).status,"accepted");assert.equal((db2.prepare("SELECT COUNT(*) AS count FROM self_beliefs WHERE id=?").get(approved.body.selfBeliefId) as any).count,1);db2.close()}finally{child.kill();await new Promise(r=>setTimeout(r,150));try{rmSync(directory,{recursive:true,force:true})}catch{}}});
