import * as Notifications from 'expo-notifications';
import { createCheckin } from '@/storage/repositories/checkinRepository';
import { trackingHypothesis } from '@/storage/repositories/hypothesisRepository';
import { saveNotificationSchedule, todaySchedules } from '@/storage/repositories/notificationRepository';
import { getNotificationSettings } from '@/storage/repositories/settingsRepository';
import { chooseFutureMinute } from './policy';

Notifications.setNotificationHandler({ handleNotification: async () => ({ shouldPlaySound: false, shouldSetBadge: false, shouldShowBanner: true, shouldShowList: true }) });
export async function scheduleNextCheckin(seed = Date.now()) { const settings = await getNotificationSettings(); if (!settings.notification_enabled) return null; const permission = await Notifications.requestPermissionsAsync(); if (!permission.granted) return null; const existing = await todaySchedules(); if (existing.length >= settings.daily_limit) return null; const occupied = existing.map((item) => { const date = new Date(item.scheduled_at); return date.getHours() * 60 + date.getMinutes(); }); const minute = chooseFutureMinute(seed, new Date(), settings, occupied); if (minute === null) return null; const hypothesis = await trackingHypothesis(); const checkin = await createCheckin('hypothesis', hypothesis?.id ?? null); const scheduledAt = new Date(); scheduledAt.setHours(Math.floor(minute / 60), minute % 60, 0, 0); if (scheduledAt <= new Date()) scheduledAt.setDate(scheduledAt.getDate() + 1); const notificationId = await Notifications.scheduleNotificationAsync({ content: { title: 'MeTheory', body: '今の観察を短く記録しませんか？', data: { route: '/checkin', checkinId: checkin.id, hypothesisId: checkin.hypothesisId, kind: checkin.kind, expiresAt: checkin.expiresAt } }, trigger: { type: Notifications.SchedulableTriggerInputTypes.DATE, date: scheduledAt } }); await saveNotificationSchedule({ checkinId: checkin.id, hypothesisId: checkin.hypothesisId, kind: checkin.kind, scheduledAt: scheduledAt.toISOString(), expiresAt: checkin.expiresAt, notificationId }); return notificationId; }
export async function cancelMeTheoryNotifications() { await Notifications.cancelAllScheduledNotificationsAsync(); }
