export type AiGenerationInput = { generationType: 'question' | 'hypothesis_explanation' | 'self_model'; structuredInput: Record<string, unknown>; promptVersion: string; locale: string; model?: string };
export type AiGenerationResult = { output: unknown; provider: string; model: string; inputTokens: number; outputTokens: number; latencyMs: number; cacheHit: boolean; fallbackUsed: boolean };
export type AiProvider = { providerKey: string; generate(input: AiGenerationInput): Promise<AiGenerationResult> };

export class DeterministicFallbackProvider implements AiProvider {
  readonly providerKey = 'deterministic_fallback';
  async generate(input: AiGenerationInput) { const parameter = String(input.structuredInput.parameterName ?? 'この項目'); const output = { text: `現在の「${parameter}」を入力してください。`, answerSchema: input.structuredInput.answerSchema ?? {} }; return { output, provider: this.providerKey, model: 'fallback-v1', inputTokens: 0, outputTokens: 0, latencyMs: 0, cacheHit: false, fallbackUsed: true }; }
}
export class MockAiProvider implements AiProvider { readonly providerKey = 'mock'; private readonly output: unknown; constructor(output: unknown = { text: 'mock' }) { this.output = output; } async generate(input: AiGenerationInput) { return { output: this.output, provider: this.providerKey, model: input.model ?? 'mock-v1', inputTokens: 1, outputTokens: 1, latencyMs: 0, cacheHit: false, fallbackUsed: false }; } }
export class AiProviderRegistry { private readonly providers = new Map<string, AiProvider>(); register(provider: AiProvider) { this.providers.set(provider.providerKey, provider); } get(providerKey: string) { return this.providers.get(providerKey); } }
export type AiUsageLog = { provider: string; model: string; latencyMs: number; inputTokens: number; outputTokens: number; estimatedCostUsd: number; cacheHit: boolean; fallbackUsed: boolean; validationErrors: string[] };
export class AiResponseCache { private readonly values = new Map<string, { expiresAt: number; value: AiGenerationResult }>(); private readonly ttlMs: number; constructor(ttlMs = 15 * 60 * 1000) { this.ttlMs = ttlMs; } get(key: string) { const entry = this.values.get(key); if (!entry || entry.expiresAt < Date.now()) { this.values.delete(key); return undefined; } return { ...entry.value, cacheHit: true }; } set(key: string, value: AiGenerationResult) { this.values.set(key, { expiresAt: Date.now() + this.ttlMs, value }); } }
export class OpenAiProvider implements AiProvider {
  readonly providerKey = 'openai'; private readonly apiKey: string; private readonly model: string; private readonly endpoint: string; private readonly cache: AiResponseCache;
  constructor(input: { apiKey: string; model?: string; endpoint?: string; cache?: AiResponseCache }) { this.apiKey = input.apiKey; this.model = input.model ?? 'gpt-4o-mini'; this.endpoint = input.endpoint ?? 'https://api.openai.com/v1/responses'; this.cache = input.cache ?? new AiResponseCache(); }
  async generate(input: AiGenerationInput): Promise<AiGenerationResult> { const cacheKey = JSON.stringify({ model: input.model ?? this.model, generationType: input.generationType, structuredInput: input.structuredInput, promptVersion: input.promptVersion, locale: input.locale }); const cached = this.cache.get(cacheKey); if (cached) return cached; const startedAt = Date.now(); const response = await fetch(this.endpoint, { method: 'POST', headers: { authorization: `Bearer ${this.apiKey}`, 'content-type': 'application/json' }, body: JSON.stringify({ model: input.model ?? this.model, input: [{ role: 'system', content: 'Return JSON only. Do not expose private identifiers, raw records, or sensitive values.' }, { role: 'user', content: JSON.stringify({ generationType: input.generationType, locale: input.locale, promptVersion: input.promptVersion, input: input.structuredInput }) }], text: { format: { type: 'json_object' } } }) }); if (!response.ok) throw new Error(`openai_http_${response.status}`); const payload = await response.json() as { output_text?: string; usage?: { input_tokens?: number; output_tokens?: number } }; let output: unknown; try { output = JSON.parse(payload.output_text ?? ''); } catch { throw new Error('openai_invalid_json'); } const result = { output, provider: this.providerKey, model: input.model ?? this.model, inputTokens: payload.usage?.input_tokens ?? 0, outputTokens: payload.usage?.output_tokens ?? 0, latencyMs: Date.now() - startedAt, cacheHit: false, fallbackUsed: false }; this.cache.set(cacheKey, result); return result; }
}
export function validateAiGenerationOutput(output: unknown) { if (!output || typeof output !== 'object') return { valid: false, errors: ['invalid_json'] }; const value = output as Record<string, unknown>; if (typeof value.text !== 'string' || !value.text.trim() || value.text.length > 240) return { valid: false, errors: ['invalid_text'] }; if (/This proves|definitely|definitively|証明|絶対|確実|間違いなく|仮説は正しい/i.test(value.text)) return { valid: false, errors: ['leading_or_disclosing_text'] }; return { valid: true, errors: [] }; }
