export type SourceProviderKey = 'system_clock' | 'device_activity' | 'calendar' | 'health' | 'weather' | 'screen_time' | 'location' | 'manual_import' | 'test_fixture';
export type SourceCapability = 'read_events' | 'read_samples' | 'read_current_state' | 'read_daily_summary' | 'subscribe_changes';
export type SourcePermissionStatus = 'not_required' | 'not_requested' | 'granted' | 'denied' | 'restricted' | 'unavailable';
export type SourceFetchReason = 'initial_import' | 'scheduled_refresh' | 'hypothesis_required' | 'user_requested' | 'recovery';
export type SourceFetchInput = { userId: string; startAt: string; endAt: string; requestedParameterIds: string[]; cursor?: string; maximumRecords?: number; reason: SourceFetchReason };
export type ExternalSourceRecord = { providerKey: string; externalRecordId: string; externalType: string; observedAt: string; endedAt?: string; rawFields: Record<string, unknown>; importedAt: string };
export type SourceFetchResult = { records: ExternalSourceRecord[]; nextCursor?: string; fetchedAt: string };
export type ExternalParameterMapping = { id: string; providerKey: string; externalField: string; externalType?: string; parameterId: string; transformation: { type: 'identity' } | { type: 'unit_conversion'; fromUnit: string; toUnit: string } | { type: 'enum_mapping'; values: Record<string, string> } | { type: 'duration_between'; startField: string; endField: string } | { type: 'count_records' } | { type: 'custom_transform'; transformId: string }; certainty: 'high' | 'medium' | 'low'; transformationVersion: string; isActive: boolean };
export type SourceAdapter = { providerKey: SourceProviderKey; capabilities: readonly SourceCapability[]; getPermissionStatus(): Promise<SourcePermissionStatus>; requestPermission?(): Promise<SourcePermissionStatus>; listSupportedParameterMappings(): Promise<ExternalParameterMapping[]>; fetch(input: SourceFetchInput): Promise<SourceFetchResult> };
export function validateSourceFetchInput(input: SourceFetchInput) { if (!input.userId || !input.startAt || !input.endAt || new Date(input.startAt) >= new Date(input.endAt)) throw new Error('invalid_fetch_period'); if (!input.requestedParameterIds.length) throw new Error('no_parameters_requested'); if (input.maximumRecords !== undefined && (!Number.isInteger(input.maximumRecords) || input.maximumRecords <= 0)) throw new Error('invalid_maximum_records'); }
export class SourceProviderRegistry { private readonly adapters = new Map<string, SourceAdapter>(); register(adapter: SourceAdapter) { if (this.adapters.has(adapter.providerKey)) throw new Error('provider_already_registered'); this.adapters.set(adapter.providerKey, adapter); } get(providerKey: string) { const adapter = this.adapters.get(providerKey); if (!adapter) throw new Error('provider_unavailable'); return adapter; } list() { return [...this.adapters.values()]; } }
export class SystemClockAdapter implements SourceAdapter { readonly providerKey = 'system_clock' as const; readonly capabilities = ['read_current_state', 'read_events'] as const; async getPermissionStatus() { return 'not_required' as const; } async listSupportedParameterMappings() { return ['observed_at', 'time_period', 'day_of_week', 'day_type'].map((parameterId) => ({ id: `system_clock_${parameterId}`, providerKey: this.providerKey, externalField: parameterId, parameterId, transformation: { type: 'identity' as const }, certainty: 'high' as const, transformationVersion: 'clock-v1', isActive: true })); } async fetch(input: SourceFetchInput) { validateSourceFetchInput(input); const date = new Date(input.endAt); const hour = date.getHours(); const timePeriod = hour < 6 ? 'night' : hour < 12 ? 'morning' : hour < 18 ? 'daytime' : 'evening'; const day = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'][date.getDay()]; const dayType = date.getDay() === 0 || date.getDay() === 6 ? 'weekend' : 'weekday'; return { fetchedAt: new Date().toISOString(), records: [{ providerKey: this.providerKey, externalRecordId: `clock_${date.toISOString()}`, externalType: 'clock_snapshot', observedAt: date.toISOString(), rawFields: { observed_at: date.toISOString(), time_period: timePeriod, day_of_week: day, day_type: dayType }, importedAt: new Date().toISOString() }] }; } }
export class TestFixtureAdapter implements SourceAdapter { readonly providerKey = 'test_fixture' as const; readonly capabilities = ['read_events', 'read_samples', 'read_daily_summary'] as const; private readonly records: ExternalSourceRecord[]; constructor(records: ExternalSourceRecord[] = []) { this.records = records; } async getPermissionStatus() { return 'granted' as const; } async listSupportedParameterMappings() { return []; } async fetch(input: SourceFetchInput) { validateSourceFetchInput(input); return { fetchedAt: new Date().toISOString(), records: this.records.filter((record) => new Date(record.observedAt) >= new Date(input.startAt) && new Date(record.observedAt) <= new Date(input.endAt)).slice(0, input.maximumRecords ?? 1000) }; } }
export class ManualImportAdapter implements SourceAdapter { readonly providerKey = 'manual_import' as const; readonly capabilities = ['read_events', 'read_samples'] as const; private readonly inputRecords: ExternalSourceRecord[]; constructor(inputRecords: ExternalSourceRecord[] = []) { this.inputRecords = inputRecords; } async getPermissionStatus() { return 'granted' as const; } async listSupportedParameterMappings() { return []; } async fetch(input: SourceFetchInput) { validateSourceFetchInput(input); return { fetchedAt: new Date().toISOString(), records: this.inputRecords.filter((record) => new Date(record.observedAt) >= new Date(input.startAt) && new Date(record.observedAt) <= new Date(input.endAt)).slice(0, input.maximumRecords ?? 1000) }; } static parseJson(raw: string) { const parsed: unknown = JSON.parse(raw); if (!Array.isArray(parsed)) throw new Error('manual_import_requires_array'); return parsed as ExternalSourceRecord[]; } }
