export type SyntheticScenarioId = 'clear_positive_effect' | 'clear_negative_effect' | 'no_effect' | 'high_missingness' | 'unbalanced_cohorts' | 'effect_reversal' | 'temporary_effect' | 'belief_match' | 'belief_mismatch';
export type SyntheticExpectation = { candidateExpected: boolean; expectedRelation?: 'a_greater_than_b' | 'a_less_than_b'; expectedStability?: 'stable' | 'unstable' | 'insufficient'; maximumCandidateScore?: number; minimumMissingRate?: number };
export type SyntheticObservation = { episodeId: string; parameterId: string; value: unknown; isMissing: boolean; observedAt: string };
export type SyntheticDataset = { observations: SyntheticObservation[]; conditionParameterId: string; outcomeParameterId: string; expectedDirection: 'a_greater_than_b' | 'a_less_than_b'; seed: number; scenario?: SyntheticScenarioId; expectation?: SyntheticExpectation };
export const SYNTHETIC_SCENARIOS: Record<SyntheticScenarioId, SyntheticExpectation> = { clear_positive_effect: { candidateExpected: true, expectedRelation: 'a_greater_than_b', expectedStability: 'stable' }, clear_negative_effect: { candidateExpected: true, expectedRelation: 'a_less_than_b', expectedStability: 'stable' }, no_effect: { candidateExpected: false, maximumCandidateScore: 0.5 }, high_missingness: { candidateExpected: false, minimumMissingRate: 0.5 }, unbalanced_cohorts: { candidateExpected: false }, effect_reversal: { candidateExpected: true, expectedStability: 'unstable' }, temporary_effect: { candidateExpected: true, expectedStability: 'unstable' }, belief_match: { candidateExpected: true, expectedRelation: 'a_greater_than_b' }, belief_mismatch: { candidateExpected: true, expectedRelation: 'a_less_than_b' } };
export function generateSyntheticDataset(input: { count?: number; seed?: number; startAt?: string; effect?: number; scenario?: SyntheticScenarioId }): SyntheticDataset {
  const count = input.count ?? 100; const seed = input.seed ?? 42; const scenario = input.scenario ?? 'clear_positive_effect'; const baseEffect = input.effect ?? (scenario === 'clear_negative_effect' || scenario === 'belief_mismatch' ? -1.5 : scenario === 'no_effect' ? 0 : 1.5); let state = seed >>> 0; const random = () => { state = (state * 1664525 + 1013904223) >>> 0; return state / 4294967296; }; const start = new Date(input.startAt ?? '2026-01-01T00:00:00.000Z'); const observations: SyntheticObservation[] = [];
  for (let index = 0; index < count; index += 1) { const episodeId = `synthetic_${seed}_${index}`; const high = scenario === 'unbalanced_cohorts' ? index < Math.max(2, Math.floor(count * 0.9)) : index % 2 === 0; const phase = index / Math.max(count - 1, 1); const effect = scenario === 'effect_reversal' ? (phase < 0.5 ? 1.5 : -1.5) : scenario === 'temporary_effect' ? (phase < 0.25 ? 1.5 : 0) : baseEffect; const noise = (random() - 0.5) * 0.6; const outcome = Math.max(1, Math.min(5, 3 + (high ? effect / 2 : -effect / 2) + noise)); const observedAt = new Date(start.getTime() + index * 86400000).toISOString(); const conditionMissing = scenario === 'high_missingness' && random() < 0.3; const outcomeMissing = scenario === 'high_missingness' ? random() < 0.5 : index % 37 === 0; observations.push({ episodeId, parameterId: 'condition', value: high, isMissing: conditionMissing, observedAt }, { episodeId, parameterId: 'outcome', value: outcome, isMissing: outcomeMissing, observedAt }); }
  return { observations, conditionParameterId: 'condition', outcomeParameterId: 'outcome', expectedDirection: baseEffect >= 0 ? 'a_greater_than_b' : 'a_less_than_b', seed, scenario, expectation: SYNTHETIC_SCENARIOS[scenario] };
}
