import { dbPromise, newId } from '../db';
import { resolveCheckinTiming } from '../checkinTiming';
export type CheckinKind = 'random' | 'hypothesis' | 'follow_up' | 'manual_demo';
export type CreateCheckinInput = { kind: CheckinKind; hypothesisId?: string | null; scheduledAt?: string; expiresAt?: string };
export async function createCheckin(input: CreateCheckinInput) { const db = await dbPromise; const id = newId('checkin'); const timing = resolveCheckinTiming(input.scheduledAt, input.expiresAt); const question = { title: 'Record the current activity', fields: ['activity_type', 'started', 'completed', 'energy'], policyVersion: 'mobile-v1' }; await db.runAsync('INSERT INTO checkins (id, hypothesis_id, kind, question_json, scheduled_at, expires_at, response_status, policy_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', id, input.hypothesisId ?? null, input.kind, JSON.stringify(question), timing.scheduledAt, timing.expiresAt, 'pending', 'mobile-v1'); return { id, hypothesisId: input.hypothesisId ?? null, kind: input.kind, ...timing, ...question }; }
export async function setCheckinStatus(id: string, status: 'answered' | 'skipped' | 'expired' | 'cancelled', missingReason?: string) { const db = await dbPromise; await db.withTransactionAsync(async () => { await db.runAsync('UPDATE checkins SET response_status = ?, missing_reason = ? WHERE id = ? AND response_status = ?', status, missingReason ?? null, id, 'pending'); await db.runAsync('UPDATE notification_schedules SET status = ? WHERE checkin_id = ? AND status = ?', status, id, 'scheduled'); }); }
export async function pendingCheckin(id: string) { const db = await dbPromise; const row = await db.getFirstAsync<{ id: string; hypothesis_id: string | null; kind: CheckinKind; scheduled_at: string; expires_at: string; response_status: string }>('SELECT * FROM checkins WHERE id = ?', id); if (row && row.response_status === 'pending' && new Date(row.expires_at) <= new Date()) { await setCheckinStatus(id, 'expired', 'expired'); return { ...row, response_status: 'expired' }; } return row; }
export async function checkinHypothesisId(id: string) { const db = await dbPromise; const row = await db.getFirstAsync<{ hypothesis_id: string | null }>('SELECT hypothesis_id FROM checkins WHERE id = ?', id); return row?.hypothesis_id ?? null; }
export async function recentCheckins() { const db = await dbPromise; return db.getAllAsync<{ id: string; hypothesis_id: string | null; scheduled_at: string; kind: CheckinKind; response_status: string }>('SELECT id, hypothesis_id, scheduled_at, kind, response_status FROM checkins ORDER BY scheduled_at DESC LIMIT 50'); }
export async function expireOverdueCheckins() { const db = await dbPromise; await db.runAsync("UPDATE checkins SET response_status = 'expired', missing_reason = 'expired' WHERE response_status = 'pending' AND expires_at < ?", new Date().toISOString()); await db.runAsync("UPDATE notification_schedules SET status = 'expired' WHERE status = 'scheduled' AND expires_at < ?", new Date().toISOString()); }
export async function missingCheckinCount(hypothesisId: string) { const db = await dbPromise; const row = await db.getFirstAsync<{ count: number }>("SELECT COUNT(*) AS count FROM checkins WHERE hypothesis_id = ? AND response_status IN ('skipped', 'expired')", hypothesisId); return row?.count ?? 0; }
