import { dbPromise, newId } from '../db';
export type CheckinKind = 'random' | 'hypothesis' | 'follow_up' | 'manual_demo';
export async function createCheckin(kind: CheckinKind = 'manual_demo', hypothesisId?: string | null) { const db = await dbPromise; const id = newId('checkin'); const scheduledAt = new Date().toISOString(); const expiresAt = new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(); const question = { title: '今の活動を記録する', fields: ['activity_type', 'started', 'completed', 'energy'], policyVersion: 'mobile-v1' }; await db.runAsync('INSERT INTO checkins (id, hypothesis_id, kind, question_json, scheduled_at, expires_at, response_status, policy_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', id, hypothesisId ?? null, kind, JSON.stringify(question), scheduledAt, expiresAt, 'pending', 'mobile-v1'); return { id, hypothesisId: hypothesisId ?? null, kind, scheduledAt, expiresAt, ...question }; }
export async function setCheckinStatus(id: string, status: 'answered' | 'skipped' | 'expired', missingReason?: string) { const db = await dbPromise; await db.runAsync('UPDATE checkins SET response_status = ?, missing_reason = ? WHERE id = ?', status, missingReason ?? null, id); }
export async function pendingCheckin(id: string) { const db = await dbPromise; return db.getFirstAsync<{ id: string; hypothesis_id: string | null; kind: CheckinKind; scheduled_at: string; expires_at: string; response_status: string }>('SELECT * FROM checkins WHERE id = ?', id); }
export async function checkinHypothesisId(id: string) { const db = await dbPromise; const row = await db.getFirstAsync<{ hypothesis_id: string | null }>('SELECT hypothesis_id FROM checkins WHERE id = ?', id); return row?.hypothesis_id ?? null; }
export async function recentCheckins() { const db = await dbPromise; return db.getAllAsync<{ id: string; hypothesis_id: string | null; scheduled_at: string; kind: CheckinKind; response_status: string }>('SELECT id, hypothesis_id, scheduled_at, kind, response_status FROM checkins ORDER BY scheduled_at DESC LIMIT 50'); }
export async function expireOverdueCheckins() { const db = await dbPromise; await db.runAsync("UPDATE checkins SET response_status = 'expired', missing_reason = 'expired' WHERE response_status = 'pending' AND expires_at < ?", new Date().toISOString()); }
export async function missingCheckinCount(hypothesisId: string) { const db = await dbPromise; const row = await db.getFirstAsync<{ count: number }>("SELECT COUNT(*) AS count FROM checkins WHERE hypothesis_id = ? AND response_status IN ('skipped', 'expired')", hypothesisId); return row?.count ?? 0; }
