import { buildDataCollectionPlan, createExperimentDraftFromCandidate, EVIDENCE_POLICY, evaluateExperiment, transitionExperiment, type CandidateForExperiment, type DataCollectionPlan, type ExperimentDraft, type ExperimentEvaluation, type ExperimentObservation, type ExperimentStatus } from "../../domain";
import { dbPromise, newId } from "../db";

type Row = Record<string, unknown>;
const parse = <T>(value: unknown, fallback: T): T => { try { return JSON.parse(String(value)) as T; } catch { return fallback; } };
function draftFromRow(row: Row): ExperimentDraft { const draft = parse<ExperimentDraft | null>(row.draft_json, null); if (!draft) throw new Error("experiment_draft_corrupt"); return { ...draft, id: String(row.id), status: String(row.status) as ExperimentDraft["status"] }; }
function candidateFromRow(row: Row): CandidateForExperiment { return { id: String(row.id), conditionParameterId: String(row.condition_parameter_id), outcomeParameterId: String(row.outcome_parameter_id), conditionLabel: String(row.condition_name_ja ?? row.condition_parameter_id), outcomeLabel: String(row.outcome_name_ja ?? row.outcome_parameter_id), cohortAKey: String(row.cohort_a_key), cohortBKey: String(row.cohort_b_key), effectValue: Number(row.effect_value), sampleCount: Number(row.cohort_a_sample_count ?? 0) + Number(row.cohort_b_sample_count ?? 0), minimumPerGroup: 3 }; }

export async function createExperimentDraftFromCandidateForUser(input: { userId: string; candidateId: string; now?: string }) {
  const db = await dbPromise;
  const row = await db.getFirstAsync<Row>("SELECT hc.*,cp.name_ja AS condition_name_ja,op.name_ja AS outcome_name_ja FROM hypothesis_candidates hc JOIN parameter_definitions cp ON cp.id=hc.condition_parameter_id JOIN parameter_definitions op ON op.id=hc.outcome_parameter_id WHERE hc.user_id=? AND hc.id=? AND hc.status IN('discovered','presented')", input.userId, input.candidateId);
  if (!row) throw new Error("candidate_not_available");
  const draft = createExperimentDraftFromCandidate({ id: newId("experiment_draft"), candidate: candidateFromRow(row), now: input.now });
  const timestamp = input.now ?? new Date().toISOString();
  await db.runAsync("INSERT INTO experiment_drafts(id,user_id,source_candidate_id,draft_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)", draft.id, input.userId, input.candidateId, JSON.stringify(draft), draft.status, timestamp, timestamp);
  return draft;
}
export async function listExperimentDrafts(input: { userId: string; status?: string }) { const db = await dbPromise; const rows = input.status ? await db.getAllAsync<Row>("SELECT * FROM experiment_drafts WHERE user_id=? AND status=? ORDER BY updated_at DESC", input.userId, input.status) : await db.getAllAsync<Row>("SELECT * FROM experiment_drafts WHERE user_id=? ORDER BY updated_at DESC", input.userId); return rows.map(draftFromRow); }
export async function getExperimentDraft(input: { userId: string; draftId: string }) { const row = await (await dbPromise).getFirstAsync<Row>("SELECT * FROM experiment_drafts WHERE user_id=? AND id=?", input.userId, input.draftId); return row ? draftFromRow(row) : null; }
export async function updateExperimentDraft(input: { userId: string; draftId: string; patch: Partial<Pick<ExperimentDraft, "title" | "statement" | "durationDays" | "minimumObservations" | "minimumPerGroup" | "suggestedSchedule" | "stopConditions">> }) { const current = await getExperimentDraft(input); if (!current || current.status !== "draft") throw new Error("experiment_draft_not_editable"); const next = { ...current, ...input.patch }; if (!next.title.trim() || !next.statement.trim() || !Number.isInteger(next.durationDays) || next.durationDays < 1 || next.durationDays > 90 || !Number.isInteger(next.minimumPerGroup) || next.minimumPerGroup < EVIDENCE_POLICY.minimumSamplesPerCohort || next.minimumPerGroup > 1000 || !Number.isInteger(next.minimumObservations) || next.minimumObservations < Math.max(EVIDENCE_POLICY.minimumTotalSamples, next.minimumPerGroup * 2) || next.minimumObservations > 5000) throw new Error("experiment_draft_invalid"); await (await dbPromise).runAsync("UPDATE experiment_drafts SET draft_json=?,updated_at=? WHERE user_id=? AND id=? AND status='draft'", JSON.stringify(next), new Date().toISOString(), input.userId, input.draftId); return next; }
export async function rejectExperimentDraft(input: { userId: string; draftId: string }) { const draft = await getExperimentDraft(input); if (!draft || draft.status !== "draft") throw new Error("experiment_draft_not_available"); await (await dbPromise).runAsync("UPDATE experiment_drafts SET status='rejected',updated_at=? WHERE user_id=? AND id=? AND status='draft'", new Date().toISOString(), input.userId, input.draftId); }

export async function acceptExperimentDraft(input: { userId: string; draftId: string; hypothesisId?: string | null }) {
  const draft = await getExperimentDraft(input); if (!draft || draft.status !== "draft") throw new Error("experiment_draft_not_available");
  const db = await dbPromise; const timestamp = new Date().toISOString(); const id = newId("experiment");
  await db.withTransactionAsync(async () => {
    await db.runAsync("UPDATE experiment_drafts SET status='accepted',updated_at=? WHERE user_id=? AND id=? AND status='draft'", timestamp, input.userId, input.draftId);
    await db.runAsync("INSERT INTO experiments(id,user_id,draft_id,source_candidate_id,title,statement,kind,comparison_type,status,started_at,ended_at,duration_days,minimum_observations,minimum_per_group,schedule_json,stop_conditions_json,safety_notes_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", id, input.userId, input.draftId, draft.sourceCandidateId, draft.title, draft.statement, draft.kind, draft.comparisonType, "ready", null, null, draft.durationDays, draft.minimumObservations, draft.minimumPerGroup, JSON.stringify(draft.suggestedSchedule), JSON.stringify(draft.stopConditions), JSON.stringify(draft.safetyNotes), timestamp);
    for (const parameterId of draft.conditionParameters) await db.runAsync("INSERT INTO experiment_conditions(experiment_id,parameter_id,role,config_json) VALUES(?,?,?,?)", id, parameterId, "condition", JSON.stringify({ groupA: draft.groupAKey, groupB: draft.groupBKey }));
    await db.runAsync("INSERT INTO experiment_conditions(experiment_id,parameter_id,role,config_json) VALUES(?,?,?,?)", id, draft.targetOutcomeParameter, "outcome", "{}");
    for (const parameterId of draft.requiredParameters) await db.runAsync("INSERT INTO experiment_required_parameters(experiment_id,parameter_id,minimum_samples,askable,priority) VALUES(?,?,?,?,?)", id, parameterId, draft.minimumPerGroup, 1, parameterId === draft.targetOutcomeParameter ? 0 : 100);
    await db.runAsync("INSERT INTO experiment_schedules(experiment_id,schedule_json,enabled,updated_at) VALUES(?,?,?,?)", id, JSON.stringify(draft.suggestedSchedule), 1, timestamp);
    for (const stop of draft.stopConditions) await db.runAsync("INSERT INTO experiment_stop_conditions(id,experiment_id,kind,description,threshold) VALUES(?,?,?,?,?)", newId("stop"), id, stop.kind, stop.description, stop.threshold ?? null);
    if (input.hypothesisId) await db.runAsync("INSERT INTO experiment_hypothesis_links(experiment_id,hypothesis_id,relation,created_at) VALUES(?,?,?,?)", id, input.hypothesisId, "source", timestamp);
  });
  return getExperiment({ userId: input.userId, experimentId: id });
}

function experimentFromRow(row: Row) { return { id: String(row.id), userId: String(row.user_id), draftId: String(row.draft_id), sourceCandidateId: String(row.source_candidate_id), title: String(row.title), statement: String(row.statement), kind: String(row.kind), comparisonType: String(row.comparison_type), status: String(row.status) as ExperimentStatus, startedAt: typeof row.started_at === "string" ? row.started_at : null, endedAt: typeof row.ended_at === "string" ? row.ended_at : null, durationDays: Number(row.duration_days), minimumObservations: Number(row.minimum_observations), minimumPerGroup: Number(row.minimum_per_group), schedule: parse(row.schedule_json, {}), stopConditions: parse(row.stop_conditions_json, []), safetyNotes: parse(row.safety_notes_json, []), createdAt: String(row.created_at) }; }
export async function listExperiments(input: { userId: string; status?: string }) { const db = await dbPromise; const rows = input.status ? await db.getAllAsync<Row>("SELECT * FROM experiments WHERE user_id=? AND status=? ORDER BY created_at DESC", input.userId, input.status) : await db.getAllAsync<Row>("SELECT * FROM experiments WHERE user_id=? ORDER BY created_at DESC", input.userId); return rows.map(experimentFromRow); }
export async function getExperiment(input: { userId: string; experimentId: string }) { const row = await (await dbPromise).getFirstAsync<Row>("SELECT * FROM experiments WHERE user_id=? AND id=?", input.userId, input.experimentId); return row ? experimentFromRow(row) : null; }
export async function transitionExperimentForUser(input: { userId: string; experimentId: string; status: ExperimentStatus }) { const current = await getExperiment(input); if (!current) throw new Error("experiment_not_found"); const next = transitionExperiment(current.status, input.status); const timestamp = new Date().toISOString(); await (await dbPromise).runAsync("UPDATE experiments SET status=?,started_at=CASE WHEN ?='active' AND started_at IS NULL THEN ? ELSE started_at END,ended_at=CASE WHEN ? IN('completed','cancelled','archived','invalid') THEN ? ELSE ended_at END WHERE user_id=? AND id=?", next, next, timestamp, next, timestamp, input.userId, input.experimentId); return getExperiment(input); }

export async function addExperimentObservation(input: { userId: string; experimentId: string; observation: Omit<ExperimentObservation, "experimentId"> }) { const experiment = await getExperiment(input); if (!experiment || !["active", "paused"].includes(experiment.status)) throw new Error("experiment_not_active"); await (await dbPromise).runAsync("INSERT OR IGNORE INTO experiment_observations(id,experiment_id,episode_id,observed_at,group_key,outcome,condition_values_json,source,eligible,note,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)", input.observation.id, input.experimentId, input.observation.episodeId ?? null, input.observation.observedAt, input.observation.groupKey, input.observation.outcome, JSON.stringify(input.observation.conditionValues ?? {}), input.observation.source, input.observation.eligible ? 1 : 0, input.observation.note ?? null, new Date().toISOString()); return { ...input.observation, experimentId: input.experimentId }; }
 export async function evaluateExperimentForUser(input: { userId: string; experimentId: string; evaluatedAt?: string }): Promise<ExperimentEvaluation> { const experiment = await getExperiment(input); if (!experiment || experiment.status !== "completed") throw new Error("experiment_must_be_completed"); const draft = await getExperimentDraft({ userId: input.userId, draftId: String(experiment.draftId) }); if (!draft) throw new Error("experiment_draft_not_found"); const db = await dbPromise; const rows = await db.getAllAsync<Row>("SELECT * FROM experiment_observations WHERE experiment_id=? ORDER BY observed_at,id", input.experimentId); const observations = rows.map((row) => ({ id: String(row.id), experimentId: input.experimentId, episodeId: typeof row.episode_id === "string" ? row.episode_id : undefined, observedAt: String(row.observed_at), groupKey: String(row.group_key), outcome: Number(row.outcome), conditionValues: parse(row.condition_values_json, {}), source: String(row.source) as ExperimentObservation["source"], eligible: Number(row.eligible) === 1, note: typeof row.note === "string" ? row.note : undefined })); const evaluation = evaluateExperiment({ experimentId: input.experimentId, observations, groupAKey: draft.groupAKey, groupBKey: draft.groupBKey, minimumPerGroup: experiment.minimumPerGroup, minimumObservations: experiment.minimumObservations, expectedDirection: draft.expectedDirection, minimumEffect: draft.minimumEffect, kind: experiment.kind as "condition_comparison" | "behavioral_intervention" | "observation_only", evaluatedAt: input.evaluatedAt, outcomeScale: draft.outcomeDefinition?.minimum !== undefined && draft.outcomeDefinition.maximum !== undefined ? { minimumValue: draft.outcomeDefinition.minimum, maximumValue: draft.outcomeDefinition.maximum } : undefined }); const nextStatus: ExperimentStatus = evaluation.status === "insufficient_data" ? "insufficient_data" : "evaluated"; transitionExperiment(experiment.status, nextStatus); await db.withTransactionAsync(async () => { await db.runAsync("INSERT INTO experiment_evaluations(id,experiment_id,evaluation_json,status,evaluated_at) VALUES(?,?,?,?,?)", newId("experiment_evaluation"), input.experimentId, JSON.stringify(evaluation), evaluation.status, evaluation.evaluatedAt); await db.runAsync("UPDATE experiments SET status=?,ended_at=COALESCE(ended_at,?) WHERE user_id=? AND id=?", nextStatus, evaluation.evaluatedAt, input.userId, input.experimentId); }); return evaluation; }
export async function latestExperimentEvaluation(input: { userId: string; experimentId: string }) { if (!(await getExperiment(input))) throw new Error("experiment_not_found"); const row = await (await dbPromise).getFirstAsync<Row>("SELECT evaluation_json FROM experiment_evaluations WHERE experiment_id=? ORDER BY evaluated_at DESC LIMIT 1", input.experimentId); return row ? parse<ExperimentEvaluation | null>(row.evaluation_json, null) : null; }
export async function experimentQuestions(input: { userId: string; experimentId: string }) { if (!(await getExperiment(input))) throw new Error("experiment_not_found"); const rows = await (await dbPromise).getAllAsync<Row>("SELECT rp.parameter_id,pd.name_ja,rp.minimum_samples,rp.askable FROM experiment_required_parameters rp JOIN parameter_definitions pd ON pd.id=rp.parameter_id WHERE rp.experiment_id=? ORDER BY rp.priority", input.experimentId); return rows.map((row) => ({ parameterId: String(row.parameter_id), text: "現在の「" + String(row.name_ja) + "」を記録してください。", minimumSamples: Number(row.minimum_samples), askable: Number(row.askable) === 1, reason: "この実験に必要な観測項目です" })); }
export async function createExperimentCollectionPlan(input: { userId: string; experimentId: string }): Promise<DataCollectionPlan> { const experiment = await getExperiment(input); if (!experiment) throw new Error("experiment_not_found"); const db = await dbPromise; const requirements = await db.getAllAsync<Row>("SELECT rp.parameter_id,pd.name_ja,rp.minimum_samples,rp.askable FROM experiment_required_parameters rp JOIN parameter_definitions pd ON pd.id=rp.parameter_id WHERE rp.experiment_id=?", input.experimentId); const counts: Record<string, number> = {}; for (const row of requirements) { const count = await db.getFirstAsync<{ count: number }>("SELECT COUNT(*) AS count FROM parameter_values pv JOIN observation_episodes oe ON oe.id=pv.episode_id WHERE oe.user_id=? AND oe.experiment_id=? AND pv.parameter_id=? AND pv.is_missing=0", input.userId, input.experimentId, String(row.parameter_id)); counts[String(row.parameter_id)] = Number(count?.count ?? 0); } const plan = buildDataCollectionPlan({ id: newId("collection_plan"), sourceAnalysisId: input.experimentId, targetConstruct: "experiment", requirements: requirements.map((row) => ({ parameterId: String(row.parameter_id), label: String(row.name_ja), minimumSamples: Number(row.minimum_samples), askable: Number(row.askable) === 1, preferredSource: "user" as const })), counts, includePcsTemplateRequest: true }); const timestamp = new Date().toISOString(); await db.runAsync("INSERT INTO data_collection_plans(id,user_id,source_analysis_id,target_construct,plan_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)", plan.id, input.userId, plan.sourceAnalysisId, plan.targetConstruct, JSON.stringify(plan), plan.status, timestamp, timestamp); for (const shortage of plan.shortages) await db.runAsync("INSERT INTO data_collection_shortages(plan_id,parameter_id,needed,reason) VALUES(?,?,?,?)", plan.id, shortage.key, shortage.needed, shortage.reason); return plan; }
