import type { HypothesisSpec } from '../../domain';
import { dbPromise, newId } from '../db';

export function timeOfDaySpec(): HypothesisSpec { return { schemaVersion: '1', unit: 'response', scope: [{ field: 'time_period', operator: 'in', value: ['day', 'night'] }], cohorts: [{ key: 'day', conditions: [{ field: 'time_period', operator: 'equals', value: 'day' }] }, { key: 'night', conditions: [{ field: 'time_period', operator: 'equals', value: 'night' }] }], outcome: { field: 'completed', metric: 'binary_rate_difference', positiveValues: [true] }, expectation: { relation: 'cohort_a_less_than_b', minimumEffect: 0.2 }, evaluationPolicy: { captureModes: ['momentary_observation'], acceptedSources: ['user_confirmed', 'system'], minimumSamplesPerCohort: 3, maximumCohortRatio: 2, windowDays: 30, excludeLowCertainty: true, maximumMissingRate: 0.2 } }; }

export async function saveHypothesis(selfBeliefId: string, belief: string, spec: HypothesisSpec) { const db = await dbPromise; const id = newId('hyp'); const statement = '昼と夜で活動開始率または活動完了率に差がある'; await db.runAsync('INSERT INTO hypotheses (id, self_belief_id, template_key, statement, state, spec_json, spec_version, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', id, selfBeliefId, 'time_of_day_productivity', statement, 'tracking', JSON.stringify(spec), spec.schemaVersion, new Date().toISOString()); return { id, statement, spec }; }
export async function trackingHypothesis() { const db = await dbPromise; return db.getFirstAsync<{ id: string; self_belief_id: string; statement: string; state: string; spec_json: string; spec_version: string }>("SELECT * FROM hypotheses WHERE state = 'tracking' ORDER BY created_at DESC LIMIT 1"); }
export async function latestHypothesis() { const db = await dbPromise; return db.getFirstAsync<{ id: string; self_belief_id: string; statement: string; state: string; spec_json: string; spec_version: string }>('SELECT * FROM hypotheses ORDER BY created_at DESC LIMIT 1'); }
export async function hypothesisById(id: string) { const db = await dbPromise; return db.getFirstAsync<{ id: string; self_belief_id: string; statement: string; state: string; spec_json: string; spec_version: string }>('SELECT * FROM hypotheses WHERE id = ?', id); }
