import type { HypothesisSpec } from '../../domain';
import { templateByKey } from '@/features/hypothesisTemplates';
import { dbPromise, newId } from '../db';

export function timeOfDaySpec(): HypothesisSpec { return templateByKey('night_completion').spec; }

export async function saveHypothesis(selfBeliefId: string, templateKey: string) { const db = await dbPromise; const id = newId('hyp'); const template = templateByKey(templateKey); const createdAt = new Date().toISOString(); await db.runAsync('INSERT INTO hypotheses (id, self_belief_id, template_key, statement, state, spec_json, spec_version, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', id, selfBeliefId, template.key, template.hypothesisStatement, 'tracking', JSON.stringify(template.spec), template.spec.schemaVersion, createdAt); const parameterId = (field: string) => field === 'completed' ? 'completion_status' : field; const requiredFields = [...template.spec.scope.map((condition) => condition.field), ...template.spec.cohorts.flatMap((cohort) => cohort.conditions.map((condition) => condition.field)), template.spec.outcome.field]; for (const [index, field] of [...new Set(requiredFields)].entries()) { const parameter = await db.getFirstAsync<{ id: string }>('SELECT id FROM parameter_definitions WHERE id=?', parameterId(field)); if (!parameter) continue; const role = field === template.spec.outcome.field ? 'outcome' : 'cohort'; await db.runAsync('INSERT OR IGNORE INTO hypothesis_parameter_requirements (hypothesis_id,parameter_id,requirement_role,required,minimum_samples,priority,created_at) VALUES (?,?,?,?,?,?,?)', id, parameter.id, role, 1, template.spec.evaluationPolicy.minimumSamplesPerCohort, index * 10, createdAt); } return { id, statement: template.hypothesisStatement, spec: template.spec }; }
export async function trackingHypothesis() { const db = await dbPromise; return db.getFirstAsync<{ id: string; self_belief_id: string; template_key: string; statement: string; state: string; spec_json: string; spec_version: string }>("SELECT * FROM hypotheses WHERE state = 'tracking' ORDER BY created_at DESC LIMIT 1"); }
export async function latestHypothesis() { const db = await dbPromise; return db.getFirstAsync<{ id: string; self_belief_id: string; template_key: string; statement: string; state: string; spec_json: string; spec_version: string }>('SELECT * FROM hypotheses ORDER BY created_at DESC LIMIT 1'); }
export async function hypothesisById(id: string) { const db = await dbPromise; return db.getFirstAsync<{ id: string; self_belief_id: string; template_key: string; statement: string; state: string; spec_json: string; spec_version: string }>('SELECT * FROM hypotheses WHERE id = ?', id); }
