import type * as SQLite from 'expo-sqlite';
import { dbPromise, newId } from '../db';
import { fallbackQuestionText, validateParameterValue, type AllowedValue, type ParameterDefinition, type ParameterValueInput, type ParameterSourceType, type Certainty } from '../../domain/parameters';

type Row = Record<string, unknown>;
const parse = (value: unknown, fallback: unknown) => { try { return JSON.parse(String(value)); } catch { return fallback; } };
async function definition(db: SQLite.SQLiteDatabase, id: string) { return db.getFirstAsync<ParameterDefinition>('SELECT * FROM parameter_definitions WHERE id = ?', id); }
async function allowed(db: SQLite.SQLiteDatabase, id: string) { return db.getAllAsync<AllowedValue>('SELECT * FROM parameter_allowed_values WHERE parameter_id = ? AND is_active = 1 ORDER BY sort_order', id); }

export async function getParameterDefinition(parameterId: string) { return definition(await dbPromise, parameterId); }
export async function listParameterDefinitions(filter: { layer?: string; activeOnly?: boolean; askableOnly?: boolean } = {}) {
  const clauses: string[] = []; const args: (string | number)[] = [];
  if (filter.layer) { clauses.push('parameter_layer = ?'); args.push(filter.layer); } if (filter.activeOnly !== false) clauses.push('is_active = 1'); if (filter.askableOnly) clauses.push('askable = 1');
  return (await dbPromise).getAllAsync<ParameterDefinition>(`SELECT * FROM parameter_definitions ${clauses.length ? `WHERE ${clauses.join(' AND ')}` : ''} ORDER BY parameter_layer,id`, ...args);
}
export async function listAllowedValues(parameterId: string) { return allowed(await dbPromise, parameterId); }
export async function getParameterGovernance(parameterId: string) { return (await dbPromise).getFirstAsync<Row>('SELECT * FROM parameter_governance WHERE parameter_id=?', parameterId); }
export async function searchParameterDefinitions(input: { query?: string; domain?: string; status?: string; activeOnly?: boolean }) { const clauses: string[] = []; const args: (string | number)[] = []; if (input.query) { clauses.push('(pd.id LIKE ? OR pd.name_ja LIKE ? OR pg.aliases_ja_json LIKE ?)'); const query = `%${input.query}%`; args.push(query, query, query); } if (input.domain) { clauses.push('pg.domain=?'); args.push(input.domain); } if (input.status) { clauses.push('pg.status=?'); args.push(input.status); } if (input.activeOnly !== false) clauses.push('pd.is_active=1'); return (await dbPromise).getAllAsync<Row>(`SELECT pd.*,pg.domain,pg.aliases_ja_json,pg.status,pg.governance_version FROM parameter_definitions pd LEFT JOIN parameter_governance pg ON pg.parameter_id=pd.id ${clauses.length ? `WHERE ${clauses.join(' AND ')}` : ''} ORDER BY pd.name_ja`, ...args); }
export async function setParameterGovernance(input: { parameterId: string; domain: string; aliasesJa?: string[]; status: string; replacedByParameterId?: string; comparableParameterIds?: string[]; conflictingParameterIds?: string[]; minimumObservationIntervalMinutes?: number }) { const db = await dbPromise; await db.runAsync('INSERT INTO parameter_governance (parameter_id,domain,aliases_ja_json,status,replaced_by_parameter_id,comparable_parameter_ids_json,conflicting_parameter_ids_json,minimum_observation_interval_minutes,governance_version,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(parameter_id) DO UPDATE SET domain=excluded.domain,aliases_ja_json=excluded.aliases_ja_json,status=excluded.status,replaced_by_parameter_id=excluded.replaced_by_parameter_id,comparable_parameter_ids_json=excluded.comparable_parameter_ids_json,conflicting_parameter_ids_json=excluded.conflicting_parameter_ids_json,minimum_observation_interval_minutes=excluded.minimum_observation_interval_minutes,governance_version=excluded.governance_version,updated_at=excluded.updated_at', input.parameterId, input.domain, JSON.stringify(input.aliasesJa ?? []), input.status, input.replacedByParameterId ?? null, JSON.stringify(input.comparableParameterIds ?? []), JSON.stringify(input.conflictingParameterIds ?? []), input.minimumObservationIntervalMinutes ?? null, 'governance-v1', new Date().toISOString()); }

export async function getUserParameterSetting(userId: string, parameterId: string) { return (await dbPromise).getFirstAsync<Row>('SELECT * FROM user_parameter_settings WHERE user_id = ? AND parameter_id = ?', userId, parameterId); }
export async function setUserParameterSetting(input: { userId: string; parameterId: string; collectionEnabled: boolean; cloudSyncEnabled?: boolean; externalAiEnabled?: boolean; rawValueAccessEnabled?: boolean; enabledReason?: string }) {
  const db = await dbPromise; const timestamp = new Date().toISOString();
  await db.runAsync(`INSERT INTO user_parameter_settings (user_id,parameter_id,collection_enabled,cloud_sync_enabled,external_ai_enabled,raw_value_access_enabled,enabled_reason,enabled_at,disabled_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,parameter_id) DO UPDATE SET collection_enabled=excluded.collection_enabled,cloud_sync_enabled=excluded.cloud_sync_enabled,external_ai_enabled=excluded.external_ai_enabled,raw_value_access_enabled=excluded.raw_value_access_enabled,enabled_reason=excluded.enabled_reason,enabled_at=excluded.enabled_at,disabled_at=excluded.disabled_at,updated_at=excluded.updated_at`, input.userId, input.parameterId, input.collectionEnabled ? 1 : 0, input.cloudSyncEnabled ? 1 : 0, input.externalAiEnabled ? 1 : 0, input.rawValueAccessEnabled ? 1 : 0, input.enabledReason ?? null, input.collectionEnabled ? timestamp : null, input.collectionEnabled ? null : timestamp, timestamp);
}

export async function createObservationEpisode(input: { userId: string; checkinId?: string; hypothesisId?: string; episodeType: string; captureMode: string; observedAt: string; startedAt?: string; endedAt?: string; sourceContext?: Record<string, unknown> }) {
  const db = await dbPromise; const id = newId('episode'); await db.runAsync('INSERT INTO observation_episodes (id,user_id,checkin_id,hypothesis_id,episode_type,capture_mode,observed_at,started_at,ended_at,source_context_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)', id, input.userId, input.checkinId ?? null, input.hypothesisId ?? null, input.episodeType, input.captureMode, input.observedAt, input.startedAt ?? null, input.endedAt ?? null, JSON.stringify(input.sourceContext ?? {}), new Date().toISOString()); return id;
}

function columns(input: ParameterValueInput): Array<string | number | null> { if (input.valueType === 'boolean') return [input.value ? 1 : 0, null, null, null, null, null]; if (input.valueType === 'integer') return [null, input.value, null, null, null, null]; if (['number', 'ordinal', 'duration_minutes', 'percentage'].includes(input.valueType)) return [null, null, input.value as number, null, null, null]; if (input.valueType === 'short_text') return [null, null, null, input.value, null, null]; if (input.valueType === 'datetime') return [null, null, null, null, input.value, null]; return [null, null, null, null, null, JSON.stringify(input.value)]; }
async function insertValue(db: SQLite.SQLiteDatabase, input: { episodeId: string; parameterId: string; value?: ParameterValueInput; observedAt: string; sourceType: ParameterSourceType; sourceProvider?: string; certainty?: Certainty; userConfirmed?: boolean; missingReason?: string; externalRecordId?: string }) {
  const def = await definition(db, input.parameterId); if (!def) throw new Error(`unknown parameter: ${input.parameterId}`); const isMissing = Boolean(input.missingReason); let value = input.value;
  if (!isMissing) { if (!value) throw new Error('value required unless missing'); validateParameterValue(def, value, await allowed(db, input.parameterId)); } else value = undefined;
  const typed = value ? columns(value) : [null, null, null, null, null, null];
  await db.runAsync('INSERT INTO parameter_values (id,episode_id,parameter_id,boolean_value,integer_value,number_value,text_value,datetime_value,json_value,observed_at,source_type,source_provider,external_record_id,certainty,user_confirmed,parameter_version,transformation_version,is_missing,missing_reason,eligible_for_evaluation,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', newId('param_value'), input.episodeId, input.parameterId, ...typed, input.observedAt, input.sourceType, input.sourceProvider ?? null, input.externalRecordId ?? null, input.certainty ?? 'medium', input.userConfirmed ? 1 : 0, def.definition_version, null, isMissing ? 1 : 0, input.missingReason ?? null, isMissing ? 0 : 1, new Date().toISOString());
}
export async function saveParameterValue(input: Parameters<typeof insertValue>[1]) { return insertValue(await dbPromise, input); }
export async function saveParameterValuesTransaction(input: { episode: Parameters<typeof createObservationEpisode>[0]; values: Omit<Parameters<typeof insertValue>[1], 'episodeId'>[] }) { const db = await dbPromise; let id = ''; await db.withTransactionAsync(async () => { id = newId('episode'); const e = input.episode; await db.runAsync('INSERT INTO observation_episodes (id,user_id,checkin_id,hypothesis_id,episode_type,capture_mode,observed_at,started_at,ended_at,source_context_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)', id, e.userId, e.checkinId ?? null, e.hypothesisId ?? null, e.episodeType, e.captureMode, e.observedAt, e.startedAt ?? null, e.endedAt ?? null, JSON.stringify(e.sourceContext ?? {}), new Date().toISOString()); for (const value of input.values) await insertValue(db, { ...value, episodeId: id }); }); return id; }
export async function getEpisodeValues(episodeId: string) { return (await dbPromise).getAllAsync<Row>('SELECT pv.*,pd.name_ja,pd.value_type FROM parameter_values pv JOIN parameter_definitions pd ON pd.id=pv.parameter_id WHERE pv.episode_id=? ORDER BY pv.created_at', episodeId); }
export async function queryParameterValues(input: { userId?: string; parameterId?: string; from?: string; to?: string; eligibleOnly?: boolean }) { const clauses: string[] = []; const args: (string | number)[] = []; if (input.userId) { clauses.push('oe.user_id=?'); args.push(input.userId); } if (input.parameterId) { clauses.push('pv.parameter_id=?'); args.push(input.parameterId); } if (input.from) { clauses.push('pv.observed_at>=?'); args.push(input.from); } if (input.to) { clauses.push('pv.observed_at<?'); args.push(input.to); } if (input.eligibleOnly) clauses.push('pv.eligible_for_evaluation=1'); return (await dbPromise).getAllAsync<Row>(`SELECT pv.*,oe.user_id FROM parameter_values pv JOIN observation_episodes oe ON oe.id=pv.episode_id ${clauses.length ? `WHERE ${clauses.join(' AND ')}` : ''} ORDER BY pv.observed_at`, ...args); }
export async function getHypothesisRequirements(hypothesisId: string) { return (await dbPromise).getAllAsync<Row>('SELECT hpr.*,pd.name_ja,pd.value_type,pd.askable FROM hypothesis_parameter_requirements hpr JOIN parameter_definitions pd ON pd.id=hpr.parameter_id WHERE hpr.hypothesis_id=? ORDER BY hpr.priority', hypothesisId); }
export async function getMissingHypothesisParameters(input: { hypothesisId: string; userId: string }) { const db = await dbPromise; const reqs = await getHypothesisRequirements(input.hypothesisId); const missing: Row[] = []; for (const req of reqs) { const parameterId = String(req.parameter_id); const count = await db.getFirstAsync<{ count: number }>('SELECT COUNT(*) count FROM parameter_values pv JOIN observation_episodes oe ON oe.id=pv.episode_id WHERE oe.user_id=? AND (oe.hypothesis_id=? OR oe.hypothesis_id IS NULL) AND pv.parameter_id=? AND pv.is_missing=0', input.userId, input.hypothesisId, parameterId); const source = await db.getFirstAsync<{ source_type: string }>('SELECT source_type FROM parameter_source_definitions WHERE parameter_id=? ORDER BY priority LIMIT 1', parameterId); if ((!count || count.count < Number(req.minimum_samples ?? 1)) && source?.source_type === 'user' && Number(req.askable) === 1) missing.push(req); } return missing; }

export async function saveGeneratedQuestion(input: { userId: string; hypothesisId?: string; parameterId: string; checkinId?: string; generatedText: string; answerSchema: Record<string, unknown>; reason: Record<string, unknown>; generationMethod?: 'template' | 'ai' | 'fallback'; validationStatus?: 'pending' | 'accepted' | 'rejected' | 'fallback_used' }) { const db = await dbPromise; const def = await definition(db, input.parameterId); const answerType = String(input.answerSchema.valueType ?? ''); const numeric = ['integer', 'number', 'ordinal', 'duration_minutes', 'percentage'].includes(def?.value_type ?? ''); const answerMatches = Boolean(def) && (answerType === def?.value_type || (numeric && answerType === 'number')); const forbidden = /仮説|正しい|きっと|当然/.test(input.generatedText); if (!def || !input.generatedText.trim() || input.generatedText.length > 240 || !answerMatches || forbidden) throw new Error('invalid generated question'); const method = input.generationMethod ?? 'template'; await db.runAsync('INSERT INTO generated_questions (id,user_id,hypothesis_id,parameter_id,checkin_id,generated_text,answer_schema_json,generation_method,generation_version,reason_json,validation_status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)', newId('question'), input.userId, input.hypothesisId ?? null, input.parameterId, input.checkinId ?? null, input.generatedText.trim(), JSON.stringify(input.answerSchema), method, 'question-v1', JSON.stringify(input.reason), input.validationStatus ?? 'accepted', new Date().toISOString()); }
export async function listGeneratedQuestions(input: { userId: string; parameterId?: string; limit?: number }) { const db = await dbPromise; if (input.parameterId) return db.getAllAsync<Row>('SELECT * FROM generated_questions WHERE user_id=? AND parameter_id=? ORDER BY created_at DESC LIMIT ?', input.userId, input.parameterId, input.limit ?? 50); return db.getAllAsync<Row>('SELECT * FROM generated_questions WHERE user_id=? ORDER BY created_at DESC LIMIT ?', input.userId, input.limit ?? 50); }

export async function generateQuestionsForHypothesis(input: { userId: string; hypothesisId: string; checkinId?: string }) { const db = await dbPromise; const missing = await getMissingHypothesisParameters(input); const result: string[] = []; for (const item of missing) { const def = await definition(db, String(item.parameter_id)); if (!def) continue; const values = await allowed(db, def.id); const text = fallbackQuestionText(def, values); await saveGeneratedQuestion({ ...input, parameterId: def.id, generatedText: text, answerSchema: { valueType: def.value_type, allowedValues: values.map((value) => value.value_key) }, reason: { kind: 'missing_hypothesis_parameter', parameterId: def.id }, generationMethod: 'fallback', validationStatus: 'fallback_used' }); result.push(text); } return result; }

export async function saveResponseParametersInTransaction(db: SQLite.SQLiteDatabase, input: { responseId: string; checkinId: string; hypothesisId?: string; payload: Record<string, unknown>; observedAt: string }) {
  const episodeId = `episode_${input.responseId}`;
  await db.runAsync('INSERT OR IGNORE INTO observation_episodes (id,user_id,checkin_id,hypothesis_id,episode_type,capture_mode,observed_at,source_context_json,created_at) VALUES (?,?,?,?,?,?,?,?,?)', episodeId, 'local-user', input.checkinId, input.hypothesisId ?? null, 'momentary_checkin', 'momentary_observation', input.observedAt, '{}', input.observedAt);
  const candidates: Array<{ parameterId: string; value: ParameterValueInput }> = [];
  const add = (parameterId: string, value: ParameterValueInput) => candidates.push({ parameterId, value });
  if (typeof input.payload.energy === 'number') add('energy_level', { valueType: 'number', value: input.payload.energy });
  if (typeof input.payload.activity_type === 'string') add('activity_category', { valueType: 'single_choice', value: input.payload.activity_type });
  if (typeof input.payload.started === 'boolean') add('start_status', { valueType: 'single_choice', value: input.payload.started ? 'started' : 'not_started' });
  if (typeof input.payload.completed === 'boolean') add('completion_status', { valueType: 'single_choice', value: input.payload.completed ? 'completed' : 'not_completed' });
  add('time_period', { valueType: 'single_choice', value: classifyTimePeriod(new Date(input.observedAt)) });
  for (const item of candidates) { try { await insertValue(db, { episodeId, parameterId: item.parameterId, value: item.value, observedAt: input.observedAt, sourceType: item.parameterId === 'time_period' ? 'system' : 'user', certainty: 'high', userConfirmed: item.parameterId !== 'time_period' }); } catch (error) { if (!String(error).includes('unknown allowed value')) throw error; } }
}

function classifyTimePeriod(date: Date) { const hour = date.getHours(); if (hour < 6) return 'night'; if (hour < 12) return 'morning'; if (hour < 18) return 'daytime'; return 'evening'; }
