import { evaluateQuestionBudget, type QuestionBudgetSettings } from '../../domain';
import { fallbackQuestionText } from '../../domain/parameters';
import { dbPromise } from '../db';
import { getSetting, setSetting } from './settingsRepository';
import { saveGeneratedQuestion } from './parameterRepository';
import { selectNextQuestionTargets } from './hypothesisCandidateRepository';

export async function buildQuestionGenerationContext(input: { userId: string; hypothesisId: string; parameterId: string; targetCohortKey?: string }) {
  const db = await dbPromise;
  const parameter = await db.getFirstAsync<Record<string, unknown>>("SELECT pd.* FROM parameter_definitions pd LEFT JOIN parameter_governance pg ON pg.parameter_id=pd.id WHERE pd.id=? AND pd.is_active=1 AND COALESCE(pg.status,'active') NOT IN ('deprecated','archived')", input.parameterId);
  if (!parameter) throw new Error('parameter_not_found');
  const metadata = await db.getFirstAsync<Record<string, unknown>>('SELECT * FROM parameter_question_metadata WHERE parameter_id=?', input.parameterId);
  const values = await db.getAllAsync<{ value_key: string; label_ja: string }>('SELECT value_key,label_ja FROM parameter_allowed_values WHERE parameter_id=? AND is_active=1 ORDER BY sort_order', input.parameterId);
  return { parameter: { id: input.parameterId, nameJa: String(parameter.name_ja), descriptionJa: String(parameter.description_ja), valueType: String(parameter.value_type), minimumValue: parameter.minimum_value as number | null, maximumValue: parameter.maximum_value as number | null, unit: parameter.unit as string | null, allowedValues: values.map((value) => ({ key: value.value_key, labelJa: value.label_ja })) }, measurement: { targetJa: String(metadata?.measurement_target_ja ?? parameter.name_ja), timeReference: String(metadata?.time_reference ?? 'current'), subjectType: String(metadata?.subject_type ?? 'user') }, currentContext: { targetCohortKey: input.targetCohortKey }, constraints: { neutralWordingRequired: Number(metadata?.neutral_wording_required ?? 1) === 1, hypothesisDisclosureProhibited: Number(metadata?.hypothesis_disclosure_prohibited ?? 1) === 1, leadingWordingProhibited: Number(metadata?.leading_wording_prohibited ?? 1) === 1, maximumLength: 240 } };
}
export async function validateGeneratedQuestion(input: { generatedText: string; parameterId: string; answerSchema: Record<string, unknown> }) {
  const db = await dbPromise; const parameter = await db.getFirstAsync<{ value_type: string; askable: number; is_active: number }>("SELECT pd.value_type,pd.askable,pd.is_active FROM parameter_definitions pd LEFT JOIN parameter_governance pg ON pg.parameter_id=pd.id WHERE pd.id=? AND COALESCE(pg.status,'active') NOT IN ('deprecated','archived')", input.parameterId);
  if (!parameter || !parameter.askable || !parameter.is_active || !input.generatedText.trim() || input.generatedText.length > 240) return { valid: false, errors: ['parameter_or_text_invalid'] };
  const numeric = ['integer', 'number', 'ordinal', 'duration_minutes', 'percentage'].includes(parameter.value_type); const typeValid = input.answerSchema.valueType === parameter.value_type || numeric && input.answerSchema.valueType === 'number'; if (!typeValid) return { valid: false, errors: ['answer_schema_mismatch'] };
  if (parameter.value_type === 'single_choice') { const allowed = await db.getAllAsync<{ value_key: string }>('SELECT value_key FROM parameter_allowed_values WHERE parameter_id=? AND is_active=1', input.parameterId); const options = input.answerSchema.allowedValues; if (!Array.isArray(options) || options.some((option) => !allowed.some((item) => item.value_key === option))) return { valid: false, errors: ['allowed_values_mismatch'] }; }
  return { valid: true, errors: [] };
}
export async function generateQuestion(input: { userId: string; hypothesisId: string; parameterId: string; targetCohortKey?: string; checkinId?: string }) { const context = await buildQuestionGenerationContext(input); const definition = { id: context.parameter.id, name_ja: context.parameter.nameJa, description_ja: context.parameter.descriptionJa, value_type: context.parameter.valueType as never, minimum_value: context.parameter.minimumValue ?? null, maximum_value: context.parameter.maximumValue ?? null, unit: context.parameter.unit ?? null, parameter_layer: 'base' as const, temporal_type: 'momentary', askable: 1, usable_as_condition: 0, usable_as_outcome: 0, usable_as_explanation: 0, sensitivity: 'normal', enabled_by_default: 0, is_active: 1, definition_version: 'parameter-v2' }; const allowed = context.parameter.allowedValues.map((value) => ({ parameter_id: input.parameterId, value_key: value.key, label_ja: value.labelJa, sort_order: 0, numeric_value: null, is_active: 1, definition_version: 'parameter-v2' as string })); const text = fallbackQuestionText(definition, allowed); const answerSchema = { valueType: context.parameter.valueType, allowedValues: context.parameter.allowedValues.map((value) => value.key) }; const validation = await validateGeneratedQuestion({ generatedText: text, parameterId: input.parameterId, answerSchema }); if (!validation.valid) throw new Error('fallback_question_invalid'); await saveGeneratedQuestion({ ...input, generatedText: text, answerSchema, reason: { requirementRole: 'dynamic_target', targetCohortKey: input.targetCohortKey ?? null }, generationMethod: 'fallback', validationStatus: 'fallback_used' }); return { text, parameterId: input.parameterId, answerSchema }; }
export async function generateNextQuestions(input: { userId: string; hypothesisId: string; checkinId?: string; limit?: number }) { const budget = await getQuestionBudgetDecision(input); if (!budget.allowed) { if ('pauseUntil' in budget && budget.pauseUntil) await setSetting(`question_pause_until:${input.hypothesisId}`, budget.pauseUntil); return []; } const targets = await selectNextQuestionTargets(input); const questions = []; for (const target of targets.slice(0, Math.min(input.limit ?? 3, 3))) questions.push(await generateQuestion({ ...input, parameterId: String(target.parameterId), targetCohortKey: target.targetCohortKey as string | undefined })); return questions; }
export async function getQuestionBudgetDecision(input: { userId: string; hypothesisId: string; now?: string; settings?: Partial<QuestionBudgetSettings> }) {
  const db = await dbPromise; const now = new Date(input.now ?? new Date().toISOString()); const dayStart = new Date(now); dayStart.setHours(0, 0, 0, 0); const hourStart = new Date(now.getTime() - 3600000); const day = await db.getFirstAsync<{ count: number }>('SELECT COUNT(*) count FROM generated_questions WHERE user_id=? AND created_at>=?', input.userId, dayStart.toISOString()); const hour = await db.getFirstAsync<{ count: number }>('SELECT COUNT(*) count FROM generated_questions WHERE user_id=? AND created_at>=?', input.userId, hourStart.toISOString()); const hypothesis = await db.getFirstAsync<{ count: number }>('SELECT COUNT(*) count FROM generated_questions WHERE user_id=? AND hypothesis_id=? AND created_at>=?', input.userId, input.hypothesisId, dayStart.toISOString()); const last = await db.getFirstAsync<{ created_at: string }>('SELECT created_at FROM generated_questions WHERE user_id=? ORDER BY created_at DESC LIMIT 1', input.userId); const recent = await db.getAllAsync<{ response_status: string }>('SELECT response_status FROM checkins WHERE hypothesis_id=? ORDER BY scheduled_at DESC LIMIT 10', input.hypothesisId); const answered = recent.filter((row) => row.response_status === 'answered').length; const completed = recent.filter((row) => ['answered', 'skipped', 'expired'].includes(row.response_status)).length; const skips = recent.findIndex((row) => row.response_status === 'answered'); const consecutiveSkips = skips < 0 ? recent.length : skips; const pauseUntil = await getSetting<string | null>(`question_pause_until:${input.hypothesisId}`, null); const notificationSettings = await getSetting<{ quiet_periods?: Array<{ start: string; end: string }> }>('notification_settings', {}); const quiet = notificationSettings.quiet_periods?.[0]; return evaluateQuestionBudget({ now: now.toISOString(), todayCount: day?.count ?? 0, hourCount: hour?.count ?? 0, hypothesisTodayCount: hypothesis?.count ?? 0, lastQuestionAt: last?.created_at ?? null, consecutiveSkips, pauseUntil, quietHoursStart: quiet?.start, quietHoursEnd: quiet?.end, recentResponseRate: completed ? answered / completed : undefined, notificationPermissionGranted: true, hypothesisActive: true, settings: input.settings });
}
