import { SourceProviderRegistry, SystemClockAdapter, TestFixtureAdapter, ManualImportAdapter, type ExternalParameterMapping, type ExternalSourceRecord, type SourceAdapter, type SourceFetchInput, type SourceProviderKey } from '../../domain';
import { dbPromise, newId } from '../db';
import { validateParameterValue, type ParameterValueInput } from '../../domain/parameters';

type Row = Record<string, unknown>;
export const sourceProviderRegistry = new SourceProviderRegistry();
sourceProviderRegistry.register(new SystemClockAdapter());
sourceProviderRegistry.register(new TestFixtureAdapter());
sourceProviderRegistry.register(new ManualImportAdapter());
const mappings = new Map<string, ExternalParameterMapping>();
for (const parameterId of ['observed_at', 'time_period', 'day_of_week', 'day_type']) mappings.set(`system_clock_${parameterId}`, { id: `system_clock_${parameterId}`, providerKey: 'system_clock', externalField: parameterId, parameterId, transformation: { type: 'identity' }, certainty: 'high', transformationVersion: 'clock-v1', isActive: true });
export function registerSourceAdapter(adapter: SourceAdapter) { sourceProviderRegistry.register(adapter); }
export function getSourceAdapter(providerKey: string) { return sourceProviderRegistry.get(providerKey); }
export function listAvailableSourceProviders() { return sourceProviderRegistry.list().map((adapter) => adapter.providerKey); }
export function registerParameterMapping(mapping: ExternalParameterMapping) { mappings.set(mapping.id, mapping); }
export function listParameterMappings(providerKey: string) { return [...mappings.values()].filter((mapping) => mapping.providerKey === providerKey && mapping.isActive); }
export async function getSourcePermissionStatus(providerKey: string) { return sourceProviderRegistry.get(providerKey).getPermissionStatus(); }
export async function requestSourcePermission(providerKey: string) { const adapter = sourceProviderRegistry.get(providerKey); return adapter.requestPermission ? adapter.requestPermission() : adapter.getPermissionStatus(); }

export async function planParameterImports(input: { userId: string; providerKey: string; parameterIds: string[]; startAt: string; endAt: string; reason: 'base' | 'hypothesis_required' | 'user_selected' | 'refresh' }) { const db = await dbPromise; const adapter = sourceProviderRegistry.get(input.providerKey); const permission = await adapter.getPermissionStatus(); const providerMappings = listParameterMappings(input.providerKey); const skipped: Array<{ parameterId: string; reason: string }> = []; const approved: string[] = []; for (const parameterId of input.parameterIds) { const definition = await db.getFirstAsync<Row>('SELECT * FROM parameter_definitions WHERE id=? AND is_active=1', parameterId); const setting = await db.getFirstAsync<Row>('SELECT * FROM user_parameter_settings WHERE user_id=? AND parameter_id=?', input.userId, parameterId); const mapping = providerMappings.find((item) => item.parameterId === parameterId); if (!definition) skipped.push({ parameterId, reason: 'unsupported' }); else if (!mapping) skipped.push({ parameterId, reason: 'mapping_missing' }); else if (!setting || !setting.collection_enabled) skipped.push({ parameterId, reason: 'collection_disabled' }); else if (permission !== 'granted' && permission !== 'not_required') skipped.push({ parameterId, reason: 'permission_missing' }); else if (definition.sensitivity === 'sensitive' && !setting.collection_enabled) skipped.push({ parameterId, reason: 'sensitive_consent_missing' }); else approved.push(parameterId); } return { providerKey: input.providerKey, parameterIds: approved, startAt: input.startAt, endAt: input.endAt, reason: input.reason, skipped }; }

export async function normalizeExternalRecord(input: { record: ExternalSourceRecord; mapping: ExternalParameterMapping; parameter: Row }): Promise<{ parameterId: string; value: ParameterValueInput; observedAt: string; source: { providerKey: string; externalRecordId: string; externalType: string }; certainty: 'high' | 'medium' | 'low'; transformationVersion: string; userConfirmationRequired: boolean }> { const { record, mapping, parameter } = input; const raw = record.rawFields[mapping.externalField]; let value: unknown = raw; if (mapping.transformation.type === 'unit_conversion') { if (typeof raw !== 'number') throw new Error('invalid_external_value'); if (mapping.transformation.fromUnit === 'hours' && mapping.transformation.toUnit === 'minutes') value = raw * 60; if (mapping.transformation.fromUnit === 'seconds' && mapping.transformation.toUnit === 'minutes') value = raw / 60; } else if (mapping.transformation.type === 'enum_mapping') { value = mapping.transformation.values[String(raw)]; } else if (mapping.transformation.type === 'duration_between') { const start = record.rawFields[mapping.transformation.startField]; const end = record.rawFields[mapping.transformation.endField]; if (typeof start !== 'string' || typeof end !== 'string') throw new Error('invalid_external_value'); value = (Date.parse(end) - Date.parse(start)) / 60000; } else if (mapping.transformation.type === 'count_records') { value = Array.isArray(raw) ? raw.length : 0; } const valueType = String(parameter.value_type) as ParameterValueInput['valueType']; const typed = (valueType === 'multi_choice' || valueType === 'tag_set') ? { valueType, value: Array.isArray(value) ? value.map(String) : [String(value)] } : { valueType, value } as ParameterValueInput; validateParameterValue({ ...parameter, parameter_layer: String(parameter.parameter_layer) as never, value_type: valueType, minimum_value: parameter.minimum_value as number | null, maximum_value: parameter.maximum_value as number | null } as never, typed); return { parameterId: mapping.parameterId, value: typed, observedAt: record.observedAt, source: { providerKey: record.providerKey, externalRecordId: record.externalRecordId, externalType: record.externalType }, certainty: mapping.certainty, transformationVersion: mapping.transformationVersion, userConfirmationRequired: Boolean(parameter.sensitivity === 'sensitive') }; }

function typedColumns(value: ParameterValueInput) { if (value.valueType === 'boolean') return [value.value ? 1 : 0, null, null, null, null, null]; if (value.valueType === 'integer') return [null, value.value, null, null, null, null]; if (['number', 'ordinal', 'duration_minutes', 'percentage'].includes(value.valueType)) return [null, null, value.value as number, null, null, null]; if (value.valueType === 'short_text') return [null, null, null, value.value, null, null]; if (value.valueType === 'datetime') return [null, null, null, null, value.value, null]; return [null, null, null, null, null, JSON.stringify(value.value)]; }
export async function saveImportedValuesTransaction(input: { userId: string; providerKey: string; records: Array<{ record: ExternalSourceRecord; values: Awaited<ReturnType<typeof normalizeExternalRecord>>[] }>; batchId: string }) { const db = await dbPromise; let imported = 0; let duplicates = 0; await db.withTransactionAsync(async () => { for (const item of input.records) { const episodeId = `external_${input.providerKey}_${item.record.externalRecordId}`; await db.runAsync('INSERT OR IGNORE INTO observation_episodes (id,user_id,episode_type,capture_mode,observed_at,ended_at,source_context_json,created_at) VALUES (?,?,?,?,?,?,?,?)', episodeId, input.userId, 'external_import', 'system_import', item.record.observedAt, item.record.endedAt ?? null, JSON.stringify({ providerKey: input.providerKey, externalRecordId: item.record.externalRecordId }), item.record.importedAt); for (const normalized of item.values) { const parameter = await db.getFirstAsync<Row>('SELECT * FROM parameter_definitions WHERE id=?', normalized.parameterId); if (!parameter) continue; const columns = typedColumns(normalized.value); try { await db.runAsync('INSERT INTO parameter_values (id,episode_id,parameter_id,boolean_value,integer_value,number_value,text_value,datetime_value,json_value,observed_at,source_type,source_provider,external_record_id,certainty,user_confirmed,parameter_version,transformation_version,is_missing,eligible_for_evaluation,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', newId('param_value'), episodeId, normalized.parameterId, ...columns, normalized.observedAt, 'external_app', normalized.source.providerKey, normalized.source.externalRecordId, normalized.certainty, normalized.userConfirmationRequired ? 0 : 1, String(parameter.definition_version), normalized.transformationVersion, 0, 1, new Date().toISOString()); imported += 1; } catch (error) { if (String(error).includes('UNIQUE')) duplicates += 1; else throw error; } } } }); return { imported, duplicates }; }

export async function runParameterImport(input: { userId: string; providerKey: SourceProviderKey; fetch: SourceFetchInput; reason: 'initial_import' | 'scheduled_refresh' | 'hypothesis_required' | 'user_requested' | 'recovery' }) { const db = await dbPromise; const plan = await planParameterImports({ userId: input.userId, providerKey: input.providerKey, parameterIds: input.fetch.requestedParameterIds, startAt: input.fetch.startAt, endAt: input.fetch.endAt, reason: input.reason === 'user_requested' ? 'user_selected' : input.reason === 'scheduled_refresh' ? 'refresh' : 'hypothesis_required' }); const batchId = newId('import_batch'); await db.runAsync('INSERT INTO external_import_batches (id,user_id,provider_key,reason,period_start_at,period_end_at,requested_parameter_ids_json,status,created_at) VALUES (?,?,?,?,?,?,?,?,?)', batchId, input.userId, input.providerKey, input.reason, input.fetch.startAt, input.fetch.endAt, JSON.stringify(plan.parameterIds), 'running', new Date().toISOString()); const adapter = sourceProviderRegistry.get(input.providerKey); const fetched = await adapter.fetch({ ...input.fetch, requestedParameterIds: plan.parameterIds }); const providerMappings = listParameterMappings(input.providerKey); const prepared: Array<{ record: ExternalSourceRecord; values: Awaited<ReturnType<typeof normalizeExternalRecord>>[] }> = []; for (const record of fetched.records) { const values = []; for (const mapping of providerMappings.filter((item) => plan.parameterIds.includes(item.parameterId))) { const parameter = await db.getFirstAsync<Row>('SELECT * FROM parameter_definitions WHERE id=?', mapping.parameterId); if (!parameter) continue; try { values.push(await normalizeExternalRecord({ record, mapping, parameter })); } catch { } } prepared.push({ record, values }); await db.runAsync('INSERT OR IGNORE INTO external_import_items (id,batch_id,provider_key,external_record_id,external_type,observed_at,status,imported_value_count,created_at) VALUES (?,?,?,?,?,?,?,?,?)', newId('import_item'), batchId, input.providerKey, record.externalRecordId, record.externalType, record.observedAt, 'imported', values.length, new Date().toISOString()); } const result = await saveImportedValuesTransaction({ userId: input.userId, providerKey: input.providerKey, records: prepared, batchId }); await db.runAsync("UPDATE external_import_batches SET fetched_record_count=?,imported_value_count=?,duplicate_count=?,status=?,completed_at=? WHERE id=?", fetched.records.length, result.imported, result.duplicates, result.duplicates ? 'partially_completed' : 'completed', new Date().toISOString(), batchId); return { batchId, ...result, fetchedRecords: fetched.records.length, skipped: plan.skipped }; }
