import { commands, env, window, workspace, Uri, type ExtensionContext } from "vscode";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const exec = promisify(execFile);
type TemplateSummary = { id: string; name: string; description: string; theme: string; field_count?: number };
function root() { const folder = workspace.workspaceFolders?.[0]?.uri.fsPath; if (!folder) throw new Error("Open a MeTheory workspace first."); return folder; }
function cliPath(context: ExtensionContext) { return resolve(context.extensionUri.fsPath, "..", "cli", "src", "main.ts"); }
async function cli(context: ExtensionContext, args: string[]) { return exec(process.execPath, ["--experimental-strip-types", cliPath(context), ...args], { cwd: root() }); }
async function api(path: string, init?: RequestInit) { const response = await fetch(`http://127.0.0.1:8100${path}`, init); const payload = await response.json() as any; if (!response.ok) throw new Error(payload.error ?? `api_${response.status}`); return payload; }
async function startService(context: ExtensionContext) { await cli(context, ["workspace", "init"]); await cli(context, ["service", "start"]); }
async function templates(theme: string): Promise<TemplateSummary[]> { const payload = await api(`/v1/templates?userId=${encodeURIComponent(process.env.METHEORY_USER_ID ?? "local-user")}`); const terms = theme.toLowerCase().split(/\s+/).filter(Boolean); return (payload.items as TemplateSummary[]).map(item => ({ ...item, score: terms.reduce((score, term) => score + ((item.name + " " + item.description + " " + item.theme).toLowerCase().includes(term) ? 1 : 0), 0) })).sort((a: any, b: any) => b.score - a.score).slice(0, 3); }
function safeSegment(value: string) { return value.trim().replace(/[<>:"/\\|?*\x00-\x1f]/g, "-").replace(/\.+$/g, "").slice(0, 100) || "note"; }
async function createNote(context: ExtensionContext, theme: string) { await startService(context); const suggestions = await templates(theme); const selected = await window.showQuickPick([{ label: "(No template)", id: "" }, ...suggestions.map(item => ({ label: item.name, description: item.description, id: item.id }))], { placeHolder: "Choose a primary template" }); if (!selected) return; const title = await window.showInputBox({ prompt: "Note title", value: selected.id ? selected.label : theme }); if (!title) return; const category = await window.showInputBox({ prompt: "Directory under notes (max two levels)", value: "inbox" }); if (category === undefined) return; const segments = category.split(/[\\/]/).filter(Boolean).slice(0, 2).map(safeSegment); const directory = join(root(), "notes", ...segments); await mkdir(directory, { recursive: true }); const date = new Date().toISOString(); const filename = `${date.slice(0, 10)}-${safeSegment(title)}.md`; const path = join(directory, filename); const template = selected.id ? await api(`/v1/templates/${selected.id}?userId=${encodeURIComponent(process.env.METHEORY_USER_ID ?? "local-user")}`) : null; const prompts = (template?.currentVersion?.fields ?? []).map((field: any) => `- ${field.label}${field.description ? `: ${field.description}` : ""}`).join("\n"); const body = `# ${title}\n\n${prompts ? `<!--\nMeTheory writing guide:\n${prompts}\n-->\n\n` : ""}`; await writeFile(path, ["---", `recorded_at: ${date}`, `template_id: ${selected.id || "null"}`, `template_version_id: ${template?.currentVersion?.id ?? "null"}`, "---", "", body].join("\n"), "utf8"); await cli(context, ["entry", "sync", path]); if (workspace.getConfiguration("metheory.notes").get("openAfterCreate", true)) await commands.executeCommand("vscode.open", Uri.file(path)); window.showInformationMessage(`MeTheory: created ${filename}`); }
class StartViewProvider { constructor(private readonly context: ExtensionContext) {} resolveWebviewView(view: any) { view.webview.options = { enableScripts: true }; view.webview.html = `<!doctype html><html><body><h2>MeTheory</h2><input id="theme" placeholder="What do you want to write about?" style="width:100%"/><button id="create">Create note</button><script>const vscode=acquireVsCodeApi();document.getElementById('create').onclick=()=>vscode.postMessage({type:'startNote',theme:document.getElementById('theme').value});</script></body></html>`; view.webview.onDidReceiveMessage((message: any) => { if (message.type === "startNote") void createNote(this.context, String(message.theme ?? "")); }); } }
class StatusViewProvider { constructor(private readonly context: ExtensionContext) {} resolveWebviewView(view: any) { view.webview.options = { enableScripts: true }; const refresh = async () => { try { const service = await cli(this.context, ["service", "status"]); const status = await cli(this.context, ["workspace", "status"]); view.webview.html = `<!doctype html><html><body><h2>Status</h2><pre>${escapeHtml(service.stdout + status.stdout)}</pre></body></html>`; } catch (error) { view.webview.html = `<h2>Status</h2><p>${escapeHtml(error instanceof Error ? error.message : "error")}</p>`; } }; void refresh(); } }
class PrivacyViewProvider { constructor(private readonly context: ExtensionContext) {} resolveWebviewView(view: any) { view.webview.options = { enableScripts: true }; const load = async () => { try { const [status, consents, fields, audit] = await Promise.all([cli(this.context, ["privacy", "status"]), cli(this.context, ["privacy", "consents", "list"]), cli(this.context, ["privacy", "fields", "list"]), cli(this.context, ["privacy", "audit", "list"])]); view.webview.html = `<!doctype html><html><body><h2>Privacy</h2><h3>Status</h3><pre>${escapeHtml(status.stdout)}</pre><h3>Protected fields</h3><pre>${escapeHtml(fields.stdout)}</pre><h3>Consent and external AI permissions</h3><pre>${escapeHtml(consents.stdout)}</pre><h3>Audit and safe-delete history</h3><pre>${escapeHtml(audit.stdout)}</pre><p>Use the consent revoke and safe-delete commands to change processing permissions. Markdown files are review-only and are never edited automatically.</p></body></html>`; } catch (error) { view.webview.html = `<h2>Privacy</h2><p>${escapeHtml(error instanceof Error ? error.message : "error")}</p>`; } }; void load(); } }
class CliListProvider { constructor(private readonly context: ExtensionContext, private readonly args: string[], private readonly title: string) {} async getChildren() { try { const result = await cli(this.context, this.args); const payload = JSON.parse(result.stdout) as any; const rows = Array.isArray(payload) ? payload : payload.items ?? []; return rows.map((row: any) => ({ label: String(row.name ?? row.theme ?? row.entryId ?? row.id ?? "item"), description: String(row.description ?? row.status ?? row.provider ?? ""), tooltip: `${this.title}: ${String(row.id ?? row.entryId ?? "")}`, collapsibleState: 0 })); } catch (error) { return [{ label: `${this.title}: ${error instanceof Error ? error.message : "unavailable"}`, collapsibleState: 0 }]; } } getTreeItem(item: any) { return item; } }
function escapeHtml(value: string) { return value.replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char] ?? char)); }
function activeMarkdown() { const file = window.activeTextEditor?.document.uri.fsPath; if (!file || !file.endsWith(".md")) throw new Error("Open a Markdown file first."); return file; }
async function runAiCommand(context: ExtensionContext, args: string[]) { const result = await cli(context, args); window.showInformationMessage(result.stdout.trim().slice(0, 1000) || "MeTheory completed."); }

export function activate(context: ExtensionContext) {
  context.subscriptions.push(window.registerWebviewViewProvider("metheory.start", new StartViewProvider(context)), window.registerWebviewViewProvider("metheory.status", new StatusViewProvider(context)), window.registerWebviewViewProvider("metheory.privacy", new PrivacyViewProvider(context)), window.registerTreeDataProvider("metheory.templates", new CliListProvider(context, ["template", "list"], "Templates")), window.registerTreeDataProvider("metheory.review", new CliListProvider(context, ["entry", "extraction-list"], "Extraction review")), window.registerTreeDataProvider("metheory.search", new CliListProvider(context, ["entry", "list"], "Entries")));
  const register = (name: string, handler: () => Promise<void>) => context.subscriptions.push(commands.registerCommand(name, async () => { try { await handler(); } catch (error) { window.showErrorMessage(error instanceof Error ? error.message : "MeTheory command failed"); } }));
  register("metheory.initializeWorkspace", async () => runAiCommand(context, ["workspace", "init"]));
  register("metheory.startNoteFromTheme", async () => { const theme = await window.showInputBox({ prompt: "What do you want to write about?" }); if (theme?.trim()) await createNote(context, theme); });
  register("metheory.syncCurrentFile", async () => runAiCommand(context, ["entry", "sync", activeMarkdown()]));
  register("metheory.syncWorkspace", async () => runAiCommand(context, ["workspace", "sync"]));
  register("metheory.generateTemplate", async () => { const theme = await window.showInputBox({ prompt: "Template theme" }); if (theme) await runAiCommand(context, ["template", "generate", theme]); });
  register("metheory.listTemplates", async () => runAiCommand(context, ["template", "list"]));
  register("metheory.searchEntries", async () => { const query = await window.showInputBox({ prompt: "Search Entries" }); if (query) await runAiCommand(context, ["entry", "search", query]); });
  register("metheory.openStatus", async () => commands.executeCommand("workbench.view.extension.metheory"));
  register("metheory.startService", async () => runAiCommand(context, ["service", "start"]));
  register("metheory.stopService", async () => runAiCommand(context, ["service", "stop"]));
  register("metheory.createBackup", async () => runAiCommand(context, ["backup", "create", "manual"]));
  register("metheory.detectLocalAi", async () => runAiCommand(context, ["ai", "detect"]));
  register("metheory.startLocalAi", async () => runAiCommand(context, ["ai", "start"]));
  register("metheory.stopLocalAi", async () => runAiCommand(context, ["ai", "stop"]));
  register("metheory.testAiConnection", async () => runAiCommand(context, ["ai", "test"]));
  register("metheory.structureCurrentNote", async () => runAiCommand(context, ["entry", "structure", activeMarkdown()]));
  register("metheory.reextractCurrentNote", async () => runAiCommand(context, ["entry", "structure", activeMarkdown()]));
  register("metheory.openExtractionReview", async () => runAiCommand(context, ["entry", "extraction-list"]));
  register("metheory.copyExternalAiPrompt", async () => { const theme = await window.showInputBox({ prompt: "Theme for the external AI prompt" }); if (!theme) return; const result = await cli(context, ["template", "generate", theme]); const output = JSON.parse(result.stdout); if (!output.promptPath) throw new Error("manual_ai_prompt_unavailable"); const prompt = JSON.parse(await readFile(join(root(), output.promptPath), "utf8")).prompt; await env.clipboard.writeText(prompt); window.showInformationMessage("MeTheory: external AI prompt copied."); });
  register("metheory.openPrivacyView", async () => commands.executeCommand("workbench.view.extension.metheory"));
  register("metheory.listPrivacyConsents", async () => runAiCommand(context, ["privacy", "consents", "list"]));
  register("metheory.grantPrivacyConsent", async () => { const templateId = await window.showInputBox({ prompt: "Template ID" }); const fieldKey = await window.showInputBox({ prompt: "Field key" }); const consentType = await window.showQuickPick(["sensitive_field_processing", "external_ai_transfer", "highly_sensitive_downgrade"], { placeHolder: "Consent type" }); if (!templateId || !fieldKey || !consentType) return; const provider = consentType === "external_ai_transfer" ? await window.showInputBox({ prompt: "Provider ID" }) : ""; const destination = consentType === "external_ai_transfer" ? await window.showInputBox({ prompt: "Destination fingerprint" }) : ""; await runAiCommand(context, ["privacy", "consent", "grant", templateId, fieldKey, consentType, provider ?? "", destination ?? "", "--confirm"]); });
  register("metheory.revokePrivacyConsent", async () => { const consentId = await window.showInputBox({ prompt: "Consent ID to revoke" }); if (consentId) await runAiCommand(context, ["privacy", "consent", "revoke", consentId]); });
  register("metheory.planSafeDelete", async () => { const selector = await window.showInputBox({ prompt: "Safe delete selector JSON", value: "{\"fieldKey\":\"\"}" }); if (selector) await runAiCommand(context, ["privacy", "safe-delete", "plan", selector]); });
  register("metheory.executeSafeDelete", async () => { const planId = await window.showInputBox({ prompt: "Safe delete plan ID" }); if (!planId) return; const confirmation = await window.showInputBox({ prompt: "Type the exact confirmation text shown by the plan" }); if (confirmation) await runAiCommand(context, ["privacy", "safe-delete", "execute", planId, confirmation]); });
}
export function deactivate() {}
