import { buildManualTemplatePrompt, parseTemplateDraftJson, validateTemplateDraft, type GenerateTemplateDraftInput, type TemplateDraft } from "../../../packages/templates/src/index.ts";
export type AiHealthStatus={providerId:string;available:boolean;running:boolean;model?:string;errorCode?:string};
export type ExtractEntryValuesInput={content:string;template:any;sourceContentHash:string};
export type ExtractionDecision="suggested"|"review_required"|"unanswered";
export type GeneratedExtractionResult={values:Record<string,unknown>;confidence:Record<string,number>;decisions:Record<string,ExtractionDecision>;sourceContentHash:string;providerId:string;model:string;warnings:string[]};
export interface MeTheoryAiProvider {readonly id:string;readonly displayName:string;readonly capabilities:{templateGeneration:boolean;structuredExtraction:boolean;titleSuggestion:boolean};healthCheck():Promise<AiHealthStatus>;generateTemplateDraft(input:GenerateTemplateDraftInput,signal?:AbortSignal):Promise<TemplateDraft>;extractEntryValues(input:ExtractEntryValuesInput,signal?:AbortSignal):Promise<GeneratedExtractionResult>;suggestTitle?(input:{theme:string;primaryTemplate?:any},signal?:AbortSignal):Promise<{title:string;provider:string}>;}
export class AiProviderError extends Error {readonly code:string;constructor(code:string){super(code);this.code=code;}}
function parseJson(text:string){try{return JSON.parse(text.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim());}catch{throw new AiProviderError("invalid_json");}}
function extractionPrompt(input:ExtractEntryValuesInput){return JSON.stringify({instruction:"Return JSON only. Extract explicit facts only. Do not diagnose or infer missing values.",content:input.content,fields:input.template.fields},null,2);}
function extractionResult(raw:any,input:ExtractEntryValuesInput,id:string,model:string):GeneratedExtractionResult{if(!raw||typeof raw!=="object")throw new AiProviderError("invalid_schema");const values:Record<string,unknown>={};const confidence:Record<string,number>={};const decisions:Record<string,ExtractionDecision>={};for(const field of input.template.fields){if(field.fieldKey in raw){values[field.fieldKey]=raw[field.fieldKey];const score=typeof raw._confidence?.[field.fieldKey]==="number"?Math.max(0,Math.min(1,raw._confidence[field.fieldKey])):0.5;confidence[field.fieldKey]=score;decisions[field.fieldKey]=score>=0.85?"suggested":score>=0.6?"review_required":"unanswered";}}return {values,confidence,decisions,sourceContentHash:input.sourceContentHash,providerId:id,model,warnings:[]};}
export class DisabledAiProvider implements MeTheoryAiProvider {readonly id:string="disabled";readonly displayName:string="AI disabled";readonly capabilities:MeTheoryAiProvider["capabilities"]={templateGeneration:false,structuredExtraction:false,titleSuggestion:false};async healthCheck():Promise<AiHealthStatus>{return {providerId:this.id,available:false,running:false,errorCode:"disabled"};}async generateTemplateDraft(_input:GenerateTemplateDraftInput,_signal?:AbortSignal):Promise<TemplateDraft>{throw new AiProviderError("disabled");}async extractEntryValues(_input:ExtractEntryValuesInput,_signal?:AbortSignal):Promise<GeneratedExtractionResult>{throw new AiProviderError("disabled");}}
export class ManualExternalAiProvider implements MeTheoryAiProvider {readonly id:string="manual";readonly displayName:string="Manual external AI";readonly capabilities:MeTheoryAiProvider["capabilities"]={templateGeneration:true,structuredExtraction:true,titleSuggestion:false};promptForTemplate(input:GenerateTemplateDraftInput){return buildManualTemplatePrompt(input);}parseTemplate(text:string){return parseTemplateDraftJson(text);}promptForExtraction(input:ExtractEntryValuesInput){return extractionPrompt(input);}async healthCheck():Promise<AiHealthStatus>{return {providerId:this.id,available:true,running:false};}async generateTemplateDraft(_input:GenerateTemplateDraftInput,_signal?:AbortSignal):Promise<TemplateDraft>{throw new AiProviderError("manual_input_required");}async extractEntryValues(_input:ExtractEntryValuesInput,_signal?:AbortSignal):Promise<GeneratedExtractionResult>{throw new AiProviderError("manual_input_required");}}
export class MockAiProvider implements MeTheoryAiProvider {readonly id="mock";readonly displayName="Mock local AI";readonly capabilities={templateGeneration:true,structuredExtraction:true,titleSuggestion:true};async healthCheck(){return {providerId:this.id,available:true,running:true,model:"mock"};}async generateTemplateDraft(input:GenerateTemplateDraftInput){return validateTemplateDraft({theme:input.theme,name:`${input.theme}の記録`,description:"Mock draft",fields:[{fieldKey:"summary",label:"要約",inputType:"text",valueType:"text",required:false,displayOrder:1,sensitivity:"normal",reason:"明示内容の要約"}]});}async extractEntryValues(input:ExtractEntryValuesInput){return extractionResult({},input,this.id,"mock");}async suggestTitle(input:{theme:string}){return {title:input.theme,provider:this.id};}}
export class OpenAICompatibleLocalProvider implements MeTheoryAiProvider {readonly id:string="openai-compatible-local";readonly displayName:string="OpenAI-compatible local AI";readonly capabilities:MeTheoryAiProvider["capabilities"]={templateGeneration:true,structuredExtraction:true,titleSuggestion:true};private readonly config:{baseUrl:string;model:string;apiKey?:string};constructor(config:{baseUrl:string;model:string;apiKey?:string}){const hostname=new URL(config.baseUrl).hostname;if(!["127.0.0.1","localhost","::1"].includes(hostname))throw new AiProviderError("remote_local_ai_endpoint");this.config=config;}private async chat(prompt:string,signal?:AbortSignal){const r=await fetch(`${this.config.baseUrl.replace(/\/$/,"")}/chat/completions`,{method:"POST",signal,headers:{"content-type":"application/json",...(this.config.apiKey?{authorization:`Bearer ${this.config.apiKey}`}:{})},body:JSON.stringify({model:this.config.model,messages:[{role:"user",content:prompt}],temperature:0})});if(!r.ok)throw new AiProviderError("request_failed");const p=await r.json() as any;const text=p.choices?.[0]?.message?.content;if(typeof text!=="string")throw new AiProviderError("invalid_response");return text;}async healthCheck():Promise<AiHealthStatus>{try{const r=await fetch(`${this.config.baseUrl.replace(/\/v1\/?$/,"")}/models`);return {providerId:this.id,available:r.ok,running:r.ok,model:this.config.model,errorCode:r.ok?undefined:"unavailable"};}catch{return {providerId:this.id,available:false,running:false,model:this.config.model,errorCode:"unavailable"};}}async generateTemplateDraft(input:GenerateTemplateDraftInput,signal?:AbortSignal):Promise<TemplateDraft>{return validateTemplateDraft(parseTemplateDraftJson(await this.chat(buildManualTemplatePrompt(input),signal)));}async extractEntryValues(input:ExtractEntryValuesInput,signal?:AbortSignal):Promise<GeneratedExtractionResult>{return extractionResult(parseJson(await this.chat(extractionPrompt(input),signal)),input,this.id,this.config.model);}async suggestTitle(input:{theme:string;primaryTemplate?:any},signal?:AbortSignal):Promise<{title:string;provider:string}>{const p=parseJson(await this.chat(`Return JSON only: {"title":"short note title"}. Theme: ${input.theme}`,signal));if(typeof p.title!=="string")throw new AiProviderError("invalid_schema");return {title:p.title.trim(),provider:this.id};}}
export class OllamaAiProvider extends OpenAICompatibleLocalProvider {readonly id:string="ollama";readonly displayName:string="Ollama";constructor(model:string,baseUrl="http://127.0.0.1:11434/v1"){super({baseUrl,model});}}
export type AiProviderFactoryConfig={provider:"ollama"|"openai-compatible-local"|"mock"|"manual"|"disabled";model?:string;baseUrl?:string};
export function createAiProvider(config:AiProviderFactoryConfig):MeTheoryAiProvider{if(config.provider==="ollama")return new OllamaAiProvider(config.model??"llama3.2",config.baseUrl);if(config.provider==="openai-compatible-local")return new OpenAICompatibleLocalProvider({baseUrl:config.baseUrl??"http://127.0.0.1:1234/v1",model:config.model??"local-model"});if(config.provider==="mock")return new MockAiProvider();if(config.provider==="manual")return new ManualExternalAiProvider();return new DisabledAiProvider();}
