type Row = Record<string, unknown>;
type Statement = { all(...args: unknown[]): unknown[]; get(...args: unknown[]): unknown };
type SqlDb = { prepare(sql: string): Statement };

export type AiRequestContext = { userId: string; clientId: string; clientType: string; purpose: string };
export type AiParameterRequest = AiRequestContext & { parameterId: string; startAt?: string; endAt?: string };
export type AiAggregateRequest = AiRequestContext & { parameterIds: string[]; startAt: string; endAt: string; groupBy?: 'time_period' | 'day_of_week' | 'day_type' | 'activity_category' | 'is_alone' };
const GROUP_BY = new Set(['time_period', 'day_of_week', 'day_type', 'activity_category', 'is_alone']);

function scalar(row: Row): unknown { if (Number(row.is_missing) === 1) return null; if (row.boolean_value !== null && row.boolean_value !== undefined) return Boolean(row.boolean_value); if (row.integer_value !== null && row.integer_value !== undefined) return Number(row.integer_value); if (row.number_value !== null && row.number_value !== undefined) return Number(row.number_value); return null; }
function groupScalar(row: Row | undefined): string { if (!row || Number(row.is_missing) === 1) return 'missing'; const value = scalar(row); if (value !== null) return String(value); if (row.text_value !== null && row.text_value !== undefined) return String(row.text_value); if (row.datetime_value !== null && row.datetime_value !== undefined) return String(row.datetime_value); try { const parsed = JSON.parse(String(row.json_value)); return typeof parsed === 'string' || typeof parsed === 'number' || typeof parsed === 'boolean' ? String(parsed) : 'other'; } catch { return 'other'; } }
function safePeriod(input: { startAt?: string; endAt?: string }) { const end = new Date(input.endAt ?? new Date().toISOString()); const start = new Date(input.startAt ?? new Date(end.getTime() - 30 * 86400000).toISOString()); if (!Number.isFinite(start.getTime()) || !Number.isFinite(end.getTime()) || start >= end) throw new Error('invalid_period'); if (end.getTime() - start.getTime() > 90 * 86400000) throw new Error('period_too_long'); return { startAt: start.toISOString(), endAt: end.toISOString() }; }
function metric(parameterId: string, values: unknown[]) { const numeric = values.filter((value): value is number => typeof value === 'number' && Number.isFinite(value)); return { parameterId, sampleCount: values.filter((value) => value !== null).length, missingCount: values.filter((value) => value === null).length, mean: numeric.length ? numeric.reduce((sum, value) => sum + value, 0) / numeric.length : null, minimum: numeric.length ? Math.min(...numeric) : null, maximum: numeric.length ? Math.max(...numeric) : null }; }

export function createAiQueryService(db: SqlDb) {
  const readableJoin = "JOIN parameter_ai_access_policies policy ON policy.parameter_id=pd.id JOIN user_parameter_settings settings ON settings.parameter_id=pd.id AND settings.user_id=? LEFT JOIN parameter_governance governance ON governance.parameter_id=pd.id";
  const readableStatus = "pd.is_active=1 AND COALESCE(governance.status,'active')='active' AND policy.external_ai_allowed=1 AND policy.access_level<>'none' AND settings.external_ai_enabled=1 AND settings.cloud_sync_enabled=1";
  function listReadableParameters(input: AiRequestContext) { const rows = db.prepare(`SELECT pd.id,pd.name_ja,pd.description_ja,pd.value_type,pd.unit,pd.parameter_layer,pd.sensitivity,pd.definition_version,policy.access_level,policy.maximum_reference_days,COUNT(CASE WHEN pv.is_missing=0 THEN 1 END) AS sample_count,COUNT(CASE WHEN pv.is_missing=1 THEN 1 END) AS missing_count,MIN(pv.observed_at) AS first_observed_at,MAX(pv.observed_at) AS last_observed_at FROM parameter_definitions pd ${readableJoin} LEFT JOIN observation_episodes oe ON oe.user_id=settings.user_id LEFT JOIN parameter_values pv ON pv.episode_id=oe.id AND pv.parameter_id=pd.id WHERE ${readableStatus} GROUP BY pd.id ORDER BY pd.id`).all(input.userId) as Row[]; return { items: rows.map(parameterSummary), deniedParameterIds: [] }; }
  function getReadableParameter(input: AiParameterRequest) { const period = safePeriod(input); const row = db.prepare(`SELECT pd.id,pd.name_ja,pd.description_ja,pd.value_type,pd.unit,pd.parameter_layer,pd.sensitivity,pd.definition_version,policy.access_level,policy.maximum_reference_days,COUNT(CASE WHEN pv.is_missing=0 THEN 1 END) AS sample_count,COUNT(CASE WHEN pv.is_missing=1 THEN 1 END) AS missing_count,MIN(pv.observed_at) AS first_observed_at,MAX(pv.observed_at) AS last_observed_at FROM parameter_definitions pd ${readableJoin} LEFT JOIN observation_episodes oe ON oe.user_id=settings.user_id LEFT JOIN parameter_values pv ON pv.episode_id=oe.id AND pv.parameter_id=pd.id AND pv.observed_at>=? AND pv.observed_at<? WHERE ${readableStatus} AND pd.id=? GROUP BY pd.id`).get(input.userId, period.startAt, period.endAt, input.parameterId) as Row | undefined; if (!row) return { parameterId: input.parameterId, accessLevel: 'none', denied: true }; const maximumDays = Number(row.maximum_reference_days ?? 0); if (maximumDays > 0 && new Date(period.endAt).getTime() - new Date(period.startAt).getTime() > maximumDays * 86400000) return { parameterId: input.parameterId, accessLevel: 'none', denied: true, reason: 'reference_period_not_allowed' }; return parameterSummary(row); }
  function queryAggregates(input: AiAggregateRequest) { const period = safePeriod(input); if (!input.parameterIds.length || input.parameterIds.length > 10) throw new Error('ai_scope_required'); if (input.groupBy && !GROUP_BY.has(input.groupBy)) throw new Error('invalid_group_by'); if (input.groupBy && 'denied' in getReadableParameter({ ...input, parameterId: input.groupBy, ...period })) throw new Error('group_by_not_allowed'); const items: Row[] = []; const denied: string[] = []; for (const parameterId of input.parameterIds) { const access = getReadableParameter({ ...input, parameterId, ...period }); if ('denied' in access) { denied.push(parameterId); continue; } const rows = db.prepare(`SELECT pv.*,oe.id AS episode_id FROM parameter_values pv JOIN observation_episodes oe ON oe.id=pv.episode_id JOIN parameter_definitions pd ON pd.id=pv.parameter_id ${readableJoin} WHERE ${readableStatus} AND pd.id=? AND oe.user_id=? AND pv.observed_at>=? AND pv.observed_at<?`).all(input.userId, parameterId, input.userId, period.startAt, period.endAt) as Row[]; const values = rows.map(scalar); const aggregate: Row = metric(parameterId, values); if (input.groupBy) { const buckets = new Map<string, unknown[]>(); for (const row of rows) { const groupRow = db.prepare('SELECT * FROM parameter_values WHERE episode_id=? AND parameter_id=? LIMIT 1').get(row.episode_id, input.groupBy) as Row | undefined; const key = groupScalar(groupRow); (buckets.get(key) ?? (buckets.set(key, []), buckets.get(key)!)).push(scalar(row)); } aggregate.groupBy = input.groupBy; aggregate.groups = [...buckets.entries()].map(([key, bucket]) => ({ key, ...metric(parameterId, bucket) })); } items.push(aggregate); } return { accessLevel: 'aggregate_only', groups: items, deniedParameterIds: denied, period }; }
  function getReadableHypotheses(input: AiRequestContext) { const rows = db.prepare("SELECT id,statement,state,spec_version,created_at FROM hypotheses WHERE user_id=? AND state IN ('tracking','paused') ORDER BY created_at DESC").all(input.userId) as Row[]; return { items: rows.map((row) => ({ id: String(row.id), statement: String(row.statement), state: String(row.state), version: String(row.spec_version ?? '1'), createdAt: String(row.created_at) })) }; }
  function getReadableEvidence(input: AiRequestContext & { hypothesisId: string }) { const row = db.prepare('SELECT id, result, cohort_metrics_json, observed_effect, data_quality_json, evaluated_at, window_start, window_end, evaluator_version FROM hypothesis_evaluations WHERE hypothesis_id=? ORDER BY evaluated_at DESC LIMIT 1').get(input.hypothesisId) as Row | undefined; if (!row) return { hypothesisId: input.hypothesisId, evaluation: null, items: [] }; let metrics: unknown[] = []; try { const parsed = JSON.parse(String(row.cohort_metrics_json ?? '[]')); metrics = Array.isArray(parsed) ? parsed.map((item: Row) => ({ key: item.key, metricValue: item.metricValue, eligibleSamples: item.eligibleSamples, missingSamples: item.missingSamples })) : []; } catch { metrics = []; } return { hypothesisId: input.hypothesisId, evaluation: { result: row.result, observedEffect: row.observed_effect, dataQuality: row.data_quality_json, evaluatedAt: row.evaluated_at, period: { startAt: row.window_start, endAt: row.window_end }, evaluatorVersion: row.evaluator_version }, items: metrics }; }
  function getReadableSelfModel(input: AiRequestContext) { if (process.env.METHEORY_AI_SELF_MODEL_ALLOWED !== 'true') return { accessLevel: 'none', items: [] }; const rows = db.prepare('SELECT statement,created_at FROM self_beliefs WHERE user_id=? ORDER BY created_at DESC LIMIT 10').all(input.userId) as Row[]; return { accessLevel: 'explicit_self_model_consent', items: rows.map((row) => ({ statement: String(row.statement), createdAt: String(row.created_at) })) }; }
  function createSnapshot(input: AiAggregateRequest) { const aggregate = queryAggregates(input); return { generatedAt: new Date().toISOString(), accessLevel: 'aggregate_only', hypotheses: getReadableHypotheses(input).items, selfModel: getReadableSelfModel(input), aggregates: aggregate.groups, deniedParameterIds: aggregate.deniedParameterIds, period: aggregate.period }; }
  return { listReadableParameters, getReadableParameter, queryAggregates, getReadableHypotheses, getReadableEvidence, getReadableSelfModel, createSnapshot };
}

function parameterSummary(row: Row) { return { parameterId: String(row.id), nameJa: String(row.name_ja), descriptionJa: String(row.description_ja), valueType: String(row.value_type), unit: row.unit === null ? null : String(row.unit), parameterLayer: String(row.parameter_layer), sensitivity: String(row.sensitivity), accessLevel: String(row.access_level), definitionVersion: String(row.definition_version), sampleCount: Number(row.sample_count ?? 0), missingCount: Number(row.missing_count ?? 0), missingRate: Number(row.sample_count ?? 0) + Number(row.missing_count ?? 0) ? Number(row.missing_count ?? 0) / (Number(row.sample_count ?? 0) + Number(row.missing_count ?? 0)) : 0, firstObservedAt: row.first_observed_at ?? null, lastObservedAt: row.last_observed_at ?? null, maximumReferenceDays: row.maximum_reference_days ?? null }; }
