import type { DatabaseSync } from "node:sqlite";
import { randomUUID } from "node:crypto";
import { confirmationText, destinationFingerprint, newConsentId, suggestFieldPrivacy, type PrivacyConsent, type SafeDeletePlan, type SafeDeleteSelector, type SensitivityLevel } from "../../../packages/privacy/src/index.ts";

const now = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}_${randomUUID().replaceAll("-", "")}`;
type ConsentInput = Omit<PrivacyConsent, "id" | "createdAt" | "updatedAt" | "revokedAt"> & { workspaceId?: string | null; providerId?: string | null; destinationFingerprint?: string | null };

export class SqlitePrivacyRepository {
  private readonly db: DatabaseSync;
  constructor(db: DatabaseSync) { this.db = db; }
  private audit(userId: string, eventType: string, dataCategory: string, affectedCount: number) { this.db.prepare("INSERT INTO privacy_audit_events(id,user_id,event_type,data_category,affected_count,occurred_at) VALUES(?,?,?,?,?,?)").run(id("privacy_audit"), userId, eventType, dataCategory, affectedCount, now()); }
  status(userId: string) { const fields = this.db.prepare("SELECT COUNT(*) AS count FROM entry_template_fields f JOIN entry_template_versions v ON v.id=f.template_version_id JOIN entry_templates t ON t.id=v.template_id WHERE t.user_id=? AND f.sensitivity_level IN ('sensitive','highly_sensitive')").get(userId) as { count: number }; const consents = this.db.prepare("SELECT COUNT(*) AS count FROM privacy_consents WHERE user_id=? AND revoked_at IS NULL").get(userId) as { count: number }; const plans = this.db.prepare("SELECT COUNT(*) AS count FROM privacy_safe_delete_plans WHERE user_id=? AND status='planned'").get(userId) as { count: number }; return { sensitiveFieldCount: Number(fields.count), activeConsentCount: Number(consents.count), pendingSafeDeletePlans: Number(plans.count) }; }
  listConsents(userId: string, includeRevoked = false): PrivacyConsent[] { const where = includeRevoked ? "" : " AND revoked_at IS NULL"; return this.db.prepare(`SELECT * FROM privacy_consents WHERE user_id=?${where} ORDER BY created_at DESC`).all(userId) as PrivacyConsent[]; }
  listAuditEvents(userId: string, limit = 100) { return this.db.prepare("SELECT event_type,data_category,affected_count,occurred_at FROM privacy_audit_events WHERE user_id=? ORDER BY occurred_at DESC LIMIT ?").all(userId, Math.max(1, Math.min(500, limit))); }
  listSafeDeletePlans(userId: string) { return this.db.prepare("SELECT id,status,plan_json,created_at,executed_at FROM privacy_safe_delete_plans WHERE user_id=? ORDER BY created_at DESC").all(userId).map((row: any) => ({ id: row.id, status: row.status, ...(JSON.parse(row.plan_json) as object), createdAt: row.created_at, executedAt: row.executed_at })); }
  getSafeDeletePlan(userId: string, planId: string) { const row = this.db.prepare("SELECT plan_json,status,created_at,executed_at FROM privacy_safe_delete_plans WHERE user_id=? AND id=?").get(userId, planId) as any; if (!row) throw new Error("safe_delete_plan_not_found"); return { ...(JSON.parse(row.plan_json) as object), status: row.status, executedAt: row.executed_at }; }
  getConsent(userId: string, consentId: string): PrivacyConsent | null { return (this.db.prepare("SELECT * FROM privacy_consents WHERE user_id=? AND id=?").get(userId, consentId) as PrivacyConsent | undefined) ?? null; }
  grantConsent(input: ConsentInput): PrivacyConsent { if (!input.fieldKey.trim() || !["sensitive_field_processing", "external_ai_transfer", "highly_sensitive_downgrade"].includes(input.consentType) || !["field", "single_value"].includes(input.scope)) throw new Error("privacy_consent_invalid"); if (input.consentType === "external_ai_transfer" && (!input.providerId || !input.destinationFingerprint)) throw new Error("external_ai_destination_required"); const timestamp = now(); const consent: PrivacyConsent = { id: newConsentId(), ...input, createdAt: timestamp, updatedAt: timestamp, revokedAt: null }; this.db.prepare("INSERT INTO privacy_consents(id,user_id,workspace_id,template_id,template_version_id,field_key,consent_type,provider_id,destination_fingerprint,scope,granted_at,revoked_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(consent.id, consent.userId, consent.workspaceId ?? null, consent.templateId ?? null, consent.templateVersionId ?? null, consent.fieldKey, consent.consentType, consent.providerId ?? null, consent.destinationFingerprint ?? null, consent.scope, consent.grantedAt, null, timestamp, timestamp); this.audit(consent.userId, "consent_granted", consent.consentType, 1); return consent; }
  revokeConsent(userId: string, consentId: string): PrivacyConsent { const timestamp = now(); const result = this.db.prepare("UPDATE privacy_consents SET revoked_at=?,updated_at=? WHERE user_id=? AND id=? AND revoked_at IS NULL").run(timestamp, timestamp, userId, consentId); if (!result.changes) throw new Error("consent_not_found_or_revoked"); this.audit(userId, "consent_revoked", "privacy_consent", 1); return this.getConsent(userId, consentId) as PrivacyConsent; }
  hasActiveConsent(userId: string, input: { templateId?: string; templateVersionId?: string; fieldKey: string; consentType: string; providerId?: string; destinationFingerprint?: string }): boolean { const rows = this.db.prepare("SELECT * FROM privacy_consents WHERE user_id=? AND field_key=? AND consent_type=? AND revoked_at IS NULL ORDER BY granted_at DESC").all(userId, input.fieldKey, input.consentType) as Array<Record<string, unknown>>; return rows.some(row => (input.templateId === undefined || row.template_id === input.templateId) && (input.templateVersionId === undefined || row.template_version_id === input.templateVersionId) && (input.providerId === undefined || row.provider_id === input.providerId) && (input.destinationFingerprint === undefined || row.destination_fingerprint === input.destinationFingerprint)); }
  externalAiDecision(userId: string, input: { templateId?: string; templateVersionId?: string; fieldKey: string; providerId: string; host: string; connectionType?: string; profileId?: string }) { const fingerprint = destinationFingerprint(input); const allowed = this.hasActiveConsent(userId, { ...input, consentType: "external_ai_transfer", destinationFingerprint: fingerprint }); return { allowed, destinationFingerprint: fingerprint, reason: allowed ? "consent_active" : "external_ai_consent_required" }; }
  listFields(userId: string, templateId?: string) { const clause = templateId ? " AND t.id=?" : ""; const args = templateId ? [userId, templateId] : [userId]; const rows = this.db.prepare(`SELECT t.id AS template_id,t.name AS template_name,v.id AS template_version_id,v.version_number,f.field_key,f.label,f.description,f.sensitivity,f.sensitivity_level,f.classification_source,f.prohibited_secret_risk FROM entry_templates t JOIN entry_template_versions v ON v.template_id=t.id JOIN entry_template_fields f ON f.template_version_id=v.id WHERE t.user_id=?${clause} ORDER BY t.updated_at DESC,v.version_number DESC,f.display_order`).all(...args) as Array<Record<string, unknown>>; return rows.map(row => ({ ...row, privacySuggestion: suggestFieldPrivacy({ fieldKey: String(row.field_key), label: String(row.label), description: String(row.description ?? ""), sensitivity: String(row.sensitivity) }) })); }
  fieldDetail(userId: string, templateId: string, fieldKey: string) { return this.db.prepare("SELECT t.id AS template_id,t.name AS template_name,v.id AS template_version_id,v.version_number,f.* FROM entry_templates t JOIN entry_template_versions v ON v.template_id=t.id JOIN entry_template_fields f ON f.template_version_id=v.id WHERE t.user_id=? AND t.id=? AND f.field_key=? ORDER BY v.version_number DESC").all(userId, templateId, fieldKey); }
  private matchingWhere(selector: SafeDeleteSelector) { const clauses = ["e.user_id=?"]; const args: Array<string> = [selector.userId]; if (selector.templateId) { clauses.push("t.id=?"); args.push(selector.templateId); } if (selector.templateVersionId) { clauses.push("v.id=?"); args.push(selector.templateVersionId); } if (selector.fieldKey) { clauses.push("f.field_key=?"); args.push(selector.fieldKey); } if (selector.entryId) { clauses.push("e.id=?"); args.push(selector.entryId); } return { clauses: clauses.join(" AND "), args }; }
  private resolveSelector(selector: SafeDeleteSelector): SafeDeleteSelector { if (!selector.consentId) return selector; const row = this.db.prepare("SELECT template_id,template_version_id,field_key FROM privacy_consents WHERE id=? AND user_id=?").get(selector.consentId, selector.userId) as { template_id?: string; template_version_id?: string; field_key: string } | undefined; if (!row) throw new Error("consent_not_found"); return { ...selector, templateId: selector.templateId ?? row.template_id, templateVersionId: selector.templateVersionId ?? row.template_version_id, fieldKey: selector.fieldKey ?? row.field_key }; }
  createSafeDeletePlan(selector: SafeDeleteSelector, markdownFiles: Array<{ path: string; matches: number; preview?: string }>, backupCount: number, extractionCandidateCount = 0): SafeDeletePlan {
    const resolved = this.resolveSelector(selector); const { clauses, args } = this.matchingWhere(resolved);
    const valueJoin = `FROM entry_field_values ev JOIN entries e ON e.id=ev.entry_id JOIN entry_template_fields f ON f.id=ev.template_field_id JOIN entry_template_versions v ON v.id=ev.template_version_id JOIN entry_templates t ON t.id=v.template_id WHERE ${clauses}`;
    const current = this.db.prepare(`SELECT COUNT(*) AS count ${valueJoin} AND ev.is_missing=0`).get(...args) as { count: number };
    const history = this.db.prepare(`SELECT COUNT(*) AS count ${valueJoin}`).get(...args) as { count: number };
    const affectedEntries = this.db.prepare(`SELECT COUNT(DISTINCT e.id) AS count ${valueJoin}`).get(...args) as { count: number };
    const overrides = this.db.prepare(`SELECT COUNT(*) AS count FROM privacy_value_overrides o JOIN entries e ON e.id=o.entry_id JOIN entry_template_versions v ON v.id=o.template_version_id JOIN entry_templates t ON t.id=v.template_id WHERE e.user_id=?${resolved.templateId ? " AND t.id=?" : ""}${resolved.templateVersionId ? " AND v.id=?" : ""}${resolved.fieldKey ? " AND o.field_key=?" : ""}${resolved.entryId ? " AND e.id=?" : ""}`).get(resolved.userId, ...(resolved.templateId ? [resolved.templateId] : []), ...(resolved.templateVersionId ? [resolved.templateVersionId] : []), ...(resolved.fieldKey ? [resolved.fieldKey] : []), ...(resolved.entryId ? [resolved.entryId] : [])) as { count: number };
    const corrections = this.db.prepare(`SELECT COUNT(*) AS count FROM privacy_extraction_corrections WHERE user_id=?${resolved.templateId ? " AND template_id=?" : ""}${resolved.templateVersionId ? " AND template_version_id=?" : ""}${resolved.fieldKey ? " AND field_key=?" : ""}`).get(resolved.userId, ...(resolved.templateId ? [resolved.templateId] : []), ...(resolved.templateVersionId ? [resolved.templateVersionId] : []), ...(resolved.fieldKey ? [resolved.fieldKey] : [])) as { count: number };
    const plan: SafeDeletePlan = { id: id("safe_delete"), selector: resolved, affectedCurrentValues: Number(current.count), affectedHistoryValues: Number(history.count), affectedValueOverrides: Number(overrides.count), affectedCorrections: Number(corrections.count), affectedExtractionCandidates: extractionCandidateCount, affectedLearningExamples: 0, affectedBackups: backupCount, affectedMarkdownFiles: markdownFiles.map(item => ({ ...item, action: "review_only" as const })), requiredConfirmationText: confirmationText(Number(current.count) + Number(history.count) + Number(overrides.count) + Number(corrections.count) + Number(affectedEntries.count) + extractionCandidateCount), createdAt: now() };
    this.db.prepare("INSERT INTO privacy_safe_delete_plans(id,user_id,selector_json,plan_json,status,created_at) VALUES(?,?,?,?,?,?)").run(plan.id, resolved.userId, JSON.stringify(resolved), JSON.stringify(plan), "planned", plan.createdAt); return plan;
  }
  executeSafeDelete(userId: string, planId: string, confirmation: string): { planId: string; selector: SafeDeleteSelector; deletedValues: number; deletedOverrides: number; deletedCorrections: number; deletedSearchDocuments: number } {
    const row = this.db.prepare("SELECT plan_json,status FROM privacy_safe_delete_plans WHERE id=? AND user_id=?").get(planId, userId) as { plan_json: string; status: string } | undefined;
    if (!row || row.status !== "planned") throw new Error("safe_delete_plan_not_found");
    const plan = JSON.parse(row.plan_json) as SafeDeletePlan; if (confirmation !== plan.requiredConfirmationText) throw new Error("safe_delete_confirmation_mismatch");
    const { clauses, args } = this.matchingWhere(plan.selector); this.db.exec("BEGIN IMMEDIATE");
    try {
      const joins = `FROM entry_field_values ev JOIN entries e ON e.id=ev.entry_id JOIN entry_template_fields f ON f.id=ev.template_field_id JOIN entry_template_versions v ON v.id=ev.template_version_id JOIN entry_templates t ON t.id=v.template_id WHERE ${clauses}`;
      const entries = this.db.prepare(`SELECT DISTINCT e.id ${joins}`).all(...args) as Array<{ id: string }>;
      const deleted = this.db.prepare(`DELETE FROM entry_field_values WHERE id IN (SELECT ev.id ${joins})`).run(...args);
      const overrideArgs = [...args, ...(plan.selector.fieldKey ? [plan.selector.fieldKey] : [])];
      const deletedOverrides = this.db.prepare(`DELETE FROM privacy_value_overrides WHERE entry_id IN (SELECT DISTINCT e.id ${joins})${plan.selector.fieldKey ? " AND field_key=?" : ""}`).run(...overrideArgs);
      const correctionArgs = [userId, ...(plan.selector.templateId ? [plan.selector.templateId] : []), ...(plan.selector.templateVersionId ? [plan.selector.templateVersionId] : []), ...(plan.selector.fieldKey ? [plan.selector.fieldKey] : [])];
      const deletedCorrections = this.db.prepare(`DELETE FROM privacy_extraction_corrections WHERE user_id=?${plan.selector.templateId ? " AND template_id=?" : ""}${plan.selector.templateVersionId ? " AND template_version_id=?" : ""}${plan.selector.fieldKey ? " AND field_key=?" : ""}`).run(...correctionArgs);
      let searchDocuments = 0; for (const entry of entries) searchDocuments += Number(this.db.prepare("DELETE FROM search_documents WHERE user_id=? AND source_kind='entry' AND source_id=?").run(userId, entry.id).changes);
      this.db.prepare("UPDATE privacy_safe_delete_plans SET status='executed',executed_at=? WHERE id=? AND user_id=?").run(now(), planId, userId);
      this.audit(userId, "safe_delete_executed", "privacy_data", Number(deleted.changes) + Number(deletedOverrides.changes) + Number(deletedCorrections.changes)); this.db.exec("COMMIT");
      return { planId, selector: plan.selector, deletedValues: Number(deleted.changes), deletedOverrides: Number(deletedOverrides.changes), deletedCorrections: Number(deletedCorrections.changes), deletedSearchDocuments: searchDocuments };
    } catch (error) { this.db.exec("ROLLBACK"); throw error; }
  }
  static fingerprint(input: { providerId: string; host: string; connectionType?: string; profileId?: string }) { return destinationFingerprint(input); }
}
