import type { DatabaseSync } from "node:sqlite";
import { newTemplateId, validateTemplateDraft, valueForField, type GenerateTemplateDraftInput, type TemplateDraft } from "../../../packages/templates/src/index.ts";
import { randomUUID } from "node:crypto";
const now = () => new Date().toISOString(); const id = (p: string) => `${p}_${randomUUID().replaceAll("-", "")}`;
export class SqliteTemplateRepository {
  private readonly db: DatabaseSync;
  constructor(db: DatabaseSync) { this.db = db; }
  list(userId: string) { return this.db.prepare("SELECT t.*, v.id AS version_id, v.version_number, (SELECT COUNT(*) FROM entry_template_fields f WHERE f.template_version_id=v.id) AS field_count FROM entry_templates t JOIN entry_template_versions v ON v.id=t.current_version_id WHERE t.user_id=? AND t.archived_at IS NULL ORDER BY t.updated_at DESC").all(userId); }
  detail(userId: string, templateId: string) { const t = this.db.prepare("SELECT * FROM entry_templates WHERE user_id=? AND id=?").get(userId, templateId) as Record<string, unknown> | undefined; if (!t) throw new Error("template_not_found"); const v = this.db.prepare("SELECT * FROM entry_template_versions WHERE id=?").get(String(t.current_version_id)) as Record<string, unknown>; const fields = this.db.prepare("SELECT * FROM entry_template_fields WHERE template_version_id=? ORDER BY display_order").all(String(v.id)).map((r: any) => ({ ...r, options: JSON.parse(r.options_json) })); return { ...t, currentVersion: { ...v, fields } }; }
  save(userId: string, input: any) { if (input.approved !== true) throw new Error("template_approval_required"); const draft = validateTemplateDraft({ theme: input.theme, name: input.name, description: input.description, fields: input.fields }); const ts = now(); const templateId = newTemplateId(); const versionId = id("template_version"); this.db.exec("BEGIN IMMEDIATE"); try { this.db.prepare("INSERT INTO entry_templates(id,user_id,name,theme,description,current_version_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").run(templateId,userId,draft.name,draft.theme,draft.description,versionId,ts,ts); this.insertVersion(templateId,versionId,draft,input,1,ts); this.db.exec("COMMIT"); } catch(e){this.db.exec("ROLLBACK");throw e;} return this.detail(userId,templateId); }
  private insertVersion(templateId: string, versionId: string, draft: TemplateDraft, input: any, version: number, ts: string) { this.db.prepare("INSERT INTO entry_template_versions(id,template_id,version_number,generation_source,ai_provider,ai_model,prompt_version,created_at) VALUES(?,?,?,?,?,?,?,?)").run(...([versionId,templateId,version,input.generationSource ?? "user",input.aiProvider ?? null,input.aiModel ?? null,input.promptVersion ?? "template-v1",ts] as any[])); for(const f of draft.fields) this.db.prepare("INSERT INTO entry_template_fields(id,template_version_id,field_key,label,description,input_type,value_type,required,display_order,options_json,minimum,maximum,unit,sensitivity,reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(...([id("template_field"),versionId,f.fieldKey,f.label,f.description ?? "",f.inputType,f.valueType,f.required?1:0,f.displayOrder,JSON.stringify(f.options ?? []),f.minimum ?? null,f.maximum ?? null,f.unit ?? null,f.sensitivity,f.reason] as any[])); }
  createEntry(userId: string, templateId: string, input: any) { const d=this.detail(userId,templateId); const t=d as any; if(t.archived_at) throw new Error("template_archived"); const entryId=id("entry"), ts=now(); const fields=t.currentVersion.fields; this.db.exec("BEGIN IMMEDIATE"); try { this.db.prepare("INSERT INTO entries(id,user_id,template_id,template_version_id,title,body,recorded_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").run(entryId,userId,templateId,t.currentVersion.id,input.title ?? t.name,input.body ?? "",input.recordedAt ?? ts,ts,ts); for(const f of fields){const value=valueForField(f,input.values?.[f.field_key]) as any; const missing=value===null?1:0; this.db.prepare("INSERT INTO entry_field_values(id,entry_id,template_version_id,template_field_id,text_value,integer_value,number_value,boolean_value,json_value,date_value,datetime_value,duration_seconds,is_missing,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id("entry_value"),entryId,t.currentVersion.id,f.id,typeof value === "string" ? value:null,typeof value === "number" && Number.isInteger(value)?value:null,typeof value === "number" && !Number.isInteger(value)?value:null,typeof value === "boolean"?(value?1:0):null,Array.isArray(value)?JSON.stringify(value):null,f.value_type === "date"?value:null,f.value_type === "datetime"?value:null,f.value_type === "duration_seconds"?value:null,missing,ts); } this.db.exec("COMMIT"); return { id: entryId, templateId, templateVersionId:t.currentVersion.id }; } catch(e){this.db.exec("ROLLBACK");throw new Error(e instanceof Error ? e.message : "entry_creation_failed");} }
  archive(userId:string, templateId:string){if(!this.db.prepare("UPDATE entry_templates SET archived_at=?,updated_at=? WHERE user_id=? AND id=? AND archived_at IS NULL").run(now(),now(),userId,templateId).changes)throw new Error("template_not_found");}
}
