import type * as SQLite from 'expo-sqlite';

type Seed = { id: string; name: string; type: string; min?: number; max?: number; unit?: string; layer?: string; ask?: boolean; condition?: boolean; outcome?: boolean; explanation?: boolean; sensitive?: boolean; choices?: string[] };
const numeric = (id: string, name: string, min: number, max: number, unit = '', extra: Partial<Seed> = {}): Seed => ({ id, name, type: 'number', min, max, unit, ...extra });
const choices = (id: string, name: string, values: string[], extra: Partial<Seed> = {}): Seed => ({ id, name, type: 'single_choice', choices: values, ...extra });
const seeds: Seed[] = [
  choices('time_period', '時間帯', ['morning', 'daytime', 'evening', 'night'], { condition: true }), choices('day_of_week', '曜日', ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'], { condition: true }), choices('day_type', '日種別', ['weekday', 'weekend', 'holiday'], { condition: true }),
  ...'observed_at responded_at prompted_at'.split(' ').map((id) => ({ id, name: id, type: 'datetime' })), { id: 'minutes_since_wake', name: '起床からの経過分', type: 'duration_minutes', min: 0, max: 1440, unit: '分' },
  choices('activity_category', '活動カテゴリ', ['work', 'study', 'rest', 'move', 'eat', 'other'], { ask: true, condition: true }), choices('activity_phase', '活動フェーズ', ['before', 'during', 'after'], { ask: true }), choices('start_status', '開始状態', ['not_started', 'started', 'delayed', 'skipped'], { ask: true, condition: true }), choices('completion_status', '完了状態', ['completed', 'not_completed', 'interrupted', 'skipped'], { ask: true, outcome: true }),
  numeric('activity_duration_minutes', '活動時間', 0, 1440, '分'), { id: 'was_planned', name: '予定されていたか', type: 'boolean', condition: true }, numeric('activity_satisfaction', '活動満足度', 1, 5, '点', { outcome: true, ask: true }), numeric('activity_enjoyment', '活動の楽しさ', 1, 5, '点'), numeric('experienced_difficulty', '体感難易度', 1, 5, '点'),
  ...['energy_level','fatigue_level','sleepiness_level','hunger_level','physical_wellbeing','break_need'].map((id) => numeric(id, id, 1, 5, '点')), ...['mood_valence','stress_level','concentration_level','distractibility_level','mental_clarity','boredom_level','overwhelm_level','confidence_level'].map((id) => numeric(id, id, 1, 5, '点')),
  ...['is_alone','interaction_present','co_working_present','had_nap'].map((id) => ({ id, name: id, type: 'boolean' })), choices('people_present', '同席人数', ['none', 'one', 'several', 'many']),
  numeric('sleep_duration_minutes', '睡眠時間', 0, 1440, '分'), numeric('sleep_quality', '睡眠の質', 1, 5, '点'), numeric('wake_refreshment', '起床時の回復感', 1, 5, '点'),
  numeric('answer_confidence', '回答確信度', 1, 5, '点'), numeric('response_delay_minutes', '回答遅延時間', 0, 10080, '分'), choices('capture_mode', '取得モード', ['momentary_observation', 'immediate_follow_up', 'retrospective_entry', 'system_import']), choices('value_source', '値の取得元', ['user', 'system', 'device', 'external_app', 'derived', 'ai_inferred']), choices('missing_reason', '欠損理由', ['unanswered', 'not_applicable', 'permission_denied', 'source_failure', 'unknown', 'expired', 'skipped']),
  ...['task_importance','task_urgency','task_interest','task_clarity','task_complexity','task_autonomy'].map((id) => numeric(id, id, 1, 5, '点', { layer: 'hypothesis_dependent', ask: true, condition: true })), numeric('start_delay_minutes', '開始遅延', 0, 1440, '分', { layer: 'hypothesis_dependent', ask: true, outcome: true }), numeric('interruption_count', '中断回数', 0, 100, '回', { layer: 'hypothesis_dependent' }), numeric('context_switch_count', 'コンテキスト切替回数', 0, 100, '回', { layer: 'hypothesis_dependent' }), numeric('noise_level', '騒音レベル', 0, 100, '点', { layer: 'hypothesis_dependent' }), numeric('environmental_distraction', '環境からの注意散漫', 1, 5, '点', { layer: 'hypothesis_dependent' }), numeric('evaluation_pressure', '評価プレッシャー', 1, 5, '点', { layer: 'hypothesis_dependent' }), numeric('minutes_since_meal', '食事からの経過分', 0, 1440, '分', { layer: 'hypothesis_dependent' }), numeric('caffeine_amount_mg', 'カフェイン量', 0, 1000, 'mg', { layer: 'hypothesis_dependent' }), numeric('minutes_until_next_event', '次の予定までの分', 0, 1440, '分', { layer: 'hypothesis_dependent' }), numeric('schedule_density', '予定密度', 0, 24, '件', { layer: 'hypothesis_dependent' }), numeric('time_pressure', '時間的圧迫感', 1, 5, '点', { layer: 'hypothesis_dependent' }), numeric('recent_screen_time_minutes', '直近の画面時間', 0, 1440, '分', { layer: 'hypothesis_dependent' }), numeric('notification_received_count', '通知受信数', 0, 1000, '件', { layer: 'hypothesis_dependent' }), ...['outcome_quality','sense_of_accomplishment','energy_after','mood_after'].map((id) => numeric(id, id, 1, 5, '点', { layer: 'hypothesis_dependent', outcome: true })),
  ...['precise_location','location_history','heart_rate','heart_rate_variability','medication_taken','health_condition_tags','menstrual_cycle_phase','alcohol_intake_level','nicotine_intake','severe_distress_flag','interaction_person_id','message_content'].map((id) => ({ id, name: id, type: 'short_text', layer: 'sensitive', sensitive: true }))
];

export const PARAMETER_SEEDS = seeds.map((item) => ({ ...item, name: item.name.replaceAll('_', ' ') }));
const now = () => new Date().toISOString();
const SYSTEM_PARAMETER_IDS = new Set(['observed_at', 'responded_at', 'prompted_at', 'time_period', 'day_of_week', 'day_type', 'minutes_since_wake', 'capture_mode', 'value_source', 'missing_reason', 'response_delay_minutes']);
function governanceDomain(id: string) { if (id.includes('sleep') || id === 'had_nap' || id === 'wake_refreshment') return 'sleep'; if (id.includes('mood') || id.includes('stress') || id.includes('boredom') || id.includes('overwhelm')) return 'emotion'; if (id.includes('concentration') || id.includes('clarity') || id.includes('distractibility')) return 'cognition'; if (id.includes('task_') || id.includes('procrastination')) return 'motivation'; if (id.includes('location') || id.includes('noise') || id.includes('distraction')) return 'environment'; if (id.includes('screen') || id.includes('notification')) return 'digital'; if (id.includes('energy') || id.includes('fatigue') || id.includes('hunger') || id.includes('physical')) return 'physical'; if (id.includes('completion') || id.includes('satisfaction') || id.includes('outcome')) return 'outcome'; if (id.includes('answer_') || id.includes('response_') || id.includes('capture_') || id === 'missing_reason') return 'quality'; if (id.includes('activity')) return 'activity'; if (id.includes('schedule') || id.includes('time_') || id.includes('day_') || id.includes('minutes_')) return 'time'; return 'quality'; }
export async function seedParameterDefinitions(db: SQLite.SQLiteDatabase) {
  const timestamp = now();
  for (const seed of PARAMETER_SEEDS) {
    const layer = seed.layer ?? 'base'; const sensitivity = seed.sensitive ? 'sensitive' : 'normal'; const askable = seed.ask ? 1 : 0;
    await db.runAsync(`INSERT OR IGNORE INTO parameter_definitions (id,name_ja,description_ja,value_type,minimum_value,maximum_value,unit,parameter_layer,temporal_type,askable,usable_as_condition,usable_as_outcome,usable_as_explanation,sensitivity,enabled_by_default,is_active,definition_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, seed.id, seed.name, `${seed.name}を観測するためのパラメーター`, seed.type, seed.min ?? null, seed.max ?? null, seed.unit ?? null, layer, 'momentary', askable, seed.condition ? 1 : 0, seed.outcome ? 1 : 0, seed.explanation ? 1 : 0, sensitivity, layer === 'base' ? 1 : 0, 1, 'parameter-v1', timestamp, timestamp);
    for (const [sort, value] of (seed.choices ?? []).entries()) await db.runAsync('INSERT OR IGNORE INTO parameter_allowed_values (parameter_id,value_key,label_ja,sort_order,numeric_value,is_active,definition_version) VALUES (?,?,?,?,?,?,?)', seed.id, value, value, sort, null, 1, 'parameter-v1');
    await db.runAsync('INSERT OR IGNORE INTO parameter_source_definitions (parameter_id,source_type,provider_key,priority,requires_permission,requires_user_confirmation,transformation_version) VALUES (?,?,?,?,?,?,?)', seed.id, SYSTEM_PARAMETER_IDS.has(seed.id) ? 'system' : 'user', '', 100, seed.sensitive ? 1 : 0, 0, 'source-v1');
    await db.runAsync('INSERT OR IGNORE INTO parameter_question_metadata (parameter_id,measurement_target_ja,time_reference,subject_type,answer_format,generation_version) VALUES (?,?,?,?,?,?)', seed.id, seed.name, 'current', 'user', seed.type === 'number' || seed.type === 'duration_minutes' ? 'number' : seed.type === 'boolean' ? 'boolean' : seed.type === 'datetime' ? 'short_text' : seed.type === 'single_choice' ? 'single_choice' : 'short_text', 'question-v1');
    await db.runAsync('INSERT OR IGNORE INTO parameter_ai_access_policies (parameter_id,external_ai_allowed,access_level,individual_consent_required,usable_for_hypothesis_generation,usable_for_question_generation,usable_for_explanation,policy_version) VALUES (?,?,?,?,?,?,?,?)', seed.id, seed.sensitive ? 0 : 1, seed.sensitive ? 'none' : 'aggregate_only', seed.sensitive ? 1 : 0, seed.sensitive ? 0 : 1, seed.sensitive ? 0 : 1, seed.sensitive ? 0 : 1, 'ai-policy-v1');
    await db.runAsync('INSERT OR IGNORE INTO parameter_governance (parameter_id,domain,aliases_ja_json,status,comparable_parameter_ids_json,conflicting_parameter_ids_json,governance_version,updated_at) VALUES (?,?,?,?,?,?,?,?)', seed.id, seed.sensitive ? 'sensitive' : governanceDomain(seed.id), JSON.stringify([seed.name]), 'active', '[]', '[]', 'governance-v1', timestamp);
  }
}
