import type * as SQLite from 'expo-sqlite';

type Seed = { id: string; name: string; type: string; min?: number; max?: number; unit?: string; layer?: string; ask?: boolean; condition?: boolean; outcome?: boolean; explanation?: boolean; sensitive?: boolean; active?: boolean; choices?: string[]; positiveValues?: string[] };
const ordinal = (id: string, name: string, min = 1, max = 5, extra: Partial<Seed> = {}): Seed => ({ id, name, type: 'ordinal', min, max, unit: 'point', ...extra });
const integer = (id: string, name: string, min: number, max: number, unit: string, extra: Partial<Seed> = {}): Seed => ({ id, name, type: 'integer', min, max, unit, ...extra });
const number = (id: string, name: string, min: number, max: number, unit: string, extra: Partial<Seed> = {}): Seed => ({ id, name, type: 'number', min, max, unit, ...extra });
const choice = (id: string, name: string, choices: string[], extra: Partial<Seed> = {}): Seed => ({ id, name, type: 'single_choice', choices, ...extra });
const baseRoles = { ask: true, condition: true, outcome: true, explanation: true };

const seeds: Seed[] = [
  choice('observed_at', '観測日時', [], { type: 'datetime' }), choice('responded_at', '回答日時', [], { type: 'datetime' }), choice('prompted_at', '提示日時', [], { type: 'datetime' }),
  choice('time_period', '時間帯', ['morning', 'daytime', 'evening', 'night'], { condition: true }), choice('day_of_week', '曜日', ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'], { condition: true }), choice('day_type', '日種別', ['weekday', 'weekend', 'holiday'], { condition: true }), integer('minutes_since_wake', '起床からの経過分', 0, 1440, 'minutes'),
  choice('activity_category', '活動カテゴリ', ['work', 'study', 'rest', 'move', 'eat', 'other'], { ask: true, condition: true }), choice('activity_phase', '活動フェーズ', ['before', 'during', 'after'], { ask: true }), choice('start_status', '開始状態', ['not_started', 'started', 'delayed', 'skipped'], { ask: true, condition: true, positiveValues: ['started'] }), choice('completion_status', '完了状態', ['completed', 'not_completed', 'interrupted', 'skipped'], { ask: true, outcome: true, positiveValues: ['completed'] }), integer('activity_duration_minutes', '活動時間', 0, 1440, 'minutes'), ordinal('activity_satisfaction', '活動満足度', 1, 5, { ...baseRoles }), ordinal('activity_enjoyment', '活動の楽しさ', 1, 5), ordinal('experienced_difficulty', '体感難易度', 1, 5),
  ...['energy_level', 'fatigue_level', 'sleepiness_level', 'hunger_level', 'physical_wellbeing', 'break_need'].map((id) => ordinal(id, id, 1, 5, { ...baseRoles })),
  ...['mood_valence', 'stress_level', 'concentration_level', 'distractibility_level', 'mental_clarity', 'boredom_level', 'overwhelm_level', 'confidence_level'].map((id) => ordinal(id, id, 1, 5, { ...baseRoles })),
  { id: 'is_alone', name: '一人でいる', type: 'boolean', ...baseRoles }, choice('people_present', '周囲の人数', ['none', 'one', 'several', 'many']), { id: 'interaction_present', name: '交流の有無', type: 'boolean' }, { id: 'co_working_present', name: '共同作業の有無', type: 'boolean' },
  integer('sleep_duration_minutes', '睡眠時間', 0, 1440, 'minutes', { ...baseRoles }), ordinal('sleep_quality', '睡眠の質', 1, 5, { ...baseRoles }), ordinal('wake_refreshment', '起床時の回復感', 1, 5), { id: 'had_nap', name: '昼寝の有無', type: 'boolean' },
  ordinal('answer_confidence', '回答確信度', 1, 5), integer('response_delay_minutes', '回答遅延時間', 0, 10080, 'minutes'), choice('capture_mode', '取得モード', ['momentary_observation', 'immediate_follow_up', 'retrospective_entry', 'system_import']), choice('value_source', '値の取得元', ['user', 'system', 'device', 'external_app', 'derived', 'ai_inferred']), choice('missing_reason', '欠損理由', ['unanswered', 'not_applicable', 'permission_denied', 'source_failure', 'unknown', 'expired', 'skipped']),
  ...['task_importance', 'task_urgency', 'task_interest', 'task_clarity', 'task_complexity', 'task_autonomy'].map((id) => ordinal(id, id, 1, 5, { layer: 'hypothesis_dependent', ask: true, condition: true })), integer('start_delay_minutes', '開始遅延', 0, 1440, 'minutes', { layer: 'hypothesis_dependent', ask: true, outcome: true }), integer('interruption_count', '中断回数', 0, 100, 'count', { layer: 'hypothesis_dependent' }), integer('context_switch_count', 'コンテキスト切替回数', 0, 100, 'count', { layer: 'hypothesis_dependent' }), number('noise_level', '騒音レベル', 0, 100, 'point', { layer: 'hypothesis_dependent' }), ordinal('environmental_distraction', '環境気散度', 1, 5, { layer: 'hypothesis_dependent' }), ordinal('evaluation_pressure', '評価プレッシャー', 1, 5, { layer: 'hypothesis_dependent' }), integer('minutes_since_meal', '食事からの経過分', 0, 1440, 'minutes', { layer: 'hypothesis_dependent' }), integer('caffeine_amount_mg', 'カフェイン量', 0, 1000, 'mg', { layer: 'hypothesis_dependent' }), integer('minutes_until_next_event', '次の予定までの分', 0, 1440, 'minutes', { layer: 'hypothesis_dependent' }), integer('schedule_density', '予定密度', 0, 24, 'count', { layer: 'hypothesis_dependent' }), ordinal('time_pressure', '時間的切迫感', 1, 5, { layer: 'hypothesis_dependent' }), integer('recent_screen_time_minutes', '直近画面時間', 0, 1440, 'minutes', { layer: 'hypothesis_dependent' }), integer('notification_received_count', '通知受信回数', 0, 1000, 'count', { layer: 'hypothesis_dependent' }), ...['outcome_quality', 'sense_of_accomplishment', 'energy_after', 'mood_after'].map((id) => ordinal(id, id, 1, 5, { layer: 'hypothesis_dependent', outcome: true })),
  integer('heart_rate', '心拍数', 0, 240, 'bpm', { layer: 'sensitive', sensitive: true, active: false }), number('heart_rate_variability', '心拍変動', 0, 500, 'ms', { layer: 'sensitive', sensitive: true, active: false }), { id: 'medication_taken', name: '服薬の有無', type: 'boolean', layer: 'sensitive', sensitive: true, active: false }, choice('menstrual_cycle_phase', '月経周期フェーズ', ['menstrual', 'follicular', 'ovulatory', 'luteal', 'unknown'], { layer: 'sensitive', sensitive: true, active: false }), { id: 'nicotine_intake', name: 'ニコチン摂取', type: 'boolean', layer: 'sensitive', sensitive: true, active: false }, { id: 'severe_distress_flag', name: '強い苦痛フラグ', type: 'boolean', layer: 'sensitive', sensitive: true, active: false }, { id: 'precise_location', name: '詳細位置', type: 'short_text', layer: 'sensitive', sensitive: true, active: false }, ...['location_history', 'health_condition_tags', 'alcohol_intake_level', 'interaction_person_id', 'message_content'].map((id) => ({ id, name: id, type: 'short_text', layer: 'sensitive', sensitive: true, active: false })),
];

export const PARAMETER_SEEDS = seeds;
const now = () => new Date().toISOString();
const SYSTEM_PARAMETER_IDS = new Set(['observed_at', 'responded_at', 'prompted_at', 'time_period', 'day_of_week', 'day_type', 'minutes_since_wake', 'capture_mode', 'value_source', 'missing_reason', 'response_delay_minutes']);
function governanceDomain(id: string) { if (id.includes('sleep') || id === 'had_nap' || id === 'wake_refreshment') return 'sleep'; if (id.includes('mood') || id.includes('stress') || id.includes('boredom') || id.includes('overwhelm')) return 'emotion'; if (id.includes('concentration') || id.includes('clarity') || id.includes('distractibility')) return 'cognition'; if (id.includes('task_') || id.includes('procrastination')) return 'motivation'; if (id.includes('location') || id.includes('noise') || id.includes('distraction')) return 'environment'; if (id.includes('screen') || id.includes('notification')) return 'digital'; if (id.includes('energy') || id.includes('fatigue') || id.includes('hunger') || id.includes('physical')) return 'physical'; if (id.includes('completion') || id.includes('satisfaction') || id.includes('outcome')) return 'outcome'; if (id.includes('answer_') || id.includes('response_') || id.includes('capture_') || id === 'missing_reason') return 'quality'; if (id.includes('activity')) return 'activity'; if (id.includes('schedule') || id.includes('time_') || id.includes('day_') || id.includes('minutes_')) return 'time'; return 'quality'; }
export async function seedParameterDefinitions(db: SQLite.SQLiteDatabase) {
  const timestamp = now();
  for (const seed of PARAMETER_SEEDS) {
    const layer = seed.layer ?? 'base'; const sensitivity = seed.sensitive ? 'sensitive' : 'normal'; const askable = seed.ask ? 1 : 0; const active = seed.active === false ? 0 : 1;
    await db.runAsync(`INSERT INTO parameter_definitions (id,name_ja,description_ja,value_type,minimum_value,maximum_value,unit,parameter_layer,temporal_type,askable,usable_as_condition,usable_as_outcome,usable_as_explanation,sensitivity,enabled_by_default,is_active,definition_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name_ja=excluded.name_ja,description_ja=excluded.description_ja,value_type=excluded.value_type,minimum_value=excluded.minimum_value,maximum_value=excluded.maximum_value,unit=excluded.unit,parameter_layer=excluded.parameter_layer,askable=excluded.askable,usable_as_condition=excluded.usable_as_condition,usable_as_outcome=excluded.usable_as_outcome,usable_as_explanation=excluded.usable_as_explanation,sensitivity=excluded.sensitivity,enabled_by_default=excluded.enabled_by_default,is_active=excluded.is_active,definition_version=excluded.definition_version,updated_at=excluded.updated_at`, seed.id, seed.name, `${seed.name}を観測するためのパラメーター`, seed.type, seed.min ?? null, seed.max ?? null, seed.unit ?? null, layer, 'momentary', askable, seed.condition ? 1 : 0, seed.outcome ? 1 : 0, seed.explanation ? 1 : 0, sensitivity, layer === 'base' ? 1 : 0, active, 'parameter-v2', timestamp, timestamp);
    await db.runAsync('DELETE FROM parameter_allowed_values WHERE parameter_id=?', seed.id);
    for (const [sort, value] of (seed.choices ?? []).entries()) await db.runAsync('INSERT INTO parameter_allowed_values (parameter_id,value_key,label_ja,sort_order,numeric_value,is_active,definition_version) VALUES (?,?,?,?,?,?,?)', seed.id, value, value, sort, null, 1, 'parameter-v2');
    await db.runAsync('INSERT INTO parameter_source_definitions (parameter_id,source_type,provider_key,priority,requires_permission,requires_user_confirmation,transformation_version) VALUES (?,?,?,?,?,?,?) ON CONFLICT(parameter_id,source_type,provider_key) DO UPDATE SET requires_permission=excluded.requires_permission,transformation_version=excluded.transformation_version', seed.id, SYSTEM_PARAMETER_IDS.has(seed.id) ? 'system' : 'user', '', 100, 0, 0, 'source-v2');
    const answerFormat = ['number', 'integer', 'ordinal', 'duration_minutes', 'percentage'].includes(seed.type) ? 'number' : seed.type === 'boolean' ? 'boolean' : seed.type === 'single_choice' ? 'single_choice' : ['multi_choice', 'tag_set'].includes(seed.type) ? 'multi_choice' : 'short_text';
    await db.runAsync('INSERT OR REPLACE INTO parameter_question_metadata (parameter_id,measurement_target_ja,time_reference,subject_type,answer_format,generation_version) VALUES (?,?,?,?,?,?)', seed.id, seed.name, seed.id.includes('sleep') ? 'last_night' : 'current', 'user', answerFormat, 'question-v2');
    await db.runAsync('INSERT INTO parameter_ai_access_policies (parameter_id,external_ai_allowed,access_level,individual_consent_required,usable_for_hypothesis_generation,usable_for_question_generation,usable_for_explanation,policy_version) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(parameter_id) DO UPDATE SET external_ai_allowed=excluded.external_ai_allowed,access_level=excluded.access_level,individual_consent_required=excluded.individual_consent_required,usable_for_hypothesis_generation=excluded.usable_for_hypothesis_generation,usable_for_question_generation=excluded.usable_for_question_generation,usable_for_explanation=excluded.usable_for_explanation,policy_version=excluded.policy_version', seed.id, seed.sensitive ? 0 : 1, seed.sensitive ? 'none' : 'aggregate_only', seed.sensitive ? 1 : 0, seed.sensitive ? 0 : 1, seed.sensitive ? 0 : 1, seed.sensitive ? 0 : 1, 'ai-policy-v2');
    await db.runAsync('INSERT INTO parameter_governance (parameter_id,domain,aliases_ja_json,status,comparable_parameter_ids_json,conflicting_parameter_ids_json,governance_version,updated_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(parameter_id) DO UPDATE SET domain=excluded.domain,status=excluded.status,governance_version=excluded.governance_version,updated_at=excluded.updated_at', seed.id, seed.sensitive ? 'sensitive' : governanceDomain(seed.id), '[]', active ? 'active' : 'archived', '[]', '[]', 'governance-v2', timestamp);
  }
}
