import { createHash, randomUUID } from "node:crypto";

export type SensitivityLevel = "normal" | "sensitive" | "highly_sensitive";
export type ClassificationSource = "ai_suggested" | "user_selected" | "system_rule";
export type ConsentType = "sensitive_field_processing" | "external_ai_transfer" | "highly_sensitive_downgrade";
export type ConsentScope = "field" | "single_value";
export type PrivacyConsent = { id: string; userId: string; workspaceId?: string | null; templateId?: string | null; templateVersionId?: string | null; fieldKey: string; consentType: ConsentType; providerId?: string | null; destinationFingerprint?: string | null; scope: ConsentScope; grantedAt: string; revokedAt?: string | null; createdAt: string; updatedAt: string };
export type FieldPrivacyPolicy = { sensitivityLevel: SensitivityLevel; classificationSource: ClassificationSource; prohibitedSecretRisk: boolean };
export type SensitivitySuggestion = { suggestedLevel: SensitivityLevel; reason: string; confidence: number; prohibitedSecretRisk: boolean };
export type ValuePrivacyOverride = { entryId: string; templateVersionId: string; fieldKey: string; originalLevel: "highly_sensitive"; effectiveLevel: "sensitive"; consentId: string };
export type SafeDeleteSelector = { userId: string; templateId?: string; templateVersionId?: string; fieldKey?: string; entryId?: string; consentId?: string };
export type SafeDeletePlan = { id: string; selector: SafeDeleteSelector; affectedCurrentValues: number; affectedHistoryValues: number; affectedValueOverrides?: number; affectedCorrections?: number; affectedExtractionCandidates: number; affectedLearningExamples: number; affectedBackups: number; affectedMarkdownFiles: Array<{ path: string; matches: number; preview?: string; action: "review_only" }>; requiredConfirmationText: string; createdAt: string };

const secretKeyPattern = /(password|passwd|api[_-]?key|secret|token|cookie|session|card|cvv|ssn|credential|auth|private[_-]?key|recovery|otp)/i;
const highlySensitivePattern = /(precise|exact|location|gps|health|diagnos|medication|message|person|identity|passport|government|financial|bank|sexual|trauma|distress)/i;
const secretValuePattern = /(?:sk-[A-Za-z0-9]{20,}|gh[pousr]_[A-Za-z0-9_]{20,}|AKIA[0-9A-Z]{16}|eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,})/;
export function suggestFieldPrivacy(field: { fieldKey: string; label?: string; description?: string; sensitivity?: string }): SensitivitySuggestion { const text = `${field.fieldKey} ${field.label ?? ""} ${field.description ?? ""}`; if (secretKeyPattern.test(text)) return { suggestedLevel: "highly_sensitive", reason: "The field may contain a secret, credential, or access token.", confidence: 0.98, prohibitedSecretRisk: true }; if (highlySensitivePattern.test(text)) return { suggestedLevel: "highly_sensitive", reason: "The field may identify a person or contain health, location, or intimate information.", confidence: 0.9, prohibitedSecretRisk: false }; if (field.sensitivity === "sensitive") return { suggestedLevel: "sensitive", reason: "The existing template marked this field as sensitive.", confidence: 0.85, prohibitedSecretRisk: false }; return { suggestedLevel: "normal", reason: "No sensitive pattern was detected.", confidence: 0.7, prohibitedSecretRisk: false }; }
export function normalizePrivacyPolicy(input: Partial<FieldPrivacyPolicy> & { fieldKey?: string; label?: string; description?: string; sensitivity?: string }): FieldPrivacyPolicy { const suggestion = suggestFieldPrivacy({ fieldKey: input.fieldKey ?? "", label: input.label, description: input.description, sensitivity: input.sensitivity }); const level = input.sensitivityLevel ?? (input.sensitivity === "sensitive" ? "sensitive" : suggestion.suggestedLevel); return { sensitivityLevel: level, classificationSource: input.classificationSource ?? "system_rule", prohibitedSecretRisk: input.prohibitedSecretRisk ?? suggestion.prohibitedSecretRisk }; }
export function validatePersistablePrivacyPolicy(input: Partial<FieldPrivacyPolicy> & { fieldKey: string; label?: string; description?: string; sensitivity?: string }): FieldPrivacyPolicy { const policy = normalizePrivacyPolicy(input); const suggestion = suggestFieldPrivacy(input); if (policy.prohibitedSecretRisk || suggestion.prohibitedSecretRisk) throw new Error("prohibited_secret_field_definition"); if (policy.classificationSource === "ai_suggested") throw new Error("privacy_classification_confirmation_required"); return policy; }
export function containsProhibitedSecretValue(value: unknown): boolean { return typeof value === "string" && secretValuePattern.test(value); }
export function destinationFingerprint(input: { providerId: string; host: string; connectionType?: string; profileId?: string }): string { return createHash("sha256").update(JSON.stringify({ providerId: input.providerId, host: input.host, connectionType: input.connectionType ?? "api", profileId: input.profileId ?? null })).digest("hex").slice(0, 32); }
export function consentIsActive(consent: Pick<PrivacyConsent, "grantedAt" | "revokedAt"> | null | undefined): boolean { return Boolean(consent && !consent.revokedAt && Number.isFinite(Date.parse(consent.grantedAt))); }
export function requiredConsentType(level: SensitivityLevel): ConsentType | null { return level === "highly_sensitive" ? "sensitive_field_processing" : level === "sensitive" ? "sensitive_field_processing" : null; }
export function newConsentId(): string { return `consent_${randomUUID().replaceAll("-", "")}`; }
export function confirmationText(count: number): string { return `DELETE ${count} ITEMS`; }
export function safeDeleteSelectorKey(selector: SafeDeleteSelector): string { return JSON.stringify(selector, Object.keys(selector).sort()); }
