import test from 'node:test';
import assert from 'node:assert/strict';
import { HYPOTHESIS_TEMPLATES } from '../src/features/hypothesisTemplates.ts';
import { chooseDailyMinutes } from '../src/notifications/policy.ts';
import { classifyTimePeriod } from '../src/domain/timePeriod.ts';
import { resolveCheckinTiming } from '../src/storage/checkinTiming.ts';

test('templates keep display direction and evaluator direction aligned', () => { const night = HYPOTHESIS_TEMPLATES.find((item) => item.key === 'night_completion')!; const day = HYPOTHESIS_TEMPLATES.find((item) => item.key === 'day_completion')!; assert.equal(night.spec.outcome.field, 'completed'); assert.equal(night.spec.expectation.relation, 'cohort_a_less_than_b'); assert.equal(day.spec.expectation.relation, 'cohort_a_greater_than_b'); assert.match(night.hypothesisStatement, /完了率/); assert.match(day.hypothesisStatement, /完了率/); });
test('captured time period is the single observation time basis', () => { assert.equal(classifyTimePeriod(new Date('2026-07-20T07:00:00')), 'day'); assert.equal(classifyTimePeriod(new Date('2026-07-20T18:00:00')), 'night'); assert.equal(classifyTimePeriod(new Date('2026-07-20T05:59:00')), 'night'); });
test('check-in timing uses the notification time and four-hour expiry', () => { const timing = resolveCheckinTiming('2026-07-20T10:15:00.000Z'); assert.equal(timing.scheduledAt, '2026-07-20T10:15:00.000Z'); assert.equal(new Date(timing.expiresAt).getTime() - new Date(timing.scheduledAt).getTime(), 4 * 60 * 60 * 1000); });
test('daily scheduler fills the limit without duplicate times', () => { const settings = { notification_enabled: true, window_start: '08:00', window_end: '22:00', daily_limit: 3, minimum_interval_minutes: 180, quiet_periods: [{ start: '12:00', end: '13:00' }] }; const dates = chooseDailyMinutes(new Date('2026-07-20T00:00:00'), settings, 42); assert.equal(dates.length, 3); assert.equal(new Set(dates.map((date) => date.toISOString())).size, 3); assert.ok(dates.every((date) => date.getHours() >= 8 && date.getHours() <= 22)); assert.ok(Math.abs(dates[1].getTime() - dates[0].getTime()) >= 180 * 60 * 1000); });
test('daily scheduler respects overnight quiet periods and existing reservations', () => { const settings = { notification_enabled: true, window_start: '08:00', window_end: '23:00', daily_limit: 3, minimum_interval_minutes: 120, quiet_periods: [{ start: '22:00', end: '07:00' }] }; const dates = chooseDailyMinutes(new Date('2026-07-20T00:00:00'), settings, 7, [10 * 60]); assert.equal(dates.length, 2); assert.ok(dates.every((date) => date.getHours() >= 8 && date.getHours() < 22)); assert.ok(dates.every((date) => Math.abs(date.getHours() * 60 + date.getMinutes() - 600) >= 120)); });
