#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync, existsSync, readdirSync, statSync, appendFileSync } from "node:fs";
import { join, resolve, relative } from "node:path";
import { readMarkdownEntry, withEntryMetadata } from "../../../packages/workspace-sync/src/index.ts";
const api=process.env.METHEORY_API_URL ?? "http://127.0.0.1:8100"; const root=process.cwd(); const userId=process.env.METHEORY_USER_ID ?? "local-user";
async function request(path:string, init?:RequestInit){const r=await fetch(`${api}${path}`,init);const data=await r.json() as any;if(!r.ok)throw new Error(data.error??`api_${r.status}`);return data;}
function initWorkspace(){for(const dir of ["notes","templates/drafts","templates/exports","inbox","attachments",".metheory/cache",".metheory/logs"] )mkdirSync(join(root,dir),{recursive:true});mkdirSync(join(root,".vscode"),{recursive:true});if(!existsSync(join(root,".metheory/workspace.json")))writeFileSync(join(root,".metheory/workspace.json"),JSON.stringify({version:1,notesDirectory:"notes",apiUrl:api},null,2));if(!existsSync(join(root,"AGENTS.md")))writeFileSync(join(root,"AGENTS.md"),"# MeTheory Workspace\n\n- Edit notes/ Markdown normally.\n- Do not edit .metheory/ directly.\n- Use the metheory CLI for SQLite-backed changes.\n- Preserve metheory_entry_id and recorded_at during sync.\n");console.log("workspace_initialized");}
async function syncFile(file:string){const path=relative(root,resolve(root,file));const text=readFileSync(resolve(root,file),"utf8");const entry=readMarkdownEntry(path,text);const result=await request("/v1/entries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:entry.entryId,userId,externalSource:"vscode",externalSourceId:path,title:entry.title,body:entry.body,recordedAt:entry.recordedAt,sourceUpdatedAt:new Date(statSync(resolve(root,file)).mtimeMs).toISOString()})});const metadata={metheory_entry_id:String(result.entry.id)};if(!entry.entryId)writeFileSync(resolve(root,file),withEntryMetadata(text,metadata));console.log(JSON.stringify({path,created:result.created,id:result.entry.id}));}
function markdownFiles(dir:string):string[]{return readdirSync(dir,{withFileTypes:true}).flatMap(item=>item.isDirectory()?markdownFiles(join(dir,item.name)):item.name.endsWith(".md")?[join(dir,item.name)]:[]);}
async function recordTemplate(templateId:string){const detail=await request(`/v1/templates/${encodeURIComponent(templateId)}?userId=${encodeURIComponent(userId)}`);const fields=detail.currentVersion.fields as Array<any>;const values:Record<string,unknown>={};for(const field of fields){const answer=globalThis.prompt?.(`${field.label}${field.required?" *":""}`)??"";if(field.value_type==="boolean")values[field.field_key]=answer.toLowerCase()==="true"||answer==="1";else if(["integer","number","scale","duration_seconds"].includes(field.value_type))values[field.field_key]=Number(answer);else if(field.value_type==="multi_choice")values[field.field_key]=answer.split(",").map((item:string)=>item.trim()).filter(Boolean);else values[field.field_key]=answer;}const created=await request(`/v1/templates/${encodeURIComponent(templateId)}/entries`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId,values,title:detail.name,body:""})});const filename=`${new Date().toISOString().slice(0,10)}-${created.id}.md`;mkdirSync(join(root,"notes"),{recursive:true});writeFileSync(join(root,"notes",filename),`---\nmetheory_entry_id: ${created.id}\ntemplate_id: ${templateId}\ntemplate_version_id: ${created.templateVersionId}\nrecorded_at: ${new Date().toISOString()}\n---\n\n# ${detail.name}\n`);console.log(JSON.stringify({id:created.id,path:join("notes",filename)}));}
async function main(){const [, ,command,sub,...args]=process.argv;if(command==="workspace"&&sub==="init")return initWorkspace();if(command==="entry"&&sub==="sync")return syncFile(args[0]);if(command==="workspace"&&sub==="sync"){for(const file of markdownFiles(join(root,"notes")))await syncFile(file);return;}if(command==="entry"&&sub==="list"){console.log(JSON.stringify(await request(`/v1/entries?userId=${encodeURIComponent(userId)}`),null,2));return;}if(command==="entry"&&sub==="search"){console.log(JSON.stringify(await request(`/v1/search?userId=${encodeURIComponent(userId)}&q=${encodeURIComponent(args.join(" "))}`),null,2));return;}if(command==="template"&&sub==="list"){console.log(JSON.stringify(await request(`/v1/templates?userId=${encodeURIComponent(userId)}`),null,2));return;}if(command==="template"&&sub==="generate"){const theme=args[0]??"";console.log(JSON.stringify(await request("/v1/templates/generate-draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId,theme})}),null,2));return;}if(command==="template"&&sub==="record"&&args[0])return recordTemplate(args[0]);console.error("usage: metheory workspace init|sync; entry sync <file>|list|search <query>; template list|generate <theme>|record <id>");process.exitCode=1;}main().catch(error=>{appendFileSync(join(root,".metheory/logs","cli.log"),`${new Date().toISOString()} ${error instanceof Error?error.message:"error"}\n`);console.error(error instanceof Error?error.message:"error");process.exitCode=1;});
