import { EVIDENCE_POLICY } from '../evidencePolicy.ts';
import { correctedAlpha, exactPermutationPValue } from '../significance.ts';

export type CandidateParameter = { id: string; fieldKey?: string; templateId?: string; templateVersionId?: string; semanticRole?: string; sensitivity?: string; semanticMergeAllowed?: boolean; scaleFingerprint?: string; unit?: string; sourceKind?: "entry" | "activitywatch" | "baseline"; allowedConditionRoles?: string[]; allowedOutcomeRoles?: string[]; nameJa: string; valueType: string; minimumValue?: number | null; maximumValue?: number | null; positiveValues?: unknown[]; orderedValues?: unknown[]; numericMapping?: Record<string, number>; usableAsCondition: boolean; usableAsOutcome: boolean; active?: boolean; comparableParameterIds?: string[] };
export type AnalysisEpisodeKind = "entry" | "pcs_record" | "activity_day" | "daily_join" | "experiment_checkin" | "linked_period";
export type CandidateObservation = { episodeId: string; episodeKind?: AnalysisEpisodeKind; parameterId: string; value: unknown; isMissing?: boolean; observedAt: string };
export type CohortRule = { key: string; labelJa: string; condition: { type: 'equals' | 'range' | 'in'; value?: boolean | string | number; minimum?: number; maximum?: number; minimumInclusive?: boolean; maximumInclusive?: boolean; values?: Array<string | number> } };
export type CandidateGenerationConfig = { minimumSamplesPerCohort: number; minimumTotalSamples: number; maximumMissingRate: number; minimumNormalizedEffect: number; minimumSampleBalance: number; lookbackDays: number; maximumCandidates: number; comparisonCount?: number; pairAllowlistVersion?: string };
export type CandidateScoreBreakdown = { effectScore: number; sampleSizeScore: number; balanceScore: number; stabilityScore: number; relevanceScore: number; noveltyScore: number; missingPenalty: number; qualityPenalty: number; totalScore: number };
export type HypothesisCandidate = { id: string; candidateType: 'condition_difference' | 'belief_mismatch'; conditionParameterId: string; outcomeParameterId: string; cohortA: { key: string; labelJa: string; sampleCount: number; validSampleCount: number; missingCount: number; metricValue: number }; cohortB: { key: string; labelJa: string; sampleCount: number; validSampleCount: number; missingCount: number; metricValue: number }; eligibleEpisodeCount: number; completePairCount: number; missingConditionCount: number; missingOutcomeCount: number; missingBothCount: number; relation: 'a_greater_than_b' | 'a_less_than_b' | 'approximately_equal'; effectValue: number; normalizedEffect: number; sampleBalance: number; missingRate: number; temporalStability: number; temporalStabilityStatus: 'stable' | 'unstable' | 'unknown'; candidateScore: number; scoreBreakdown: CandidateScoreBreakdown; supportingPeriod: { startAt: string; endAt: string }; alternativeExplanationParameterIds: string[]; generationVersion: string; generatedAt: string; pValue: number | null; significanceAlpha: number; significanceMethod: 'exact_permutation' | 'not_evaluable' };
export const DEFAULT_CANDIDATE_CONFIG: CandidateGenerationConfig = { minimumSamplesPerCohort: 5, minimumTotalSamples: 12, maximumMissingRate: 0.35, minimumNormalizedEffect: 0.2, minimumSampleBalance: 0.3, lookbackDays: 30, maximumCandidates: 10 };
function finiteNumber(value: number | undefined, fallback: number): number { return Number.isFinite(value) ? Number(value) : fallback; }
export function normalizeCandidateGenerationConfig(input: Partial<CandidateGenerationConfig> = {}): CandidateGenerationConfig {
  const minimumSamplesPerCohort = Math.max(EVIDENCE_POLICY.minimumSamplesPerCohort, Math.floor(finiteNumber(input.minimumSamplesPerCohort, DEFAULT_CANDIDATE_CONFIG.minimumSamplesPerCohort)));
  return {
    minimumSamplesPerCohort,
    minimumTotalSamples: Math.max(EVIDENCE_POLICY.minimumTotalSamples, minimumSamplesPerCohort * 2, Math.floor(finiteNumber(input.minimumTotalSamples, DEFAULT_CANDIDATE_CONFIG.minimumTotalSamples))),
    maximumMissingRate: Math.max(0, Math.min(EVIDENCE_POLICY.maximumMissingRate, finiteNumber(input.maximumMissingRate, DEFAULT_CANDIDATE_CONFIG.maximumMissingRate))),
    minimumNormalizedEffect: Math.max(EVIDENCE_POLICY.minimumAbsoluteEffect, finiteNumber(input.minimumNormalizedEffect, DEFAULT_CANDIDATE_CONFIG.minimumNormalizedEffect)),
    minimumSampleBalance: Math.max(EVIDENCE_POLICY.minimumSampleBalance, Math.min(1, finiteNumber(input.minimumSampleBalance, DEFAULT_CANDIDATE_CONFIG.minimumSampleBalance))),
    lookbackDays: Math.max(1, Math.min(EVIDENCE_POLICY.maximumWindowDays, Math.floor(finiteNumber(input.lookbackDays, DEFAULT_CANDIDATE_CONFIG.lookbackDays)))),
    maximumCandidates: Math.max(1, Math.min(50, Math.floor(finiteNumber(input.maximumCandidates, DEFAULT_CANDIDATE_CONFIG.maximumCandidates)))),  ...(Number.isInteger(input.comparisonCount) && input.comparisonCount! > 0 ? { comparisonCount: Math.min(10000, input.comparisonCount!) } : {}),
    ...(input.pairAllowlistVersion ? { pairAllowlistVersion: input.pairAllowlistVersion } : {})
  };
}

export function buildCohorts(parameter: CandidateParameter, allowedValues: Array<{ valueKey: string; labelJa: string }> = []): CohortRule[] {
  if (parameter.valueType === 'boolean') return [{ key: 'true', labelJa: 'True', condition: { type: 'equals', value: true } }, { key: 'false', labelJa: 'False', condition: { type: 'equals', value: false } }];
  if (parameter.valueType === 'single_choice') return allowedValues.map((item) => ({ key: item.valueKey, labelJa: item.labelJa, condition: { type: 'equals', value: item.valueKey } }));
  const minimum = parameter.minimumValue ?? 0; const maximum = parameter.maximumValue ?? minimum + 1; const midpoint = minimum + (maximum - minimum) / 2; const integerRange = Number.isInteger(minimum) && Number.isInteger(maximum);
  if (parameter.valueType === 'integer' && integerRange) { const split = Math.ceil(midpoint); return [{ key: 'low', labelJa: 'Low', condition: { type: 'range', maximum: split - 1 } }, { key: 'high', labelJa: 'High', condition: { type: 'range', minimum: split } }]; }
  return [{ key: 'low', labelJa: 'Low', condition: { type: 'range', maximum: midpoint, maximumInclusive: false } }, { key: 'high', labelJa: 'High', condition: { type: 'range', minimum: midpoint, minimumInclusive: true } }];
}
function inRule(value: unknown, rule: CohortRule['condition']) { if (rule.type === 'equals') return value === rule.value; if (rule.type === 'in') return rule.values?.includes(value as never) ?? false; return typeof value === 'number' && (rule.minimum === undefined || (rule.minimumInclusive === false ? value > rule.minimum : value >= rule.minimum)) && (rule.maximum === undefined || (rule.maximumInclusive === false ? value < rule.maximum : value <= rule.maximum)); }
export function calculateOutcomeMetric(values: unknown[], outcome: CandidateParameter) { const valid = values.filter((value) => value !== null && value !== undefined && typeof value !== 'object'); if (!valid.length) return { value: 0, valid: 0 }; if (outcome.valueType === 'boolean') { const positiveValues = outcome.positiveValues ?? [true]; return { value: valid.filter((value) => positiveValues.some((positive) => Object.is(value, positive))).length / valid.length, valid: valid.length }; } const hasNumericSemantics = Boolean(outcome.numericMapping && Object.keys(outcome.numericMapping).length) || Boolean(outcome.orderedValues?.length); if (hasNumericSemantics) { const mapping = outcome.numericMapping ?? Object.fromEntries((outcome.orderedValues ?? []).map((value, index) => [String(value), index])); const numbers = valid.map((value) => mapping[String(value)]).filter((value): value is number => Number.isFinite(value)); return { value: numbers.length ? numbers.reduce((sum, value) => sum + value, 0) / numbers.length : 0, valid: numbers.length }; } if (outcome.valueType === 'single_choice') { const positiveValues = outcome.positiveValues; if (!positiveValues?.length) return { value: 0, valid: 0 }; return { value: valid.filter((value) => positiveValues.some((positive) => Object.is(value, positive))).length / valid.length, valid: valid.length }; } const numbers = valid.filter((value): value is number => typeof value === 'number'); return { value: numbers.length ? numbers.reduce((sum, value) => sum + value, 0) / numbers.length : 0, valid: numbers.length }; }
function significanceValues(values: unknown[], outcome: CandidateParameter): number[] {
  if (outcome.valueType === "boolean") return values.flatMap((value) => typeof value === "boolean" ? [value ? 1 : 0] : []);
  if (outcome.valueType === "single_choice" && outcome.positiveValues?.length) return values.flatMap((value) => value === null || value === undefined ? [] : [(outcome.positiveValues ?? []).some((positive) => Object.is(positive, value)) ? 1 : 0]);
  const mapping = outcome.numericMapping ?? (outcome.orderedValues?.length ? Object.fromEntries(outcome.orderedValues.map((value, index) => [String(value), index])) : undefined);
  if (mapping) return values.flatMap((value) => Number.isFinite(mapping[String(value)]) ? [mapping[String(value)]] : []);
  return values.filter((value): value is number => typeof value === "number" && Number.isFinite(value));
}
function normalized(effect: number, outcome: CandidateParameter): number | null { if (['boolean', 'single_choice'].includes(outcome.valueType)) return Math.abs(effect); const minimum = outcome.minimumValue; const maximum = outcome.maximumValue; if (!Number.isFinite(minimum) || !Number.isFinite(maximum) || Number(maximum) <= Number(minimum)) return null; return Math.abs(effect) / (Number(maximum) - Number(minimum)); }
function score(effect: number, sampleSize: number, balance: number, stability: number, missingRate: number, config: CandidateGenerationConfig): CandidateScoreBreakdown { const effectScore = Math.min(1, Math.abs(effect) / Math.max(config.minimumNormalizedEffect, 0.01)); const sampleSizeScore = Math.min(1, sampleSize / (config.minimumTotalSamples * 2)); const missingPenalty = Math.max(0, missingRate - 0.1) * 0.5; const qualityPenalty = balance < config.minimumSampleBalance ? 0.25 : 0; const totalScore = Math.max(0, Math.min(1, effectScore * 0.35 + sampleSizeScore * 0.2 + balance * 0.15 + stability * 0.15 + 0.05 - missingPenalty - qualityPenalty)); return { effectScore, sampleSizeScore, balanceScore: balance, stabilityScore: stability, relevanceScore: 0, noveltyScore: 0, missingPenalty, qualityPenalty, totalScore }; }
function periodEffect(rows: Array<{ condition: unknown; outcome: unknown; observedAt: string }>, cohorts: [CohortRule, CohortRule], outcome: CandidateParameter, start: Date, end: Date) { const values = cohorts.map((cohort) => rows.filter((row) => { const time = new Date(row.observedAt); return time >= start && time <= end && inRule(row.condition, cohort.condition); }).map((row) => row.outcome)); const metrics = values.map((group) => calculateOutcomeMetric(group, outcome)); const effect = metrics[0].valid >= EVIDENCE_POLICY.minimumTemporalSamplesPerCohort && metrics[1].valid >= EVIDENCE_POLICY.minimumTemporalSamplesPerCohort ? metrics[0].value - metrics[1].value : null; const normalizedEffect = effect === null ? null : normalized(effect, outcome); return normalizedEffect !== null && normalizedEffect >= EVIDENCE_POLICY.minimumTemporalNormalizedEffect ? effect : null; }
function pairs(cohorts: CohortRule[]): Array<[CohortRule, CohortRule]> { const result: Array<[CohortRule, CohortRule]> = []; for (let index = 0; index < cohorts.length; index += 1) for (let other = index + 1; other < cohorts.length; other += 1) result.push([cohorts[index], cohorts[other]]); return result; }

export const CANDIDATE_PAIR_ALLOWLIST_VERSION = "candidate-pair-v1";
export const CANDIDATE_PAIR_ALLOWLIST: ReadonlyArray<{ conditionRole: string; outcomeRole: string; candidateType: "condition_difference" | "belief_mismatch"; version: string }> = [
  { conditionRole: "task_clarity", outcomeRole: "start_delay", candidateType: "condition_difference", version: CANDIDATE_PAIR_ALLOWLIST_VERSION },
  { conditionRole: "time_of_day", outcomeRole: "completion", candidateType: "condition_difference", version: CANDIDATE_PAIR_ALLOWLIST_VERSION },
  { conditionRole: "social_intensity", outcomeRole: "fatigue", candidateType: "condition_difference", version: CANDIDATE_PAIR_ALLOWLIST_VERSION },
  { conditionRole: "environment", outcomeRole: "focus", candidateType: "condition_difference", version: CANDIDATE_PAIR_ALLOWLIST_VERSION },
  { conditionRole: "self_rating", outcomeRole: "observed_behavior", candidateType: "condition_difference", version: CANDIDATE_PAIR_ALLOWLIST_VERSION },
  { conditionRole: "sleep_duration", outcomeRole: "energy", candidateType: "condition_difference", version: CANDIDATE_PAIR_ALLOWLIST_VERSION },
  { conditionRole: "sleep_quality", outcomeRole: "fatigue", candidateType: "condition_difference", version: CANDIDATE_PAIR_ALLOWLIST_VERSION },
  { conditionRole: "day_type", outcomeRole: "satisfaction", candidateType: "condition_difference", version: CANDIDATE_PAIR_ALLOWLIST_VERSION }
];

export function isAllowedCandidatePair(condition: CandidateParameter, outcome: CandidateParameter, pairAllowlistVersion = "none"): boolean {
  if (pairAllowlistVersion === CANDIDATE_PAIR_ALLOWLIST_VERSION) {
    return CANDIDATE_PAIR_ALLOWLIST.some((rule) => rule.version === pairAllowlistVersion && rule.candidateType === "condition_difference" && rule.conditionRole === condition.semanticRole && rule.outcomeRole === outcome.semanticRole);
  }
  if (condition.id === outcome.id || condition.sourceKind === "baseline" || outcome.sourceKind === "baseline") return false;
  if (condition.sourceKind === "activitywatch" && outcome.sourceKind === "activitywatch") return false;
  if (outcome.sourceKind === "activitywatch") {
    const allowed = outcome.allowedConditionRoles ?? ["self_rating", "mood", "energy", "fatigue", "task_clarity", "time_of_day", "day_type"];
    return Boolean(condition.semanticRole && allowed.includes(condition.semanticRole));
  }
  if (condition.sourceKind === "activitywatch") {
    const allowed = condition.allowedOutcomeRoles ?? ["completion", "satisfaction", "self_rating", "mood", "energy", "fatigue"];
    return Boolean(outcome.semanticRole && allowed.includes(outcome.semanticRole));
  }
  return true;
}
export function episodeIsEligibleForPair(kind: AnalysisEpisodeKind, condition: CandidateParameter, outcome: CandidateParameter): boolean { if (condition.sourceKind === "activitywatch" || outcome.sourceKind === "activitywatch") return kind === "daily_join"; return kind === "entry" || kind === "pcs_record" || kind === "experiment_checkin" || kind === "linked_period"; }

export function generateHypothesisCandidates(input: { parameters: CandidateParameter[]; observations: CandidateObservation[]; allowedValues?: Record<string, Array<{ valueKey: string; labelJa: string }>>; config?: Partial<CandidateGenerationConfig>; now?: string }): HypothesisCandidate[] {
  const config = normalizeCandidateGenerationConfig(input.config); const end = new Date(input.now ?? new Date().toISOString()); const start = new Date(end.getTime() - config.lookbackDays * 86400000); const observations = input.observations.filter((item) => new Date(item.observedAt) >= start && new Date(item.observedAt) <= end); const byEpisode = new Map<string, { kind: AnalysisEpisodeKind; values: Map<string, { value: unknown; isMissing: boolean; observedAt: string }> }>();
  for (const item of observations) { if (!byEpisode.has(item.episodeId)) byEpisode.set(item.episodeId, { kind: item.episodeKind ?? "entry", values: new Map() }); byEpisode.get(item.episodeId)!.values.set(item.parameterId, { value: item.value, isMissing: Boolean(item.isMissing), observedAt: item.observedAt }); }
  const result: HypothesisCandidate[] = []; const conditionParams = input.parameters.filter((item) => item.active !== false && item.usableAsCondition); const outcomeParams = input.parameters.filter((item) => item.active !== false && item.usableAsOutcome);
  for (const condition of conditionParams) for (const outcome of outcomeParams) { if (!isAllowedCandidatePair(condition, outcome, config.pairAllowlistVersion)) continue; const cohortPairs = pairs(buildCohorts(condition, input.allowedValues?.[condition.id] ?? [])); for (const cohortPair of cohortPairs) {
    const eligibleEpisodes = [...byEpisode.values()].filter((episode) => episodeIsEligibleForPair(episode.kind, condition, outcome)); const missingConditionCount = eligibleEpisodes.filter((episode) => episode.values.get(condition.id)?.isMissing || !episode.values.has(condition.id)).length; const missingOutcomeCount = eligibleEpisodes.filter((episode) => episode.values.get(outcome.id)?.isMissing || !episode.values.has(outcome.id)).length; const missingBothCount = eligibleEpisodes.filter((episode) => (episode.values.get(condition.id)?.isMissing || !episode.values.has(condition.id)) && (episode.values.get(outcome.id)?.isMissing || !episode.values.has(outcome.id))).length;
    const rows = eligibleEpisodes.flatMap((episode) => { const conditionValue = episode.values.get(condition.id); const outcomeValue = episode.values.get(outcome.id); return conditionValue && !conditionValue.isMissing ? [{ condition: conditionValue.value, outcome: outcomeValue && !outcomeValue.isMissing ? outcomeValue.value : null, observedAt: conditionValue.observedAt }] : []; }); const groups = cohortPair.map((rule) => rows.filter((row) => inRule(row.condition, rule.condition)).map((row) => row.outcome)); const sampleCounts = groups.map((group) => group.length); const metrics = groups.map((group) => calculateOutcomeMetric(group, outcome)); const missing = groups.reduce((sum, group, index) => sum + group.length - metrics[index].valid, 0); const total = sampleCounts[0] + sampleCounts[1];
    const validSampleCount = metrics[0].valid + metrics[1].valid; if (validSampleCount < config.minimumTotalSamples || metrics.some((metric) => metric.valid < config.minimumSamplesPerCohort)) continue; const effect = metrics[0].value - metrics[1].value; const normalizedEffect = normalized(effect, outcome); if (normalizedEffect === null) continue; const balance = Math.min(metrics[0].valid, metrics[1].valid) / Math.max(metrics[0].valid, metrics[1].valid, 1); const missingRate = eligibleEpisodes.length ? (missingConditionCount + missingOutcomeCount) / (2 * eligibleEpisodes.length) : 1; const firstEnd = new Date(start.getTime() + (end.getTime() - start.getTime()) / 2); const firstEffect = periodEffect(rows, cohortPair, outcome, start, firstEnd); const secondEffect = periodEffect(rows, cohortPair, outcome, new Date(firstEnd.getTime() + 1), end); const temporalStabilityStatus = firstEffect === null || secondEffect === null ? 'unknown' : Math.abs(firstEffect - secondEffect) <= Math.max(0.1, Math.abs(effect) * 0.75) && Math.sign(firstEffect) === Math.sign(secondEffect) ? 'stable' : 'unstable'; const temporalStability = temporalStabilityStatus === 'stable' ? 1 : temporalStabilityStatus === 'unknown' ? 0.5 : 0;
    if (normalizedEffect < config.minimumNormalizedEffect || balance < config.minimumSampleBalance || missingRate > config.maximumMissingRate) continue; const significance = exactPermutationPValue(significanceValues(groups[0], outcome), significanceValues(groups[1], outcome), effect >= 0 ? 'a_greater' : 'b_greater'); const significanceAlpha = correctedAlpha(config.comparisonCount ?? 1); if (!significance || significance.pValue > significanceAlpha) continue; const breakdown = score(normalizedEffect, total, balance, temporalStability, missingRate, config); const relation = effect >= 0 ? 'a_greater_than_b' : 'a_less_than_b'; const [cohortA, cohortB] = cohortPair;
    result.push({ id: `candidate_${condition.id}_${outcome.id}_${cohortA.key}_${cohortB.key}`, candidateType: 'condition_difference', conditionParameterId: condition.id, outcomeParameterId: outcome.id, cohortA: { key: cohortA.key, labelJa: cohortA.labelJa, sampleCount: sampleCounts[0], validSampleCount: metrics[0].valid, missingCount: sampleCounts[0] - metrics[0].valid, metricValue: metrics[0].value }, cohortB: { key: cohortB.key, labelJa: cohortB.labelJa, sampleCount: sampleCounts[1], validSampleCount: metrics[1].valid, missingCount: sampleCounts[1] - metrics[1].valid, metricValue: metrics[1].value }, eligibleEpisodeCount: eligibleEpisodes.length, completePairCount: rows.filter((row) => row.outcome !== null && row.outcome !== undefined).length, missingConditionCount, missingOutcomeCount, missingBothCount, relation, effectValue: effect, normalizedEffect, sampleBalance: balance, missingRate, temporalStability, temporalStabilityStatus, candidateScore: breakdown.totalScore, scoreBreakdown: breakdown, supportingPeriod: { startAt: start.toISOString(), endAt: end.toISOString() }, alternativeExplanationParameterIds: [], generationVersion: 'candidate-v8', generatedAt: end.toISOString(), pValue: significance.pValue, significanceAlpha, significanceMethod: 'exact_permutation' });
  } } return result.sort((a, b) => b.candidateScore - a.candidateScore || a.id.localeCompare(b.id)).slice(0, config.maximumCandidates);
}
